### ISSUE TITLE
[ISSUE]: I can't choose RVC files

### ISSUE THREAD

**Issue by RareFlames36** [w-okada/voice-changer#1018]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17

### Operational System

Windows 11

### GPU

RTX 3050 ti 

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

It doesn't work even I restarted my laptop, or restarted the app, there's always a error popping out if you know how to fix this please help me thanks!

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/142717345/d5aaead1-cda1-4320-9b01-76120bfe2c11)

As you can see this is the software and the cmd errors

### Logs on console

[Voice Changer] update configuration: modelSlotIndex 1700859215000
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] post_update_settings ex: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/rmvpe.onnx failed:Protobuf parsing failed.
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 337, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 345, in update_settings
  File "voice_changer\VoiceChangerV2.py", line 164, in update_settings
  File "voice_changer\RVC\RVCr2.py", line 88, in update_settings
  File "voice_changer\RVC\RVCr2.py", line 62, in initialize
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 42, in createPipeline
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 25, in getPitchExtractor
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 45, in loadPitchExtractor
  File "voice_changer\RVC\pitchExtractor\RMVPEOnnxPitchExtractor.py", line 28, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/rmvpe.onnx failed:Protobuf parsing failed.

**Comment by exciar** [comment]
reinstall the app make sure you extracted it properly
