### ISSUE TITLE
[ISSUE]:  GPU  does not appear

### ISSUE THREAD

**Issue by Kenny3vil** [w-okada/voice-changer#1055]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b.zip

### Operational System

Windows 10

### GPU

rx 580

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

Rvc

### Issue Description

In the GPU section my video card does not appear, only the CPU

### Application Screenshot

![imagen_2023-12-26_132338007](https://github.com/w-okada/voice-changer/assets/154930505/97b0a67f-a90c-411b-847b-cfb28e559e3b)

### Logs on console

    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000014F5F15BCA0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000014F5F15B580>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x0000014F5F15BD00>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer][RVC]: update_settings serverReadChunkSize:128
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer][RVC]: update_settings modelSlotIndex:1703625348000
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-12-26 13:18:04] connet sid : oNYiLnZ1Q7QRwb7hAAAC
[2023-12-26 13:18:04] connet sid : 5sFL2DoCRLXK4kxrAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: modelSlotIndex 1703625496004
[Voice Changer] model slot is changed 0 -> 4
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
Pipeline has been deleted
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000014F630C2110>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000014F5F15BCA0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x0000014F633CE230>
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer][RVC]: update_settings serverReadChunkSize:128
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer][RVC]: update_settings modelSlotIndex:1703625496004
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] post_concat_uploaded_file ex: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Users\\Gael\\AppData\\Local\\Temp\\tmpb3a_8_79\\upload_dir\\Canserbero_V2_e480_s20160.pth'
paramDict {'voiceChangerType': 'RVC', 'slot': 4, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'Canserbero_V2_e480_s20160.pth', 'kind': 'rvcModel', 'dir': ''}, {'name': 'trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index', 'kind': 'rvcIndex', 'dir': ''}], 'params': {}}
FILE: LoadModelParamFile(name='Canserbero_V2_e480_s20160.pth', kind='rvcModel', dir='')
move to C:\Users\Gael\AppData\Local\Temp\tmpb3a_8_79\upload_dir\Canserbero_V2_e480_s20160.pth -> model_dir\4\Canserbero_V2_e480_s20160.pth
FILE: LoadModelParamFile(name='trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index', kind='rvcIndex', dir='')
move to C:\Users\Gael\AppData\Local\Temp\tmpb3a_8_79\upload_dir\trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index -> model_dir\4\trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index
RVC:: slotInfo.modelFile Canserbero_V2_e480_s20160.pth
paramDict {'voiceChangerType': 'RVC', 'slot': 4, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'Canserbero_V2_e480_s20160.pth', 'kind': 'rvcModel', 'dir': ''}, {'name': 'trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index', 'kind': 'rvcIndex', 'dir': ''}], 'params': {}}
[Voice Changer] post_load_model ex: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'model_dir\\4\\Canserbero_V2_e480_s20160.pth'
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 92, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 150, in loadModel
  File "shutil.py", line 750, in rmtree
  File "shutil.py", line 620, in _rmtree_unsafe
  File "shutil.py", line 618, in _rmtree_unsafe
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'model_dir\\4\\Canserbero_V2_e480_s20160.pth'
[Voice Changer] Official Model(pyTorch) : v2
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='Canserbero_V2_e480_s20160', description='', credit='', termsOfUseUrl='', iconFile='', speakers={0: 'target'}, modelFile='Canserbero_V2_e480_s20160.pth', indexFile='trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=48000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2')
params, LoadModelParams(voiceChangerType='RVC', slot=4, isSampleMode=False, sampleId=None, files=[LoadModelParamFile(name='Canserbero_V2_e480_s20160.pth', kind='rvcModel', dir=''), LoadModelParamFile(name='trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index', kind='rvcIndex', dir='')], params={})
[2023-12-26 13:20:13] connet sid : Icblc7yZwoXj7KdMAAAF
[Voice Changer] update configuration: modelSlotIndex 1703625644004
[Voice Changer] model slot is changed 4 -> 4
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\4\trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000014FA3DA2FE0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000014FDC403040>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x0000014FDC4030A0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer][RVC]: update_settings serverReadChunkSize:128
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer][RVC]: update_settings modelSlotIndex:1703625644004
Pipeline has been deleted
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
SlotInfo::: RVCModelSlot(slotIndex=4, voiceChangerType='RVC', name='Canserbero_V2_e480_s20160', description='', credit='', termsOfUseUrl='', iconFile='model_dir\\4\\ab6761610000e5eba91405d63c939682e4efdcbc.jpg', speakers={'0': 'target'}, modelFile='Canserbero_V2_e480_s20160.pth', indexFile='trained_IVF2024_Flat_nprobe_1_Canserbero_V2_v2.index', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=48000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2')
[2023-12-26 13:21:44] connet sid : PGYDw8uEW07IIFPDAAAH
[2023-12-26 13:23:16] connet sid : 2JxluMLAxYylnHcwAAAJ

**Comment by Kraugelz** [comment]
Me to

**Comment by Alathiel** [comment]
You should download the DirectML version with amd gpu
