### ISSUE TITLE
[ISSUE]: cannot use rvc but can use beatrice

### ISSUE THREAD

**Issue by kahtcw** [w-okada/voice-changer#1065]
### Voice Changer Version

MMVCServerSIO_win_onxxgpu-cuda_v.1.5.3.17b

### Operational System

Windows 11 Home 64-bit (10.0, Build 22621)

### GPU

NVIDIA GeForce RTX 2050

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

can use beatrice but cannot use rvc

### Application Screenshot

![photo_2024-01-07_21-25-36](https://github.com/w-okada/voice-changer/assets/142160561/02076e22-d54a-41aa-b855-6c7db2cd507b)

### Logs on console

C:\Users\teoch\Downloads\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :main
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[VCClient] wait web server... done 200
[2024-01-07 21:14:32] connet sid : JT-Xb6ibX9rwaxXaAAAC
[2024-01-07 21:14:32] connet sid : 2Y4dpld_AYte-GJ-AAAD
[Voice Changer] update configuration: enableServerAudio 0
[Voice Changer] update configuration: silentThreshold 0.00091
[Voice Changer] update configuration: silentThreshold 0.00098
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: recordIO 1
-------------------------- - - - 48000, 48000
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: gpu -1
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] update configuration: f0Detector dio
[Voice Changer] update configuration: serverReadChunkSize 192
[Voice Changer] update configuration: f0Detector crepe
[Voice Changer] update configuration: gpu 0
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.

**Comment by Numidyum** [comment]
I have same issue too

**Comment by kahtcw** [comment]
can anyone help?

**Comment by kahtcw** [comment]
how do i go about fixing this? sorry im not very adept in IT or coding, do i need to change a few things on the code?

**Comment by knifetoast** [comment]
this is happening for me too. can someone explain what to do?

**Comment by qq1pvl** [comment]
same problem
