### ISSUE TITLE
[ISSUE]: Permission denied: 'samples_0003_t2.json'

### ISSUE THREAD

**Issue by Zaiayt** [w-okada/voice-changer#1070]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.15

### Operational System

Windows 10 pro

### GPU

none

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

rvc

### Issue Description

I'm trying to open the voice changer but for some reason it says  model_dis not found and when I added the folder into the files it says get_info ex: [Errno 13] Permission denied: 'samples_0003_t2.json'

### Application Screenshot

![soemthing](https://github.com/w-okada/voice-changer/assets/107722667/1cb316ad-8e6d-4726-b511-32419bea3717)

### Logs on console

C:\Users\Suruj Rudolph\Desktop\New folder\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /ddPn08/rvc-webui-models/resolve/main/embeddings/hubert_base.pt (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights/resolve/main/crepe/onnx/full.onnx (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /rinna/japanese-hubert-base/resolve/main/fairseq/model.pt (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights/resolve/main/crepe/onnx/tiny.onnx (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights/resolve/main/ddsp-svc30/nsf_hifigan_20221211/model.bin (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights/resolve/main/ddsp-svc30/nsf_hifigan_onnx_20221211/nsf_hifigan.onnx (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights/raw/main/ddsp-svc30/nsf_hifigan_20221211/config.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights/resolve/main/ddsp-svc30/embedder/hubert-soft-0d54a1f4.pt (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights_gpl/resolve/main/content-vec/contentvec-f.onnx (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights/resolve/main/rmvpe/rmvpe_20231006.pt (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/weights_gpl/resolve/main/rmvpe/rmvpe_20231006.onnx (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
    failed to download weight for rvc
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0003_t2.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0003_o2.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0003_d2.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'huggingface.co'. (_ssl.c:1007)")))
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-01-09 10:54:19] connet sid : jSqJsADB3Id0dNGZAAAB
[2024-01-09 10:54:19] connet sid : oLR8zpGKHjanALtgAAAD
[Voice Changer] get_info ex: [Errno 13] Permission denied: 'samples_0003_t2.json'
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 258, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt
[7024] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

**Comment by neurogreedy** [comment]
try again with connected vpn
