### ISSUE TITLE
[ISSUE]: Strange error when selecting any voice

### ISSUE THREAD

**Issue by Sensanko** [w-okada/voice-changer#1071]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b.zip

### Operational System

Windows 11

### GPU

GTX 1650

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

A strange error when selecting any voice, even a preset one.

### Application Screenshot

![Screenshot_27](https://github.com/w-okada/voice-changer/assets/156166181/358d65a2-b123-427b-b2ec-64e2f91bb7a0)

### Logs on console

MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
2024-01-10 13:16:47.2916924 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server... done 200
[2024-01-10 13:16:55] connet sid : 0ijIchHtk3W7z4j_AAAB
[2024-01-10 13:16:55] connet sid : scN9C6Z6Zyf89wHZAAAD
[Voice Changer] update configuration: modelSlotIndex 1704867418004
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] post_update_settings ex: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/rmvpe.onnx failed:Protobuf parsing failed.
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 337, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 345, in update_settings
  File "voice_changer\VoiceChangerV2.py", line 164, in update_settings
  File "voice_changer\RVC\RVCr2.py", line 88, in update_settings
  File "voice_changer\RVC\RVCr2.py", line 62, in initialize
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 42, in createPipeline
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 25, in getPitchExtractor
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 45, in loadPitchExtractor
  File "voice_changer\RVC\pitchExtractor\RMVPEOnnxPitchExtractor.py", line 28, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/rmvpe.onnx failed:Protobuf parsing failed.

**Comment by Sensanko** [comment]
And yet, I tried choosing not only the CPU but also the GPU, although I don’t think it matters.
CPU name: i5-10400f, if that matters

**Comment by TY-teo** [comment]
if u solved it，please tell me how to solve？

**Comment by Kuuko-fokkusugaru** [comment]
First try updating your version, the one from OP is older.
Then try reinstalling MS visual studio redist

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

https://huggingface.co/wok000/vcclient000/tree/main
