### ISSUE TITLE
[ISSUE]: Voice not converting

### ISSUE THREAD

**Issue by WrathOfMci** [w-okada/voice-changer#1084]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b.zip

### Operational System

Windows 11

### GPU

NIVIDA GeForce RTX 3060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

My voice won't conert to the Ai's

### Application Screenshot

![Uploading image.png…]()

### Logs on console

C:\Users\macke\Downloads\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server... done 200
[2024-01-15 23:30:04] connet sid : cUDX_El2wmLYEUN8AAAC
[2024-01-15 23:30:04] connet sid : GkGc5OATvNgRyI-kAAAD
[Voice Changer] update configuration: modelSlotIndex 1705379412000
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] update configuration: f0Detector crepe
[Voice Changer] update configuration: silentThreshold 0.00002
[Voice Changer] update configuration: silentThreshold 0.00003
[Voice Changer] update configuration: silentThreshold 0.00007
[Voice Changer] update configuration: silentThreshold 0.00011
[Voice Changer] update configuration: silentThreshold 0.00015
[Voice Changer] update configuration: silentThreshold 0.00022
[Voice Changer] update configuration: silentThreshold 0.00031
[Voice Changer] update configuration: silentThreshold 0.00042
[Voice Changer] update configuration: silentThreshold 0.00052
[Voice Changer] update configuration: silentThreshold 0.00064
[Voice Changer] update configuration: silentThreshold 0.00075
[Voice Changer] update configuration: silentThreshold 0.00084
[Voice Changer] update configuration: silentThreshold 0.00092
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: serverReadChunkSize 384
[Voice Changer] update configuration: crossFadeEndRate 3
[Voice Changer] update configuration: crossFadeEndRate 2
[Voice Changer] update configuration: crossFadeEndRate 1
[Voice Changer] update configuration: passThrough true

**Comment by lenore-puwawa** [comment]
`[Voice Changer] update configuration: passThrough true`
Please turn off the pass-through function.

**Comment by WrathOfMci** [comment]
> `[Voice Changer] update configuration: passThrough true` Please turn off the pass-through function.

Yea but when I do that how would I know if it's working or not. I'm not able to hear myself. I've tried recording my voice and it wasn't converted.

**Comment by lenore-puwawa** [comment]
![image](https://github.com/w-okada/voice-changer/assets/61484599/6f32e651-549d-4cfa-bfb4-96ac99a3efa4)
This is when the pass-through function is off.

![image](https://github.com/w-okada/voice-changer/assets/61484599/b0e94aa2-dfaf-4351-b44c-45bbc0fffd84)
This is when the pass-through function is on.

![image](https://github.com/w-okada/voice-changer/assets/61484599/4b364821-c902-45c2-8412-1e7b2fc65995)
If you want to hear the converted audio, please set the speakers you are using as Monitor.
Alternatively, change the Windows settings to listen to the virtual audio specified in Output.

**Comment by WrathOfMci** [comment]
> ![image](https://private-user-images.githubusercontent.com/61484599/299879190-6f32e651-549d-4cfa-bfb4-96ac99a3efa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDM5NTYsIm5iZiI6MTcwNjI0MzY1NiwicGF0aCI6Ii82MTQ4NDU5OS8yOTk4NzkxOTAtNmYzMmU2NTEtNTQ5ZC00Y2ZhLWJmYjQtOTZhYzk5YTNlZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA0MzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZGNhNjAyNTY3NjhiYWQ2NTJiOTlhNDFiMjNjZWExMWYzMmNmYWJmMmEyOGVhNzY0YmU5Y2Q0NzlmNzU3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9xRxH4KXE5S0hDBp_6uNGiynHtyshKzTVFC9i87CIA) This is when the pass-through function is off.
> 
> ![image](https://private-user-images.githubusercontent.com/61484599/299879277-b0e94aa2-dfaf-4351-b44c-45bbc0fffd84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDM5NTYsIm5iZiI6MTcwNjI0MzY1NiwicGF0aCI6Ii82MTQ4NDU5OS8yOTk4NzkyNzctYjBlOTRhYTItZGZhZi00MzUxLWI0NGMtNDViYmMwZmZmZDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA0MzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzE3OGEwZWYzNmQyMTc1MzI2NmVlN2Y1NjJhM2E2NTY0NWM0NjZhYzMwMWU5OGQ3ZWYzMTVhN2MxNWJkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Td9bUQgxcQvavj4VIct6qXlbFgIpw6FdBZ5gsoLco_I) This is when the pass-through function is on.
> 
> ![image](https://private-user-images.githubusercontent.com/61484599/299879511-4b364821-c902-45c2-8412-1e7b2fc65995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDM5NTYsIm5iZiI6MTcwNjI0MzY1NiwicGF0aCI6Ii82MTQ4NDU5OS8yOTk4Nzk1MTEtNGIzNjQ4MjEtYzkwMi00NWMyLTg0MTItMWU3YjJmYzY1OTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA0MzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODE2NDU3MGMzZGM0YWJjMGFhMGQyOTQ1ZjMzNzNkYWJiYmJiNGFiNGM4NDE1NDliZjhhNmRmNGNkMjFlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0vK4ik3Os7s46W9FLDRHzBMyIjGSiYTJQNliqUO6-w) If you want to hear the converted audio, please set the speakers you are using as Monitor. Alternatively, change the Windows settings to listen to the virtual audio specified in Output.

I disabled pass-through. I tried setting my headphones as my monitor and it didn't work. I can't hear my voice. I'm pretty sure I changed the windows setting.
![image](https://github.com/w-okada/voice-changer/assets/156729857/0d0a7168-c32b-466b-aa25-59fa7d596315)


C:\Users\macke\Downloads\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[VCClient] wait web server... done 200
[2024-01-25 23:35:18] connet sid : BI93u_MIouDdVIr9AAAB
[2024-01-25 23:35:18] connet sid : AOXo4l9Up21I1pgvAAAD
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: f0Detector rmvpe_onnx
[Voice Changer] update configuration: f0Detector crepe
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: modelSlotIndex 1706244490000
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] update configuration: modelSlotIndex 1706244491001
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] update configuration: modelSlotIndex 1706244492000
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.

**Comment by lenore-puwawa** [comment]
`[Voice Changer] exception! loading inferencer invalid load key, '\x08'.`
The sample model may be corrupted.
Please check the following steps.
1. Does it work with other sample models (Amitaro, etc.)
2. If you have a suitable RVC model on hand, try it
3. After removing VC Client, download again & run start_http.bat（This is because a sample model is downloaded when you start it for the first time.）

For reference, the file size of the sample model (Tsukuyomi-chan) I have is 54085 KB (52.8 MB (55,382,411 byte)).
It should be stored in "tsukuyomi_v2_40k_e100_simple.onnx" in "MMVCServerSIO\model_dir\0".
If the file size is smaller than this, the sample model may be corrupted.
