### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by botngamer** [w-okada/voice-changer#1101]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b

### Operational System

Windows 11

### GPU

RTX3060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

When starting the program, the program tries to load the index file, but cannot find it.

Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found

The program starts without a problem after that, but when I try to enter an input method, this error code pops up.

TypeError: (0 , Kz.removeDB) is not a function
at http://127.0.0.1:18888/index.js:2:3264601
at m (http://127.0.0.1:18888/index.js:2:1507737)
at Generator.<anonymous> (http://127.0.0.1:18888/index.js:2:1509083)
at Generator.next (http://127.0.0.1:18888/index.js:2:1508166)
at e (http://127.0.0.1:18888/index.js:2:1514937)
at c (http://127.0.0.1:18888/index.js:2:1515140)

I tried several ways to solve the problem, but nothing worked.

### Application Screenshot

![Captura de pantalla 2024-01-28 014306](https://github.com/w-okada/voice-changer/assets/157947629/8df638c8-c13e-4cff-a45f-243a94b6cf52)
![Captura de pantalla 2024-01-28 014337](https://github.com/w-okada/voice-changer/assets/157947629/c71b0dad-7672-47bf-91cd-ac61210e58fc)

### Logs on console

Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found

**Comment by YoiRida** [comment]
UP

I have same problem.
anyone can help !!?
