### ISSUE TITLE
[ISSUE]: Can't Hear Anything i even uninstalled reset twice and still nothing

### ISSUE THREAD

**Issue by mellogonegoofy** [w-okada/voice-changer#1105]
### Voice Changer Version

v.1.5.3.17b

### Operational System

Windows 11

### GPU

RTX 3060 TI

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

IDK

### Logs on console

C:\Users\akila\Downloads\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server... done 200
[2024-02-06 18:29:17] connet sid : 2KEr_WJehYfpwxiBAAAB
[2024-02-06 18:29:17] connet sid : hCvsrxzt-DkfWKZPAAAD
[Voice Changer] update configuration: gpu 0
[Voice Changer] update configuration: f0Detector crepe
[Voice Changer] update configuration: modelSlotIndex 1707262183000
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[2024-02-06 18:31:09] connet sid : KIXI1m7SbPoCFWXLAAAF
[2024-02-06 18:31:09] connet sid : qlRNhqHNzwWqJJkgAAAH
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 258, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt

**Comment by covalspace** [comment]
Same issue on M1

**Comment by KRJDEVELOPER** [comment]
me too
