### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by gentoocat** [w-okada/voice-changer#1123]
### Voice Changer Version

https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md

### Operational System

Artix Linux

### GPU

RTX 3060 Ti

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Trying to launch voice-changer on artix linux, when i select model changer crashes. I mean this:

![screenshot](https://github.com/w-okada/voice-changer/assets/76536021/f1fc3379-9bde-4312-9cdf-8639ff774997)

here is logs.

### Logs on console

[2024-02-19 00:01:19] connet sid : BJ4GKYuWe7ygS1owAAAF
[2024-02-19 00:01:19] connet sid : 4bO7UyR3SJ28lG-hAAAH
[Voice Changer] update configuration: modelSlotIndex 1708290087000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] post_update_settings ex: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Traceback (most recent call last):
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 333, in update_settings
    self.generateVoiceChanger(newVal)
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 250, in generateVoiceChanger
    from voice_changer.RVC.RVCr2 import RVCr2
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/RVCr2.py", line 11, in <module>
    from voice_changer.RVC.embedder.EmbedderManager import EmbedderManager
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 5, in <module>
    from voice_changer.RVC.embedder.FairseqContentvec import FairseqContentvec
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqContentvec.py", line 3, in <module>
    from voice_changer.RVC.embedder.FairseqHubert import FairseqHubert
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqHubert.py", line 4, in <module>
    from fairseq import checkpoint_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
[2024-02-19 00:01:42] connet sid : -UiADK4Zpvog-jxNAAAJ
[2024-02-19 00:01:42] connet sid : YhuWFTc9t9s5gE0dAAAL
[Voice Changer] update configuration: enableServerAudio 1
[Voice Changer] update configuration: serverInputDeviceId 4
[Voice Changer] update configuration: serverInputDeviceId 5
[Voice Changer] update configuration: serverInputDeviceId 4
[Voice Changer] update configuration: serverOutputDeviceId 10
[Voice Changer] update configuration: serverMonitorDeviceId 10
[Voice Changer] update configuration: modelSlotIndex 1708290153000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] post_update_settings ex: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Traceback (most recent call last):
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 333, in update_settings
    self.generateVoiceChanger(newVal)
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 250, in generateVoiceChanger
    from voice_changer.RVC.RVCr2 import RVCr2
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/RVCr2.py", line 11, in <module>
    from voice_changer.RVC.embedder.EmbedderManager import EmbedderManager
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 5, in <module>
    from voice_changer.RVC.embedder.FairseqContentvec import FairseqContentvec
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqContentvec.py", line 3, in <module>
    from voice_changer.RVC.embedder.FairseqHubert import FairseqHubert
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqHubert.py", line 4, in <module>
    from fairseq import checkpoint_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
[2024-02-19 00:02:41] connet sid : RdocapfjOssbO4ffAAAN
[2024-02-19 00:02:41] connet sid : XVGIGnkytXJR0sO3AAAP
[Voice Changer] update configuration: f0Detector dio
[Voice Changer] update configuration: modelSlotIndex 1708290171001
[Voice Changer] model slot is changed -1 -> 1
................RVC
[Voice Changer] post_update_settings ex: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Traceback (most recent call last):
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 333, in update_settings
    self.generateVoiceChanger(newVal)
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 250, in generateVoiceChanger
    from voice_changer.RVC.RVCr2 import RVCr2
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/RVCr2.py", line 11, in <module>
    from voice_changer.RVC.embedder.EmbedderManager import EmbedderManager
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 5, in <module>
    from voice_changer.RVC.embedder.FairseqContentvec import FairseqContentvec
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqContentvec.py", line 3, in <module>
    from voice_changer.RVC.embedder.FairseqHubert import FairseqHubert
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqHubert.py", line 4, in <module>
    from fairseq import checkpoint_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
[2024-02-19 00:02:54] connet sid : BvKvwQaM1vJ7G_70AAAR
[2024-02-19 00:02:54] connet sid : s1SkU7v0w_qvBDf0AAAT
[Voice Changer] update configuration: serverAudioStated 1
[Voice Changer] update configuration: modelSlotIndex 1708290182001
[Voice Changer] model slot is changed -1 -> 1
................RVC
[Voice Changer] post_update_settings ex: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Traceback (most recent call last):
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 333, in update_settings
    self.generateVoiceChanger(newVal)
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/VoiceChangerManager.py", line 250, in generateVoiceChanger
    from voice_changer.RVC.RVCr2 import RVCr2
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/RVCr2.py", line 11, in <module>
    from voice_changer.RVC.embedder.EmbedderManager import EmbedderManager
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 5, in <module>
    from voice_changer.RVC.embedder.FairseqContentvec import FairseqContentvec
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqContentvec.py", line 3, in <module>
    from voice_changer.RVC.embedder.FairseqHubert import FairseqHubert
  File "/run/media/gentoocat/f6c520a9-9a9e-479b-a681-82072c5fcab3/voice-changer/server/voice_changer/RVC/embedder/FairseqHubert.py", line 4, in <module>
    from fairseq import checkpoint_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/gentoocat/.local/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=4, name='HD-Audio Generic: ALC892 Analog (hw:1,0)', hostAPI='ALSA', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=10, name='default', hostAPI='ALSA', maxInputChannels=32, maxOutputChannels=32, default_samplerate=44100.0, available_samplerates=[]) None
[Voice Changer] ex: get_processing_sampling_rate 'NoneType' object has no attribute 'get_processing_sampling_rate'
[vcclient.log](https://github.com/w-okada/voice-changer/files/14324461/vcclient.log)

**Comment by GatienDoesStuff** [comment]
You're using python 3.11 which fairseq is currently broken on. Unless patch fairseq to fix this, or use a previous python version
