### ISSUE TITLE
[ISSUE]: It seems like not working, I only can hear my normal voice when i click passthru

### ISSUE THREAD

**Issue by Joekun3** [w-okada/voice-changer#1152]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a

### Operational System

Windows 11

### GPU

NVIDIA GeForce GTX 1650 with Max-Q Design

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Everything seems not working when i start the volume data still 0 even though I already talk. I only can hear my normal voice when I click passthru, other than that I can't hear anything. I tried to record as per tutorial but still, the wav file has nothing, theres no voice or any sounds. Help me, please

### Logs on console

C:\Users\matju\Downloads\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 44, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 48, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[VCClient] wait web server... done 200
[2024-03-16 21:24:19] connet sid : UIyJKv8Mxqj2XFvDAAAC
[2024-03-16 21:24:19] connet sid : Pb3u33mcz8Prl9b7AAAD

**Comment by IsabelaBardelli** [comment]
I'm facing same issue (I guess)

GPU: NVIDIA GeForce RTX 3060 Laptop

[x] I've tried to Clear Settings
[x] Sample/Default Models are working
[x] I've tried to change the Chunk Size
[x] GUI was successfully launched
[x] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
[x] I've tried to extract to another folder (or re-extract) the .zip file

My logs: 
[voice_changer_log.txt](https://github.com/w-okada/voice-changer/files/14627541/voice_changer_log.txt)

I'm not expert or anything but it seems 
a) .pth files aren't being downloaded in samples
b) pipeline isn't being initialized.


I will story tell an RPG and would love this to make different voices in good quality. =(

**Comment by wellsilver** [comment]
Same issue, exact same error

**Comment by type4101** [comment]
Identical issue for me too.
 Desktop, Windows 11, NVIDIA 4070 ti.

**Comment by Josh-gif953** [comment]
Same here issues. How do we fix this so I can hear the converted voice. I just hear my normal voice when I press start. Even when I put it on passthru.
