### ISSUE TITLE
[ISSUE]: Can't merge any 48k models, causes crash

### ISSUE THREAD

**Issue by uwuhazelnut** [w-okada/voice-changer#1176]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a.zip

### Operational System

Windows 10

### GPU

RTX 3070

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Whenever I try to merge any 48k models (pyTorchRVCv2,48000,768), The application crashes. Any other types of models work just fine without any issues whatsoever. I've tried using different kinds of 48k models as well and it seems to happen with any.

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/85243886/d5e70b41-bbc1-414e-bf76-d4471b193dc5)

### Logs on console

```
merge start.
merge done. write metadata.
[Voice Changer] post_merge_models ex: 'info'
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 113, in post_merge_models
  File "voice_changer\VoiceChangerManager.py", line 384, in merge_models
  File "voice_changer\RVC\RVCModelMerger.py", line 13, in merge_models
  File "voice_changer\RVC\modelMerger\MergeModel.py", line 72, in merge_model
KeyError: 'info'
```

**Comment by Darienxccs4** [comment]
I am having the same issue, i am using CPU, and I noticed this happens when I try to merge voices trained on the Replay.io and weights.gg voice models
