### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by s1ducs** [w-okada/voice-changer#1222]
### Voice Changer Version

no

### Operational System

Windows 10

### GPU

3060TI

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RCV

### Issue Description

[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

### Logs on console

[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> Beatrice-JVS
................Beatrice
[Voice Changer] [Beatrice] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer] [Beatrice] Initializing...
[Voice Changer] [Beatrice] Initializing... done
[Voice Changer][Beatrice]: update_settings gpu:0
[Voice Changer][Beatrice]: update_settings serverReadChunkSize:80
[Voice Changer][Beatrice]: update_settings extraConvertSize:65536
[Voice Changer][Beatrice]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][Beatrice]: update_settings silentThreshold:0
[Voice Changer][Beatrice]: update_settings enableServerAudio:0
[Voice Changer][Beatrice]: update_settings serverInputAudioGain:10
[Voice Changer][Beatrice]: update_settings serverOutputAudioGain:10
[Voice Changer][Beatrice]: update_settings serverInputDeviceId:1
[Voice Changer][Beatrice]: update_settings serverOutputDeviceId:8
[Voice Changer][Beatrice]: update_settings modelSlotIndex:1716915492000Beatrice-JVS
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-05-29 00:00:01] connet sid : Dh8H2vT9FowmtCi1AAAB
[2024-05-29 00:00:01] connet sid : kdz75uKtTWpSeMJTAAAD
[Voice Changer] update configuration: modelSlotIndex 1716915603005
[Voice Changer] model slot is changed Beatrice-JVS -> 5
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
Exception ignored in: <function Beatrice.__del__ at 0x000002260B442170>
Traceback (most recent call last):
  File "voice_changer\Beatrice\Beatrice.py", line 189, in __del__
AttributeError: pipeline
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 44, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 48, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings serverReadChunkSize:80
[Voice Changer][RVC]: update_settings extraConvertSize:65536
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings silentThreshold:0
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputAudioGain:10
[Voice Changer][RVC]: update_settings serverOutputAudioGain:10
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverOutputDeviceId:8
[Voice Changer][RVC]: update_settings modelSlotIndex:1716915603005
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

**Comment by KuukoShan** [comment]
Extract to a new folder with a new name then start the software with the start.bat file. Don't change any of the default settings besides the input and outputs so you can rest if it works. Select the first voice on the list, not Beatrice. Let's see if it works in that way before changing something else.

You didn't explain what the issue is at all but I can see on the logs that it successfully launched and you were able to change settings. So I guess at some point changing a setting something broke.

**Comment by s1ducs** [comment]
It didn't help



E:\voice chenger\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2024-05-29 10:21:34.3290758 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-05-29 10:21:34.3331144 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 44, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 48, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings serverReadChunkSize:80
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings silentThreshold:0
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputAudioGain:10
[Voice Changer][RVC]: update_settings serverOutputAudioGain:10
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverOutputDeviceId:8
[Voice Changer][RVC]: update_settings modelSlotIndex:1716952848000
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-05-29 10:21:47] connet sid : iR4hHXnFKaeLTK_5AAAC
[2024-05-29 10:21:47] connet sid : x8gb6xXaYJ5n9w72AAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

**Comment by s1ducs** [comment]
> Extract to a new folder with a new name then start the software with the start.bat file. Don't change any of the default settings besides the input and outputs so you can rest if it works. Select the first voice on the list, not Beatrice. Let's see if it works in that way before changing something else.
> 
> You didn't explain what the issue is at all but I can see on the logs that it successfully launched and you were able to change settings. So I guess at some point changing a setting something broke.

It didn't help



E:\voice chenger\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2024-05-29 10:21:34.3290758 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-05-29 10:21:34.3331144 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 44, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 48, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings serverReadChunkSize:80
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings silentThreshold:0
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputAudioGain:10
[Voice Changer][RVC]: update_settings serverOutputAudioGain:10
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverOutputDeviceId:8
[Voice Changer][RVC]: update_settings modelSlotIndex:1716952848000
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-05-29 10:21:47] connet sid : iR4hHXnFKaeLTK_5AAAC
[2024-05-29 10:21:47] connet sid : x8gb6xXaYJ5n9w72AAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

**Comment by KuukoShan** [comment]
Try everything again but this time don't switch the voice model. I can see in the logs that you switched model and then some errors started to happen. Try to see if it works fine with just the default settings. Just change the input and output in case of them being wrong and not being able to listen your own voice.

**Comment by deiteris** [comment]
> onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

Remove `pretrain` folder, your download on startup did not finish correctly.
