### ISSUE TITLE
[ISSUE]: Intermittently disconnecting my PC's internet (ethernet) briefly during and after use.

### ISSUE THREAD

**Issue by RodzKing** [w-okada/voice-changer#1223]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a.zip

### Operational System

Windows 10

### GPU

NVIDIA GeForce GTX 1650

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC, RVC

### Issue Description

My internet cable is connected to the router. The Wi-Fi of the router is working well. But when I use the voice-changer, it disconnects intermittently (disconnecting then reconnects again.) The voice changer works fine for a couple of minutes then its starts to disconnect my internet in intervals. I don't know how but when "connet sid" appears, it starts to affect my PC's internet.

"connet sid" also appears multiple times under a minute. Most of my logs are filled with these.

The effects linger on even after force closing the client.

### Logs on console

D:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0004_t.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000215A3642800>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0004_o.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000215A3641C90>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0004_d.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000215A3643CA0>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server...10 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 4
................RVC
[VCClient] wait web server...20 http://127.0.0.1:18888/
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[VCClient] wait web server...30 http://127.0.0.1:18888/
2024-05-29 19:15:45.8830555 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-05-29 19:15:46.2788157 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[VCClient] wait web server...40 http://127.0.0.1:18888/
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF2015_Flat_nprobe_1_yanderev2_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000001D469530BB0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001D46C640A60>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x000001D46C640A90>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[VCClient] wait web server...50 http://127.0.0.1:18888/
[Voice Changer][RVC]: update_settings modelSlotIndex:1716979886004
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-05-29 19:16:19] connet sid : oLN-WDbWDOg1QIPyAAAC
[2024-05-29 19:16:19] connet sid : gsfY7JwuJxafRwtoAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: serverReadChunkSize 320
[Voice Changer][RVC]: update_settings serverReadChunkSize:320
[2024-05-29 19:18:21] connet sid : oKUfU2PdI9OlaGjgAAAI
[2024-05-29 19:18:21] connet sid : Fhb6VelfOch0dtK6AAAJ
[2024-05-29 19:18:31] connet sid : LSg9a_Ze5jMjwJmEAAAM
[2024-05-29 19:18:31] connet sid : UZFdIYBDmwhHls3MAAAN
[2024-05-29 19:18:51] connet sid : QEqOEIb9BpmmKNd8AAAS
[2024-05-29 19:19:09] connet sid : Sxw1ZO-TVG0-vhMzAAAV
[2024-05-29 19:19:11] connet sid : pQP7I4CC9-hsyk0bAAAW
[2024-05-29 19:19:29] connet sid : ZTnzwZDWW0BKhBCKAAAZ
[2024-05-29 19:19:29] connet sid : zAy1T67fcpmNHDnJAAAa
[2024-05-29 19:19:47] connet sid : I073FANfWsfc0fbLAAAd
[2024-05-29 19:19:47] connet sid : SxIhfmpvvPj9feieAAAe
[2024-05-29 19:20:06] connet sid : YiiesPL3eXjvAtUEAAAh
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "engineio\async_drivers\asgi.py", line 58, in __call__
  File "socketio\asyncio_server.py", line 398, in handle_request
  File "engineio\asyncio_server.py", line 268, in handle_request
  File "engineio\server.py", line 637, in _get_socket
KeyError: 'Session is disconnected'
Invalid session JWhUsY8JCm0ThhkqAAAg (further occurrences of this error will be logged with level INFO)
[2024-05-29 19:20:06] connet sid : 2lLkM-AZy6zEguHCAAAk
[2024-05-29 19:20:06] connet sid : fJ1q0dbiuEAykyj1AAAl
[2024-05-29 19:20:36] connet sid : YS_Gphuw_BKMgn8sAAAn
[2024-05-29 19:20:37] connet sid : Odq-op4Vx7K196THAAAp
[2024-05-29 19:21:11] connet sid : -Ay2qxx2cgRqGYsyAAAr
[2024-05-29 19:21:24] connet sid : lxDGt5WqIgq2vpNNAAAu
[2024-05-29 19:21:31] connet sid : Q-BjS4-Ief5N5sRJAAAw
[2024-05-29 19:21:56] connet sid : qTfiOA5-1WVEY8C0AAA0
[2024-05-29 19:22:00] connet sid : pUWI0S5xwrICugHpAAA2
[2024-05-29 19:22:04] connet sid : 9bXzSHsi9Lr9MbKpAAA4
[2024-05-29 19:22:12] connet sid : 7vs3XW_2MwIQO3TOAAA6
[2024-05-29 19:22:13] connet sid : uRCph9XODobDUtVcAAA8
[2024-05-29 19:22:35] connet sid : o7sgLGVie9t7Ye67AAA-
[2024-05-29 19:22:35] connet sid : yVETelV4bgdAO8PdAABA
[2024-05-29 19:22:45] connet sid : ZJ9mU1iNu-SrYOTsAABC
[2024-05-29 19:22:46] connet sid : j7pTGKIUCeD_No4uAABE
[2024-05-29 19:22:56] connet sid : RvJFsITs8vV_aDbEAABG
[2024-05-29 19:22:57] connet sid : vLT7d1PgFbD0peQAAABI
[2024-05-29 19:23:28] connet sid : 6aUBaIfy15RsdLfFAABL
[2024-05-29 19:23:28] connet sid : _uZQlnUJhBIImquxAABM
[2024-05-29 19:23:30] connet sid : UDMJE7-NFT4V3Z_ZAABO
[2024-05-29 19:23:31] connet sid : YrP5mJPEQ5X4dt9kAABQ
[2024-05-29 19:23:40] connet sid : LTCmrOw-8QBMfxfBAABT
[2024-05-29 19:23:40] connet sid : CQX2g5Xu1_PBK308AABU
[2024-05-29 19:23:47] connet sid : DzLVROedYMewUqeqAABX
[2024-05-29 19:23:47] connet sid : lW_SU5ZGTLAUAYa6AABY
[2024-05-29 19:23:52] connet sid : G2NY669Ijkokw3P9AABb
[2024-05-29 19:23:52] connet sid : m-xzk0cCbQD6pmckAABc
[2024-05-29 19:23:54] connet sid : H0kGChzRvPIbneiPAABe
[2024-05-29 19:23:55] connet sid : P7d4TT-cTkngG1AeAABg
[2024-05-29 19:24:30] connet sid : ArDsseg7nG7MmXpwAABi
[2024-05-29 19:24:31] connet sid : EK_14v6UuxCfz7s2AABk

**Comment by KuukoShan** [comment]
The connect sid messages it's something that I only get if I use a very high chunk. May be due your gpu limitations but try to set a way lower chunk size and smaller extra even if it's for the sake of testing.
I am not sure why your internet goes away though but it seems like it may be saturating it in some way.
I guess trying to update your ethernet and other motherboard drivers won't hurt.

**Comment by RodzKing** [comment]
The situation got worse. After starting the program, GUI load normally, even after pressing the start button the program freezes but the GUI is still functioning normally like showing windows or drop list, but it won't show up to the console or take any effect.

I deleted it then I downloaded another version v.1.5.3.17b and extract and put them on the same disk drive but won't load up. It stuck on this log even after 10 minutes:

D:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json

I have created another drive and extract the program (v.1.5.3.18a) there and start fresh. For now, it seems working fine. The "connet sid" doesn't appear every couple second.
