### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'modelSlots')

### ISSUE THREAD

**Issue by vixlaz** [w-okada/voice-changer#1233]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a.zip

### Operational System

Windows 11

### GPU

GeForce RTX 4080

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

i7-13700KF
32gb ram

### Application Screenshot

![imagem_2024-06-08_231229067](https://github.com/w-okada/voice-changer/assets/130535961/1d9df06e-e848-4341-a9d9-4621a61d82a7)
![imagem_2024-06-08_231244751](https://github.com/w-okada/voice-changer/assets/130535961/8c3430d3-324c-4f2f-bcc9-f81d8b6bd5e6)
![imagem_2024-06-08_231301494](https://github.com/w-okada/voice-changer/assets/130535961/91cb6e04-dd5f-4007-838f-3d77306b141f)

### Logs on console

index.js:2 AUDIO_CONTEXT null
index.js:2 AUDIO_CONTEXT null
index.js:2 initializedRef.current false
index.js:2 [voiceChangerClient] is not ready for set audio output.
setAudioOutputElementId @ index.js:2
index.js:2 initializedRef.current false
index.js:2 [voiceChangerClient] is not ready for set audio output.
setAudioMonitorElementId @ index.js:2
index.js:2 setupkey undefined
index.js:2 change voice  Object
index.js:2 [useWebInfo] clientState is not initialized yet
(anonymous) @ index.js:2
index.js:2 AUDIO_CONTEXT null
index.js:2 AUDIO_CONTEXT null
index.js:2 deleted input device: 
index.js:2 added input device: default,communications,95d54ae31584d7dffaea8846c17ea1cd0f2230adfc34805e3bd6af759ca50ad9,3a447371e89f893119844b4e246dc20cbd0ecfdd10b05e0b221c96e2b07f40d9,e9bdf742efa13d65518de30e59861150cc7c8d3c67536f46b591bf3a37c5d331,a434fc1528011427224117e77c371baba146413f2556a003063dc9365258fb20,29b84c15cf22c4b3cbac1f3f698b897629d07cbed427be50826410004d5db367,none,file,screen
index.js:2 deleted output device: 
index.js:2 added output device: default,communications,af796d4a61930da0adce239a1b62cc846d95050c679ca069a69d88377c0acb84,4f158c6451d1f598c4a81a57b6018a6c1771976f27024ced663616e338142a05,4c6051393cf2cce50e1556960fa18b30e25eec05764a5061bdd955b7ddb66820,51bbca20a2c488e0df13c7d646d49c914962707d7e8baecc82db8de21cf03fef,7c40c9581f680074e8ba0dd480d7742b8e9d8ff4bc922dfd317510393581b7e1,b6d619f92406941192cc5e21d7380b83db0aae2012167927f80d7c42075fa713,none
index.js:2 Sample rate: default(48000)
index.js:2 AudioContext
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 AUDIO_CONTEXT AudioContext
 [AudioWorkletProcessor] created.
index.js:2 [worklet_node][voice-changer-worklet-processor] created.
index.js:2 audio out: AudioContext
63038e23-0943-41bf-b40f-996e56998f56:1 [AudioWorkletProcessor] created.
index.js:2 [worklet_node][voice-changer-worklet-processor] created.
index.js:2 [SIO] connect to 
index.js:2 [SIO] CmQsJoUVCmwwihVUAAAD
index.js:2 [SIO] connect to 
index.js:2 [SIO] 8Y_abtkTuZZZZqh1AAAC
index.js:2 [useClient] client initialized
index.js:2 change voice  Object
index.js:2 [useWebInfo] this is not web edition
(anonymous) @ index.js:2
 [worklet] worklet configured Object
63038e23-0943-41bf-b40f-996e56998f56:1 [worklet] worklet configured Object
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 initializedRef.current true
index.js:2 initializedRef.current true
index.js:2 deleted input device: 
index.js:2 added input device: default,communications,95d54ae31584d7dffaea8846c17ea1cd0f2230adfc34805e3bd6af759ca50ad9,3a447371e89f893119844b4e246dc20cbd0ecfdd10b05e0b221c96e2b07f40d9,e9bdf742efa13d65518de30e59861150cc7c8d3c67536f46b591bf3a37c5d331,a434fc1528011427224117e77c371baba146413f2556a003063dc9365258fb20,29b84c15cf22c4b3cbac1f3f698b897629d07cbed427be50826410004d5db367,none,file,screen
index.js:2 deleted output device: 
index.js:2 added output device: default,communications,af796d4a61930da0adce239a1b62cc846d95050c679ca069a69d88377c0acb84,4f158c6451d1f598c4a81a57b6018a6c1771976f27024ced663616e338142a05,4c6051393cf2cce50e1556960fa18b30e25eec05764a5061bdd955b7ddb66820,51bbca20a2c488e0df13c7d646d49c914962707d7e8baecc82db8de21cf03fef,7c40c9581f680074e8ba0dd480d7742b8e9d8ff4bc922dfd317510393581b7e1,b6d619f92406941192cc5e21d7380b83db0aae2012167927f80d7c42075fa713,none
index.js:2 RESPONSE null
index.js:2 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'modelSlots')
    at i (index.js:2:1277059)
    at Object.mergeModel (index.js:2:1278656)
DevTools failed to load source map: Could not load content for http://127.0.0.1:18888/worker-v1.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error

**Comment by orangesandblast** [comment]
I was going to make a new issue for this, but the in-GUI error message I get is the same as this so we may have the same problem.

I'm using Linux with AMD following this tutorial: [Voice Changer for AMD GPUs under Linux](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_anaconda_amd_rocm.md)
My GPU is Radeon RX 6700 XT.

When I try to load one of the sample models I get the following error screen. Once I do so the value for the selected model (which crashed) is saved into my stored_setting.json file and I have to delete it to be able to start the server again after I close this one.
![pic](https://github.com/w-okada/voice-changer/assets/168879684/96a7fc06-ab58-43be-8b8e-8af1eeb9bcf3)

**Comment by orangesandblast** [comment]
Ran a git bisect. It seems this is a regression, and [this commit](https://github.com/w-okada/voice-changer/commit/0b954131b4de0d8a196866ca5c12bf0182113302) is the cause:

    0b954131b4de0d8a196866ca5c12bf0182113302 is the first bad commit
    commit 0b954131b4de0d8a196866ca5c12bf0182113302
    Author: Tobias <tobiasgolz1@gmail.com>
    Date:   Sun Jan 21 14:02:35 2024 +0100
    
        Bugfix FCPE
    
     server/voice_changer/RVC/pitchExtractor/PitchExtractorManager.py | 1 +
     1 file changed, 1 insertion(+)

**Comment by siiiiro** [comment]
is there no other fix to this issue? Im having the exact same issue.

**Comment by Kuuko-fokkusugaru** [comment]
> is there no other fix to this issue? Im having the exact same issue when trying to merge 2 RVC models together.

Try v2 to merge them.

**Comment by siiiiro** [comment]
> > is there no other fix to this issue? Im having the exact same issue when trying to merge 2 RVC models together.
> 
> Try v2 to merge them.

it is using v2 unfortunately

**Comment by Kuuko-fokkusugaru** [comment]
> > > is there no other fix to this issue? Im having the exact same issue when trying to merge 2 RVC models together.
> > 
> > 
> > Try v2 to merge them.
> 
> i am already using v2 unfortunately

Then try v1 🙃
If you get the issue on both, then I don't know. The software requires some dependencies but so far I have only found that mvs c++ redist is a must. There are surely more as not everyone can even run the software after installing that one but I never managed for the creator to give some advice about what's exactly needed. I personally never installed anything and it works out of the box but that's probably because whatever dependency was already installed from any other software since those are quite basic ones for many software and even games.
