### ISSUE TITLE
[ISSUE]: cannot load any model

### ISSUE THREAD

**Issue by Chocobonii** [w-okada/voice-changer#1253]
### Voice Changer Version

latest

### Operational System

linux arch

### GPU

amd radeon

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

no model actually loads, I only get an error on the terminal and it does nothing

### Logs on console

[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec Not implemented
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cpu
Traceback (most recent call last):
  File "/home/bonii/WOkada/.old/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 44, in loadEmbedder
    return OnnxContentvec().loadModel(file, dev)
  File "/home/bonii/WOkada/.old/voice-changer/server/voice_changer/RVC/embedder/OnnxContentvec.py", line 8, in loadModel
    raise Exception("Not implemented")
Exception: Not implemented

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bonii/WOkada/.old/voice-changer/server/voice_changer/RVC/pipeline/PipelineGenerator.py", line 30, in createPipeline
    embedder = EmbedderManager.getEmbedder(
  File "/home/bonii/WOkada/.old/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 25, in getEmbedder
    cls.currentEmbedder = cls.loadEmbedder(embederType, isHalf, dev)
  File "/home/bonii/WOkada/.old/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 48, in loadEmbedder
    return FairseqHubert().loadModel(file, dev, isHalf)
  File "/home/bonii/WOkada/.old/voice-changer/server/voice_changer/RVC/embedder/FairseqHubert.py", line 11, in loadModel
    models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/bonii/.conda/envs/vcclient-dev/lib/python3.10/site-packages/fairseq/checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/bonii/.conda/envs/vcclient-dev/lib/python3.10/site-packages/fairseq/checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "/home/bonii/.conda/envs/vcclient-dev/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/bonii/.conda/envs/vcclient-dev/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer][RVC]: update_settings modelSlotIndex:1718839070001
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.

**Comment by raith7** [comment]
got a similar issue on mac
