### ISSUE TITLE
[ISSUE]: everything starts but 

### ISSUE THREAD

**Issue by raith7** [w-okada/voice-changer#1268]
### Voice Changer Version

MMVServerSIO_mac_onnxcpu_nocuda_v.1.5.3.17b.zip

### Operational System

MacOS sonoma 14.5

### GPU

none

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

everything seems to work fine but my voice is not getting changed, settings like gain work but the voice changer itself is not working, i also tried an older version but that one did not seem to work either.
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
infinitely repeats on console

### Application Screenshot

<img width="752" alt="Screenshot 2024-07-08 at 19 44 56" src="https://github.com/w-okada/voice-changer/assets/175038870/63b8f1c9-9c25-42ce-ad9c-1fd5153fc149">

### Logs on console

/Users/raith/Documents/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.17b/startHttp.command ; exit;
    Booting PHASE :__main__
    PYTHON:3.10.9 (main, Jan 15 2023, 23:00:56) [Clang 14.0.0 (clang-1400.0.29.202)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- -- 
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/
2024-07-08 19:31:42.953 voice-changer-native-client[2798:71958] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory mps
Traceback (most recent call last):
  File "voice_changer/RVC/embedder/EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer/RVC/embedder/OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer/RVC/pipeline/PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer/RVC/embedder/EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer/RVC/embedder/EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer/RVC/embedder/FairseqHubert.py", line 11, in loadModel
  File "fairseq/checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq/checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings serverReadChunkSize:40
[Voice Changer][RVC]: update_settings f0Detector:crepe
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverOutputDeviceId:2
[Voice Changer][RVC]: update_settings serverMonitorDeviceId:-1
[Voice Changer][RVC]: update_settings serverAudioSampleRate:32000
[Voice Changer][RVC]: update_settings modelSlotIndex:1720456107000
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
mac model_dir: /Users/raith/Documents/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.17b/model_dir
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-07-08 19:31:50] connet sid : CRXXTac0m-APk8DcAAAC
[2024-07-08 19:31:50] connet sid : 2ZMMh2bfsIfVH-c1AAAD
[Voice Changer] update configuration: modelSlotIndex 1720459916001
[Voice Changer] model slot is changed 0 -> 1
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory mps
Traceback (most recent call last):
  File "voice_changer/RVC/embedder/EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer/RVC/embedder/OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer/RVC/pipeline/PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer/RVC/embedder/EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer/RVC/embedder/EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer/RVC/embedder/FairseqHubert.py", line 11, in loadModel
  File "fairseq/checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq/checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings serverReadChunkSize:40
[Voice Changer][RVC]: update_settings f0Detector:crepe
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverOutputDeviceId:2
[Voice Changer][RVC]: update_settings serverMonitorDeviceId:-1
[Voice Changer][RVC]: update_settings serverAudioSampleRate:32000
[Voice Changer][RVC]: update_settings modelSlotIndex:1720459916001
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

**Comment by w-okada** [comment]
Could you try version 2?

https://huggingface.co/wok000/vcclient000/resolve/main/vcclient_mac_2.0.40-alpha.zip?download=true
