### ISSUE TITLE
[ISSUE for v2.0.47-alpha]: 

### ISSUE THREAD

**Issue by slnit** [w-okada/voice-changer#1293]
### Voice Changer Version

vcclient_win_cuda_2.0.45-alpha

### Operational System

Windows 10

### GPU

nvidia rtx 4060

### CUDA Version

supports CUDA versions 11.8 to 12.2

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

RVC

### Issue Description

the applications doesn't start

### Application Screenshot

![image](https://github.com/user-attachments/assets/31ce6728-2640-4fca-9d01-d787e22a7133)

### Logs on console

Traceback (most recent call last):
  File "vcclient_dev\main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\client_launcher\client_launcher.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\const.py", line 17, in <module>
  File "vcclient_dev\const.py", line 12, in get_version
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\IA\\vcclient_win_cuda_2.0.47-alpha\\dist\\main\\_internal\\vcclient_dev\\version.txt'
[1624] Failed to execute script 'main' due to unhandled exception!

**Comment by Kuuko-fokkusugaru** [comment]
Did you start it with start_http.bat?
Did you try to decompress again to a new folder?

**Comment by Kuuko-fokkusugaru** [comment]
You mention version vcclient_win_cuda_2.0.45-alpha but your log shows vcclient_win_cuda_2.0.47-alpha??

**Comment by Rakkyotan** [comment]
I also had the same situation.
The last "fbgemm.dll" file was in that location.

---
C:\RVC2047>start_http

C:\RVC2047>main.exe cui --https false
Traceback (most recent call last):
  File "vcclient_dev\main.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\initializer.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\sample_manager\sample_manager.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\slot_manager\slot_manager.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\slot_manager\model_importer\model_importer.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\slot_manager\model_importer\rvc_model_estimator\rvc_model_estimator.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "torch\__init__.py", line 148, in <module>
OSError: [WinError 126] 指定されたモジュールが見つかりません。 Error loading "C:\RVC2047\_internal\torch\lib\fbgemm.dll" or one of its dependencies.
[25320] Failed to execute script 'main' due to unhandled exception!

**Comment by slnit** [comment]
> Did you start it with start_http.bat? Did you try to decompress again to a new folder?

sorry my fault version .47

**Comment by slnit** [comment]
> Did you start it with start_http.bat? Did you try to decompress again to a new folder?

Yes, im tried but same result. Regards

**Comment by w-okada** [comment]
try to double click start_http.bat to start.

**Comment by nforestcat** [comment]
libomp140.x86_64.dll was missing for me. find the file from internet and put it _internal\torch\lib

**Comment by slnit** [comment]
> libomp140.x86_64.dll was missing for me. find the file from internet and put it _internal\torch\lib

![image](https://github.com/user-attachments/assets/30719760-e7ea-4b20-897c-5ed8d62d96a0)
 same result

**Comment by w-okada** [comment]
Regarding fbgemm.dll, It seems that there was a failure in bundling the library.
It has been updated in the new version of PyTorch. I reverted back to the original version, so it should work now.

please try vcclient_win_cuda_2.0.47a-alpha.zip.

**Comment by Rakkyotan** [comment]
I was able to install it.

**Comment by slnit** [comment]
The issue was solved in the las uploaded version, thanks.
