### ISSUE TITLE
[ISSUE]: When using the RVC format, it gives an incomprehensible error.

### ISSUE THREAD

**Issue by problemly** [w-okada/voice-changer#1307]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.18a

### Operational System

Win 10

### GPU

nvidia 1660 super 6gb

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

When using the RVC format, it gives an incomprehensible error. I tried the built-in voice on beatrice format and it worked, but here's the question: how to use RVC then?I don't have strong programming skills, so a guide for dummies=)

### Application Screenshot

![Снимок экрана 2024-08-09 022529](https://github.com/user-attachments/assets/c7da0207-b6e7-430f-a300-63f15250adae)

### Logs on console

C:\Users\user\Desktop\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
    failed to download weight for rvc
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> Beatrice-JVS
................Beatrice
[Voice Changer] [Beatrice] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer] [Beatrice] Initializing...
[Voice Changer] [Beatrice] Initializing... done
[Voice Changer][Beatrice]: update_settings gpu:0
[Voice Changer][Beatrice]: update_settings silentThreshold:0
[Voice Changer][Beatrice]: update_settings f0Detector:harvest
[Voice Changer][Beatrice]: update_settings extraConvertSize:8192
[Voice Changer][Beatrice]: update_settings serverReadChunkSize:128
[Voice Changer][Beatrice]: update_settings modelSlotIndex:1723159068000Beatrice-JVS
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-08-09 02:24:52] connet sid : a33QJCMnboaXWT4LAAAB
[2024-08-09 02:24:52] connet sid : 2qFNkOZfIopgEFEqAAAD
[Voice Changer] update configuration: modelSlotIndex 1723159494008
[Voice Changer] model slot is changed Beatrice-JVS -> 8
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
Exception ignored in: <function Beatrice.__del__ at 0x00000200CC116B90>
Traceback (most recent call last):
  File "voice_changer\Beatrice\Beatrice.py", line 189, in __del__
AttributeError: pipeline
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from pretrain/content_vec_500.onnx failed:Load model pretrain/content_vec_500.onnx failed. File doesn't exist
[Voice Changer] exception! loading embedder Model file not found: pretrain/hubert_base.pt cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 44, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from pretrain/content_vec_500.onnx failed:Load model pretrain/content_vec_500.onnx failed. File doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 48, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: pretrain/hubert_base.pt
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings silentThreshold:0
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer][RVC]: update_settings extraConvertSize:8192
[Voice Changer][RVC]: update_settings serverReadChunkSize:128
[Voice Changer][RVC]: update_settings modelSlotIndex:1723159494008
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
![Снимок экрана 2024-08-09 022654](https://github.com/user-attachments/assets/2befae5e-2fd8-41aa-a093-b1d0d61e323a)

**Comment by Kuuko-fokkusugaru** [comment]
I think you are missing some files from the initial setup.
Decompress the file in a new folder, start the file start_http.bat and wait for e everything to download. Very important to wait without interrupting the downloads or you may need to start all over.
Change the default device from cpu to gpu and test with the default settings and voice. You can also try setting the F0 detection to rmvpe or rmvpe_onnx instead of harvest. Don't set mic gain to 10 as too loud could distort the voice. If your mic works fine on a regular use out of RVC, then leave gain at 1.0 for now and set sound threshold to minimum to make sure that it picks any sound. Then test if that works before moving into other settings or different voice models. The logs definitely showed a missing file so I feel like the first startup messed the software hence why starting all over is the best option.

Additionally, if you can't make it work, you may want to try v2 https://huggingface.co/wok000/vcclient000/tree/main

**Comment by problemly** [comment]
ничего не помогло, сейчас качаю версию v2, но хотел бы дополнить что у меня была проблема с samples_0004_t.json samples_0004_d.json samples_0004_o.json из за этого я не мог раньше запустить приложение, я докачал эти файлы и приложение запустилось, но появилась проблема с голосами, может быть это поможет? @Kuuko-fokkusugaru

**Comment by problemly** [comment]
nothing helped, I'm currently downloading v2, but I would like to add that I had a problem with samples_0004_t.json samples_0004_d.json samples_0004_o.json from this I couldn't launch the application earlier, I downloaded these files and the application started, but there was a problem with the voices, maybe this will help? @Kuuko-fokkusugaru

**Comment by problemly** [comment]
V2 не запускается(

**Comment by Kuuko-fokkusugaru** [comment]
Mmm all I can think is if you have a firewall blocking files from being downloaded properly or antivirus deleting them wrongly.

**Comment by Kuuko-fokkusugaru** [comment]
Try to download again and decompress in a new folder but don't put this folder on the desktop or your documents/downloads. Instead, place the folder in the root of another drive. If you only have the C:/ drive then use the root of C:/ drive. For example, "C:/RVC". Download the file there and decompress there as well then start over and wait for all the downloads to finish. You should download the v2.0.58 cuda.

**Comment by problemly** [comment]
I would like to ask, how do I completely uninstall the program so that I can download it again?

**Comment by Kuuko-fokkusugaru** [comment]
> I would like to ask, how do I completely uninstall the program so that I can download it again?

Just delete the folder where you decompressed it
