### ISSUE TITLE
[ISSUE:]  i use every step in the voice ai setting but my voice not changing

### ISSUE THREAD

**Issue by Moonimez123** [w-okada/voice-changer#1366]
### Voice Changer Version

v.1.5.3.15 onexcpu-cuda 

### Operational System

windows 10pro

### GPU

none

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Peace be upon you. I downloaded the application and everything is fine, but when I turn on the START sound, my voice does not change even though I change the settings. I hear my voice from the background, but it does not change, even though I set the INPUT and OUTPUT to be correct, I think. I did not know the error. I watched full YouTube videos alone. Now my voice is still the same. I changed characters and nothing. I hope you can help us 
Note PASSTHRU is on
![W-OKADA](https://github.com/user-attachments/assets/ae5ffe40-e5f2-4707-8fe8-f62c5f7d928b)

### Logs on console

C:\Users\ETP-036\Downloads\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 3
................RVC
[VCClient] wait web server...10 http://127.0.0.1:18888/
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings serverReadChunkSize:112
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverOutputDeviceId:8
[Voice Changer][RVC]: update_settings serverMonitorDeviceId:8
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings modelSlotIndex:1727800101003
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-10-01 17:37:36] connet sid : XJNepkmnnrHix9NRAAAB
[2024-10-01 17:37:36] connet sid : -dUKBk52YIFr9SAnAAAD
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 258, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt
[9484] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

**Comment by Kuuko-fokkusugaru** [comment]
Hi there!
Let's first dive into some settings. Output and monitor can work in the same way but they have different purposes. They both output the sound but one is meant to we used to redirect the sound to something like virtual audio cable (VAC) while monitor is meant to be used to listen to yourself. Use monitor with your speakers or headset, but if you are also setting output to your speakers or headset to listen to yourself then set monitor to none because output would be already doing the same job. 

Gain input it's the volume of your mic so I recommend setting it to 1.0. Gain output it's the volume of the sound that you will send to virtual audio cable. Gain monitor is the volume to listen to yourself.

Passthru should be left off as default. Turning it on works to output your voice without any change, no voice changer at all.

I can see that you are not using any GPU, only CPU. This mode can be slow and sometimes doesn't work if the CPU isn't strong enough. For F0 detection I would recommend using a more suitable one for CPU since rmvpe_onnx is more intended for GPU. Try rmvpe or dio. I still recommend a GPU for better and proper performance.

I would also suggest to update to the latest version. The latest v1 one is v1.5.3.18a. You can also try v2 which is newer and may help on your issue. I have also noticed that you are using the CUDA version even though you are not using any GPU. CUDA is intended to be used with nvidia GPUs. If you are going to use the CPU, try the ML version in case of v1 or the standard version in case of v2. You can find all the latest versions in the following link:

https://huggingface.co/wok000/vcclient000/tree/main
