### ISSUE TITLE
[ISSUE for v2]: 

### ISSUE THREAD

**Issue by lulu3243** [w-okada/voice-changer#1371]
### Voice Changer Version

voice-changer-windows-nvidia-b2309

### Operational System

windows 10

### GPU

gtx 1660

### CUDA Version

12.6

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [X] I've tried to change the Chunk Size
- [X] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

YES

### Model Type

rvc

### Issue Description

Everything was working normally until yesterday it started to happen out of nowhere.

2024-10-06 09:05:34,751 INFO     [main] Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
2024-10-06 09:05:34,751 INFO     [main] Voice changer version: b2309 NVIDIA-CUDA
2024-10-06 09:05:34,751 INFO     [WeightDownloader] Loading weights.
2024-10-06 09:05:34,995 INFO     [Downloader] Verified pretrain/crepe_onnx_full.onnx
2024-10-06 09:05:34,996 INFO     [Downloader] Verified pretrain/crepe_onnx_tiny.onnx
2024-10-06 09:05:35,018 INFO     [Downloader] Verified pretrain/crepe_full.pth
2024-10-06 09:05:35,019 INFO     [Downloader] Verified pretrain/crepe_tiny.pth
2024-10-06 09:05:35,109 INFO     [Downloader] Verified pretrain/content_vec_500.onnx
2024-10-06 09:05:35,150 INFO     [Downloader] Verified pretrain/rmvpe.pt
2024-10-06 09:05:35,231 INFO     [Downloader] Verified pretrain/rmvpe.onnx
2024-10-06 09:05:35,241 INFO     [Downloader] Verified pretrain/fcpe.pt
2024-10-06 09:05:35,251 INFO     [Downloader] Verified pretrain/fcpe.onnx
2024-10-06 09:05:35,252 INFO     [WeightDownloader] All weights are loaded!
2024-10-06 09:05:35,252 INFO     [main] protocol: HTTP
local_attention\rotary.py:33: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
local_attention\rotary.py:55: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
2024-10-06 09:05:37,006 INFO     [loader] Loading faiss with AVX2 support.
2024-10-06 09:05:37,023 INFO     [loader] Successfully loaded faiss with AVX2 support.
2024-10-06 09:05:37,649 INFO     [VoiceChangerManager] Initializing...
2024-10-06 09:05:37,678 INFO     [DeviceManager] Initialized DeviceManager. Backend statuses:
2024-10-06 09:05:37,678 INFO     [DeviceManager] * DirectML: False, device count: 0
2024-10-06 09:05:37,679 INFO     [DeviceManager] * CUDA: True, device count: 1
2024-10-06 09:05:37,679 INFO     [DeviceManager] * MPS: False
2024-10-06 09:05:37,682 INFO     [DeviceManager] Switched to 0: NVIDIA GeForce GTX 1660 (CUDA) (cuda:0). FP16 support: False
2024-10-06 09:05:37,682 INFO     [VoiceChangerManager] Initialized.
Traceback (most recent call last):
  File "client.py", line 22, in <module>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "main.py", line 141, in main
  File "main.py", line 82, in runServer
  File "uvicorn\server.py", line 69, in serve
  File "uvicorn\server.py", line 76, in _serve
  File "uvicorn\config.py", line 434, in load
  File "uvicorn\importer.py", line 19, in import_from_string
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "app.py", line 24, in <module>
  File "voice_changer\VoiceChangerManager.py", line 78, in __init__
  File "voice_changer\VoiceChangerManager.py", line 149, in initialize
  File "voice_changer\ModelSlotManager.py", line 40, in get_slot_info
  File "voice_changer\ModelSlotManager.py", line 30, in _load_model_slot
IndexError: list index out of range

Press Enter to continue...

### Application Screenshot

![image](https://github.com/user-attachments/assets/c38ff20e-b878-47ed-9b7e-37259bd23d7d)

### Logs on console

2024-10-06 09:05:34,751 INFO     [main] Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
2024-10-06 09:05:34,751 INFO     [main] Voice changer version: b2309 NVIDIA-CUDA
2024-10-06 09:05:34,751 INFO     [WeightDownloader] Loading weights.
2024-10-06 09:05:34,995 INFO     [Downloader] Verified pretrain/crepe_onnx_full.onnx
2024-10-06 09:05:34,996 INFO     [Downloader] Verified pretrain/crepe_onnx_tiny.onnx
2024-10-06 09:05:35,018 INFO     [Downloader] Verified pretrain/crepe_full.pth
2024-10-06 09:05:35,019 INFO     [Downloader] Verified pretrain/crepe_tiny.pth
2024-10-06 09:05:35,109 INFO     [Downloader] Verified pretrain/content_vec_500.onnx
2024-10-06 09:05:35,150 INFO     [Downloader] Verified pretrain/rmvpe.pt
2024-10-06 09:05:35,231 INFO     [Downloader] Verified pretrain/rmvpe.onnx
2024-10-06 09:05:35,241 INFO     [Downloader] Verified pretrain/fcpe.pt
2024-10-06 09:05:35,251 INFO     [Downloader] Verified pretrain/fcpe.onnx
2024-10-06 09:05:35,252 INFO     [WeightDownloader] All weights are loaded!
2024-10-06 09:05:35,252 INFO     [main] protocol: HTTP
local_attention\rotary.py:33: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
local_attention\rotary.py:55: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
2024-10-06 09:05:37,006 INFO     [loader] Loading faiss with AVX2 support.
2024-10-06 09:05:37,023 INFO     [loader] Successfully loaded faiss with AVX2 support.
2024-10-06 09:05:37,649 INFO     [VoiceChangerManager] Initializing...
2024-10-06 09:05:37,678 INFO     [DeviceManager] Initialized DeviceManager. Backend statuses:
2024-10-06 09:05:37,678 INFO     [DeviceManager] * DirectML: False, device count: 0
2024-10-06 09:05:37,679 INFO     [DeviceManager] * CUDA: True, device count: 1
2024-10-06 09:05:37,679 INFO     [DeviceManager] * MPS: False
2024-10-06 09:05:37,682 INFO     [DeviceManager] Switched to 0: NVIDIA GeForce GTX 1660 (CUDA) (cuda:0). FP16 support: False
2024-10-06 09:05:37,682 INFO     [VoiceChangerManager] Initialized.
Traceback (most recent call last):
  File "client.py", line 22, in <module>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "main.py", line 141, in main
  File "main.py", line 82, in runServer
  File "uvicorn\server.py", line 69, in serve
  File "uvicorn\server.py", line 76, in _serve
  File "uvicorn\config.py", line 434, in load
  File "uvicorn\importer.py", line 19, in import_from_string
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "app.py", line 24, in <module>
  File "voice_changer\VoiceChangerManager.py", line 78, in __init__
  File "voice_changer\VoiceChangerManager.py", line 149, in initialize
  File "voice_changer\ModelSlotManager.py", line 40, in get_slot_info
  File "voice_changer\ModelSlotManager.py", line 30, in _load_model_slot
IndexError: list index out of range

Press Enter to continue...

**Comment by Kuuko-fokkusugaru** [comment]
Have you tried to decompress to a folder with a different name? Don't use the same folder or same old name, make a new one in the root of your drive (better if it's other than C)

**Comment by lulu3243** [comment]
I don't understand very well, can you explain it to me? it was working correctly, it always worked and then suddenly it stopped working

**Comment by Kuuko-fokkusugaru** [comment]
Oki, no problem.
First go to the root of one of your drives, for example your D or E if you have those. If you haven't, then use your C drive. Create a new folder and call it "RVC2" then get the compressed file that you downloaded with RVC and decompress everything inside of the new RVC2 folder. Now open it and look for the start_http.bat file and open it. In that way the software should be like a completely new and clean installation so it should be back to working. If that doesn't work, it could be that something changed in your system maybe?
