### ISSUE TITLE
[ISSUE for v2]: Can't run the program first time. The specified module could not be found. Error loading fbgemm.dll or one of its dependencies.

### ISSUE THREAD

**Issue by RodzKing** [w-okada/voice-changer#1380]
### Voice Changer Version

vcclient_win_cuda_2.0.61-alpha

### Operational System

11

### GPU

GeForce GTX 1050Ti

### CUDA Version

none

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

MMVC

### Issue Description

I tried to run the start_http.bat after extracting but it shows errors.

### Application Screenshot

![prob](https://github.com/user-attachments/assets/e023b5b1-b5a5-41ed-a698-e5211173811a)

### Logs on console

C:\Users\User\Downloads\vcclient_win_cuda_2.0.61-alpha\dist\main>main.exe cui --https false --no_cui True
Traceback (most recent call last):
  File "vcclient_dev\main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\initializer.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\sample_manager\sample_manager.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\slot_manager\slot_manager.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\slot_manager\model_importer\model_importer.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "vcclient_dev\voice_changer\slot_manager\model_importer\rvc_model_estimator\rvc_model_estimator.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "torch\__init__.py", line 143, in <module>
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\User\Downloads\vcclient_win_cuda_2.0.61-alpha\dist\main\_internal\torch\lib\fbgemm.dll" or one of its dependencies.
[8736] Failed to execute script 'main' due to unhandled exception!

**Comment by Aria-Victoria** [comment]
Same issue. The download server might be down for the requested resource?

**Comment by Kuuko-fokkusugaru** [comment]
Could you try installing MSVC redistributable?
Let me know if it fixes your issue.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Kuuko-fokkusugaru** [comment]
You may need to delete the folder with the decompressed RVC and start with a clean one.

**Comment by RodzKing** [comment]
> Could you try installing MSVC redistributable? Let me know if it fixes your issue. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Working now and downloading.

**Comment by Kuuko-fokkusugaru** [comment]
@w-okada I have noticed that many of the issues may be related with missing dependencies. I though RVC didn't have any but it clearly does. Do you think that RVC could be updated to check for dependencies and display the right message to tell the user to download them instead of giving an error or simply not working? It would help greatly to many starters.
