### ISSUE TITLE
fairseq is missing in Master branch

### ISSUE THREAD

**Issue by little-file** [w-okada/voice-changer#1392]
### In a few words, describe your idea

There is no requirement fairseq in the server

### More information

[Voice Changer] post_update_settings ex: No module named 'fairseq'
Traceback (most recent call last):
  File "/home/little/Projects/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
  File "/home/little/Projects/voice-changer/server/voice_changer/VoiceChangerManager.py", line 348, in update_settings
    self.generateVoiceChanger(newVal)
  File "/home/little/Projects/voice-changer/server/voice_changer/VoiceChangerManager.py", line 256, in generateVoiceChanger
    from voice_changer.RVC.RVCr2 import RVCr2
  File "/home/little/Projects/voice-changer/server/voice_changer/RVC/RVCr2.py", line 12, in <module>
    from voice_changer.RVC.embedder.EmbedderManager import EmbedderManager
  File "/home/little/Projects/voice-changer/server/voice_changer/RVC/embedder/EmbedderManager.py", line 5, in <module>
    from voice_changer.RVC.embedder.FairseqContentvec import FairseqContentvec
  File "/home/little/Projects/voice-changer/server/voice_changer/RVC/embedder/FairseqContentvec.py", line 3, in <module>
    from voice_changer.RVC.embedder.FairseqHubert import FairseqHubert
  File "/home/little/Projects/voice-changer/server/voice_changer/RVC/embedder/FairseqHubert.py", line 4, in <module>
    from fairseq import checkpoint_utils
ModuleNotFoundError: No module named 'fairseq'

**Comment by TooManyHobbies** [comment]
Hi, I don't know much about this project, and really haven't gotten it to work, but  on my Linux machine I did the following:

conda install conda-forge::fairseq
conda install conda-forge::pyworld

Then as per this issue https://github.com/w-okada/voice-changer/issues/1233 I removed line 11 from the file 

server/voice_changer/RVC/pitchExtractor/PitchExtractorManager.py

That got things running, but still not working. Maybe you will have better luck.
