### ISSUE TITLE
[REQUEST]: Using beatrice model reports an error out of bounds for axis 0 with size 1？

### ISSUE THREAD

**Issue by OneByOneB** [w-okada/voice-changer#1417]
### In a few words, describe your idea

error out of bounds for axis 0 with size 1

### More information

I trained a beatrice voice, but when I used it I got an IndexError: index 63 is out of bounds for axis 0 with size 1. This is the second sound I trained. The first one is normal. I don’t know which step is wrong with this one?

The following is the log：

vcclient   - voice_changer     - WARNING - Failed to convert_chunk_bulk_internal:Traceback (most recent call last):
  File "vcclient_dev\voice_changer\voice_change_manager\voice_changer.py", line 363, in convert_chunk_bulk_internal
  File "vcclient_dev\voice_changer\voice_change_manager\voice_changer.py", line 390, in convert_chunk
  File "vcclient_dev\voice_changer\voice_change_manager\voice_changer.py", line 517, in _convert_chunk
  File "vcclient_dev\voice_changer\voice_change_manager\vc_pipelines\beatricev2_pipeline.py", line 71, in run
  File "beatrice_python\simple_beatrice.py", line 119, in convert_segment
IndexError: index 63 is out of bounds for axis 0 with size 1

**Comment by OneByOneB** [comment]
I use vcclient_win_std_2.0.73-beta

**Comment by OneByOneB** [comment]
I found the problem. It was because the configuration file was written incorrectly.
