### ISSUE TITLE
When I use real-time translation

### ISSUE THREAD

**Issue by bambooqj** [w-okada/voice-changer#145]
![image](https://user-images.githubusercontent.com/20792621/227448450-56873a25-0536-463f-98d6-a91a77437e34.png)
When I use real-time translation, the volume keeps increasing indefinitely. What could be causing this problem?

[15832:0324/150711.482:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
[2023-03-24 15:07:14] connet sid : NwFCE8EsrCe1K0tmAAAH
post request handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 289, in handle_request
  File "engineio\asyncio_socket.py", line 109, in handle_post_request
  File "engineio\payload.py", line 13, in __init__
  File "engineio\payload.py", line 44, in decode
ValueError: Too many packets in payload
ERROR:engineio.server:post request handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 289, in handle_request
  File "engineio\asyncio_socket.py", line 109, in handle_post_request
  File "engineio\payload.py", line 13, in __init__
  File "engineio\payload.py", line 44, in decode
ValueError: Too many packets in payload

**Comment by w-okada** [comment]
res(ms) is response time to convert voice. If your PC is not sufficient power to convert voice, this value is increasing.

**Comment by w-okada** [comment]
no response, closed
