### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq'

### ISSUE THREAD

**Issue by WuhuVoV** [w-okada/voice-changer#147]
Process p:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "MMVCServerSIO.py", line 112, in localServer
  File "uvicorn\main.py", line 569, in run
  File "uvicorn\server.py", line 60, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "uvicorn\server.py", line 67, in serve
  File "uvicorn\config.py", line 477, in load
  File "uvicorn\importer.py", line 24, in import_from_string
  File "uvicorn\importer.py", line 21, in import_from_string
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "MMVCServerSIO.py", line 125, in <module>
  File "voice_changer\VoiceChangerManager.py", line 10, in get_instance
  File "voice_changer\VoiceChanger.py", line 62, in __init__
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "voice_changer\SoVitsSvc40\SoVitsSvc40.py", line 24, in <module>
ModuleNotFoundError: No module named 'fairseq'
did-fail-load
(node:7444) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/142
