### ISSUE TITLE
このエラーを修正するにはどうすればよいですか？

### ISSUE THREAD

**Issue by fatinghenji** [w-okada/voice-changer#149]
エラーログは以下に記載されています：
```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-861' coro=<AsyncServer._handle_event_internal() done, defined at socketio\asyncio_server.py:522> exception=AttributeError("'SoVitsSvc40' object has no attribute 'hubert_model'")>
Traceback (most recent call last):
  File "socketio\asyncio_server.py", line 524, in _handle_event_internal
  File "socketio\asyncio_server.py", line 569, in _trigger_event
  File "socketio\asyncio_namespace.py", line 37, in trigger_event
  File "sio\MMVC_Namespace.py", line 34, in on_request_message
  File "voice_changer\VoiceChangerManager.py", line 36, in changeVoice
  File "voice_changer\VoiceChanger.py", line 185, in on_request
  File "voice_changer\SoVitsSvc40\SoVitsSvc40.py", line 240, in generate_input
  File "voice_changer\SoVitsSvc40\SoVitsSvc40.py", line 199, in get_unit_f0
AttributeError: 'SoVitsSvc40' object has no attribute 'hubert_model'
```

**Comment by w-okada** [comment]
hubertがロードされていないみたいです。
readmeに記載の次の部分は実施されましたか？
-----------------
・so-vits-svc 4.0/so-vits-svc 4.0v2 やつくよみちゃんの動作には content vec のモデルが必要となります。こちらの[リポジトリ](https://github.com/auspicious3000/contentvec)から、ContentVec_legacy 500 のモデルをダウンロードして、実行するstartHttp_xxx.commandやstart_http_xxx.batと同じフォルダに配置してください。
-----------------

**Comment by fatinghenji** [comment]
すみません、hubertを間違ったフォルダに入れました。 日本語と英語は私の母国語ではないので、readmeの該当部分に気づかなかったかもしれません。
