### ISSUE TITLE
  Unable to successfully upload RVC's pth file

### ISSUE THREAD

**Issue by cj0596** [w-okada/voice-changer#153]
The RVC .pth file upload process gets stuck midway and cannot be successfully uploaded. 

Screenshot：    https://s1.locimg.com/2023/04/09/434d527dae290.png

The log information is as follows:

D:\AI\MMVCServerSIO>MMVCServerSIO.exe --https off -p 18888 --modelType RVC --hubert hubert_base.pt
    Booting PHASE :__main__
    Voice Changerを起動しています。
    -- 設定 --
    CONFIG:None, MODEL:None ONNX_MODEL:None
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/?modelType=RVC

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[VoiceChanger] activate model type: RVC
没有发现支持的N卡, 使用CPU进行推理
RVC initialization:  {'hubert': 'hubert_base.pt', 'useHubertOnnx': False}
VoiceChanger Initialized (GPU_NUM:0, mps_enabled:False)
[2023-04-09 11:35:34] connet sid : 7U2XZMopcnDApjvwAAAC
[2023-04-09 11:35:34] connet sid : rzvaozOuLSno25tUAAAD
post_update_setteings crossFadeOffsetRate 0.1
post_update_setteings crossFadeEndRate 0.8
post_update_setteings crossFadeOverlapSize 1024
post_update_setteings framework PyTorch
post_update_setteings onnxExecutionProvider CPUExecutionProvider
Onnx is not enabled. Please load model.
onnxExecutionProvider is not mutable variable or unknown variable!
post_update_setteings f0Detector harvest
post_update_setteings tran 10
post_update_setteings noiceScale 0.3
post_update_setteings silentThreshold 0.00001
post_update_setteings extraConvertSize 32768
post_update_setteings clusterInferRatio 0.1
clusterInferRatio is not mutable variable or unknown variable!
post_update_setteings modelSamplingRate 48000
post_update_setteings inputSampleRate 48000
[13692:0409/113716.999:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "engineio\async_drivers\asgi.py", line 67, in __call__
  File "fastapi\applications.py", line 270, in __call__
  File "starlette\applications.py", line 124, in __call__
  File "starlette\middleware\errors.py", line 184, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\cors.py", line 92, in __call__
  File "starlette\middleware\cors.py", line 147, in simple_response
  File "starlette\middleware\exceptions.py", line 79, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 21, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 706, in __call__
  File "starlette\routing.py", line 276, in handle
  File "starlette\routing.py", line 66, in app
  File "fastapi\routing.py", line 235, in app
  File "fastapi\routing.py", line 163, in run_endpoint_function
  File "starlette\concurrency.py", line 41, in run_in_threadpool
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "restapi\MMVC_Rest_Fileuploader.py", line 69, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 14, in loadModel
  File "voice_changer\VoiceChanger.py", line 86, in loadModel
  File "voice_changer\RVC\RVC.py", line 105, in loadModel
KeyError: 'config'
  File "starlette\middleware\errors.py", line 184, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\cors.py", line 92, in __call__
  File "starlette\middleware\cors.py", line 147, in simple_response
  File "starlette\middleware\exceptions.py", line 79, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 21, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 706, in __call__
  File "starlette\routing.py", line 276, in handle
  File "starlette\routing.py", line 66, in app
  File "fastapi\routing.py", line 235, in app
  File "fastapi\routing.py", line 163, in run_endpoint_function
  File "starlette\concurrency.py", line 41, in run_in_threadpool
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "restapi\MMVC_Rest_Fileuploader.py", line 69, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 14, in loadModel
  File "voice_changer\VoiceChanger.py", line 86, in loadModel
  File "voice_changer\RVC\RVC.py", line 105, in loadModel
KeyError: 'config'

**Comment by w-okada** [comment]
It seems that your model is not valid.
Did you upload the pth in weights folder ?(not in log folder)

**Comment by cj0596** [comment]
> 

Yes! It's the problem! Thanks!

But here is another problem: The VC Client can't find my GPU,just as the log above:

[VoiceChanger] activate model type: RVC
没有发现支持的N卡, 使用CPU进行推理 ← No supported NVIDIA GPU found, using CPU for inference
RVC initialization: {'hubert': 'hubert_base.pt', 'useHubertOnnx': False}

But my computer has the Nvidia 3060Ti:
https://pasteboard.co/4wvK3ZD9llWh.png

**Comment by w-okada** [comment]
please use the latest version.

**Comment by w-okada** [comment]
Close.
