### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by 0x25a6** [w-okada/voice-changer#155]
v.1.5.1.15b の macOS 用のバイナリを使用したところ以下のエラーが出力されて動作しません。
startHttps_RVC.command を Mac で実行してローカルネットワーク上の Windows10 から利用しようとしています。
Windows10 上の Chrome で UI を表示し RVC のモデルをアップロードするところまでは正常に動作しているようです。
どのように解決すればよいか教えていただけると幸いです。

macOS Monterey 12.2.1
Apple M1 Max

```
VC PROCESSING!!!! EXCEPTION!!! "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "voice_changer/VoiceChanger.py", line 197, in on_request
  File "voice_changer/RVC/RVC.py", line 277, in inference
  File "voice_changer/RVC/RVC.py", line 267, in _pyTorch_inference
  File "voice_changer/RVC/custom_vc_infer_pipeline.py", line 149, in pipeline
  File "voice_changer/RVC/custom_vc_infer_pipeline.py", line 86, in vc
  File "fairseq/models/hubert/hubert.py", line 535, in extract_features
    res = self.forward(
  File "fairseq/models/hubert/hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "fairseq/models/hubert/hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "fairseq/models/wav2vec/wav2vec2.py", line 895, in forward
    x = conv(x)
  File "torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```

**Comment by g20271** [comment]
私の環境(Windows Ryzen 5 5600X)でもCPUで動作させると同様のエラーが出ましたが、Model Settingのhalf-precisionのチェックを外して実行すると正常に動作するようになりました。

**Comment by w-okada** [comment]
それは仕様です。half-presicionはCPUでサポートされていません。
Twitterに挙げてある動画を参照していただけると幸いです。

https://twitter.com/DannadoriYellow/status/1644778267474530305?s=20

**Comment by 0x25a6** [comment]
ご返信ありがとうございます。解決しました、ありがとうございます。
確認不足で申し訳有りませんでした。お手数おかけしました。
issue の close ありがとうございました。
