### ISSUE TITLE
v.1.5.1.15bにてDestination Speaker id が空となる

### ISSUE THREAD

**Issue by migratoryfish** [w-okada/voice-changer#156]
# 環境
- OS : windows10 Home(22H2)
- CPU : Corei5 4670(無印)
- RAM : 16GB
- GPU : GTX 1070 (VRAM 8GB)
- Version : v.1.5.1.15b
- `ONNX(cpu,cuda), PyTorch(cpu,cuda)`版及び`ONNX(cpu,DirectML), PyTorch(cpu) `版の両方で発生します

# 詳細
start_http_RVC.batを起動後表示されたVC Client画面→
Speaker Settingエリア→Destination Speaker id のプルダウンが空のままとなっています。
グレーアウトはされておらず選択は可能なのですがプルダウンリストが空のため
選択できるスピーカーが存在しません。
この状態のままModel SettingからPytorch(.pth)からmodelを選択uploadし
Server ControlにてStartを押下すると下記エラーメッセージ表示されボイスチェンジャーが動作しません。

v.1.5.1.15aでは当該プルダウンには`default(0)`がデフォルトで選択済みで
正常にボイスチェンジャーが動作していることを確認しております。
```
>MMVCServerSIO.exe --https off -p 18888 --modelType RVC --hubert hubert_base.pt
    Booting PHASE :__main__
    Voice Changerを起動しています。
    -- 設定 --
    CONFIG:None, MODEL:None ONNX_MODEL:None
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/?modelType=RVC

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[VoiceChanger] activate model type: RVC
没有发现支持的N卡, 使用CPU进行推理
RVC initialization:  {'hubert': 'hubert_base.pt', 'useHubertOnnx': False}
VoiceChanger Initialized (GPU_NUM:0, mps_enabled:False)
[2023-04-09 23:56:47] connet sid : Q-YbisX5-xZGzGp9AAAC
[2023-04-09 23:56:47] connet sid : QcKv6Onx2DLKkGurAAAD
post_update_setteings crossFadeOffsetRate 0.1
post_update_setteings crossFadeEndRate 0.8
post_update_setteings crossFadeOverlapSize 1024
post_update_setteings framework PyTorch
post_update_setteings onnxExecutionProvider CPUExecutionProvider
Onnx is not enabled. Please load model.
post_update_setteings f0Detector harvest
onnxExecutionProvider is not mutable variable or unknown variable!
post_update_setteings tran 14
post_update_setteings noiceScale 0.3
post_update_setteings predictF0 1
post_update_setteings extraConvertSize 32768
post_update_setteings silentThreshold 0.00001
post_update_setteings clusterInferRatio 0.1
clusterInferRatio is not mutable variable or unknown variable!
post_update_setteings inputSampleRate 24000
[2023-04-09 23:57:38] connet sid : bBPFOedDav9aik81AAAF
[2023-04-09 23:57:38] connet sid : A8EhrdVeT1WKtgv2AAAH
post_update_setteings crossFadeOffsetRate 0.1
post_update_setteings crossFadeOverlapSize 1024
post_update_setteings crossFadeEndRate 0.8
post_update_setteings framework PyTorch
post_update_setteings onnxExecutionProvider CPUExecutionProvider
Onnx is not enabled. Please load model.
onnxExecutionProvider is not mutable variable or unknown variable!
post_update_setteings f0Factor 1
f0Factor is not mutable variable or unknown variable!
post_update_setteings f0Detector harvest
post_update_setteings tran 10
post_update_setteings noiceScale 0.3
post_update_setteings silentThreshold 0.00001
post_update_setteings extraConvertSize 32768
post_update_setteings clusterInferRatio 0.1
clusterInferRatio is not mutable variable or unknown variable!
post_update_setteings modelSamplingRate 48000
post_update_setteings inputSampleRate 48000
EXCEPTION during loading hubert/contentvec model Model file not found: hubert_base.pt
gin_channels: 256 self.spk_embed_dim: 109
Generated Strengths: for prev:(1024,), for cur:(1024,)
VC PROCESSING!!!! EXCEPTION!!! 'RVC' object has no attribute 'hubert_model'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 197, in on_request
  File "voice_changer\RVC\RVC.py", line 277, in inference
  File "voice_changer\RVC\RVC.py", line 242, in _pyTorch_inference
AttributeError: 'RVC' object has no attribute 'hubert_model'

VC PROCESSING!!!! EXCEPTION!!! 'RVC' object has no attribute 'hubert_model'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 197, in on_request
  File "voice_changer\RVC\RVC.py", line 277, in inference
  File "voice_changer\RVC\RVC.py", line 242, in _pyTorch_inference
AttributeError: 'RVC' object has no attribute 'hubert_model'
```

**Comment by migratoryfish** [comment]
すみません
大変な見落としをしておりました。本件クローズします。

`hubert_base.pt`を配置し忘れており当該ファイルを配置後は
`ONNX(cpu,cuda), PyTorch(cpu,cuda)`版で正常動作いたしました。
ただ私の環境はnvidiaGPUですが
`ONNX(cpu,DirectML), PyTorch(cpu)`版では下記メッセージが出力され
ボイスチェンジャーが動作しませんでした。
これは私の環境が
>環境によって極まれに gpu が認識されない場合があります。

に該当するからだと思います。

また
>Destination Speaker id が空

に関してもyoutubeで公開されている

>VC Client v.1.5.1.15b (遅延のコントロール)

を視聴してv.1.5.1.15b 環境下ならそれが正常であると認識できました。

```
VC PROCESSING!!!! EXCEPTION!!! "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 197, in on_request
  File "voice_changer\RVC\RVC.py", line 277, in inference
  File "voice_changer\RVC\RVC.py", line 267, in _pyTorch_inference
  File "voice_changer\RVC\custom_vc_infer_pipeline.py", line 149, in pipeline
  File "voice_changer\RVC\custom_vc_infer_pipeline.py", line 86, in vc
  File "fairseq\models\hubert\hubert.py", line 535, in extract_features
    res = self.forward(
  File "fairseq\models\hubert\hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "fairseq\models\hubert\hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "fairseq\models\wav2vec\wav2vec2.py", line 895, in forward
    x = conv(x)
  File "torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```
