### ISSUE TITLE
マージしたモデルのアップロードが途中で停止する

### ISSUE THREAD

**Issue by 0x25a6** [w-okada/voice-changer#161]
https://rentry.co/ozmm3
上記記載の方法でマージしたモデルを MMVCServerSIO_win_onnxgpu-cuda_v.1.5.1.15b にて使用しようとしたところ、uploading... 92.0% で停止してしまい以下のエラーが出力されました。
```bash
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "engineio\async_drivers\asgi.py", line 67, in __call__
  File "fastapi\applications.py", line 270, in __call__
  File "starlette\applications.py", line 124, in __call__
  File "starlette\middleware\errors.py", line 184, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\cors.py", line 92, in __call__
  File "starlette\middleware\cors.py", line 147, in simple_response
  File "starlette\middleware\exceptions.py", line 79, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 21, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 706, in __call__
  File "starlette\routing.py", line 276, in handle
  File "starlette\routing.py", line 66, in app
  File "fastapi\routing.py", line 235, in app
  File "fastapi\routing.py", line 163, in run_endpoint_function
  File "starlette\concurrency.py", line 41, in run_in_threadpool
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "restapi\MMVC_Rest_Fileuploader.py", line 69, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 14, in loadModel
  File "voice_changer\VoiceChanger.py", line 86, in loadModel
  File "voice_changer\RVC\RVC.py", line 108, in loadModel
  File "torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for dec.conv_post.weight: copying a param with shape torch.Size([1, 16, 7]) from checkpoint, the shape in current model is torch.Size([1, 32, 7]).
[24728:0413/022820.935:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```
今回、サンプリングレート 48k で生成した 2 つのモデル (epoch:400 のモデルと epoch:150 のモデル) をマージしたモデルを使用したところ上記のエラーが出力されました。マージする際の目標サンプリングレートを 48k にした場合と 40k にした場合を試しましたが、変化はありませんでした。
以前、サンプリングレート 40k で生成した 2 つのモデル(epoch:60 のモデルと epoch:60 のモデル)をマージしたモデルを使用した時は上記のエラーは発生せず正常に使えていましたので、マージしたモデルに原因があるのかもしれません。

(モデルをマージする際は学習回数が同じモデル同士でなければならないのかもしれないとも考えました。実際、epoch:60のモデル(40k) と epoch:100のモデル(40k) をマージしようとしたところ Fail to merge the models. The model architectures are not the same. と表示されマージできないケースもありました。
ところが、今回 epoch:400のモデル(48k) と epoch:150のモデル(48k)をマージした際は、正常にマージモデルが出力されました。ですので、マージできる条件も正直よく分かっていない状態です。)

また、MMVCServerSIO_win_onnxgpu-cuda_v.1.5.2.1 を使用した場合も同様に uploading... 92.0% で停止してしまいますが、上記のエラーは出力されませんでした。

モデルの問題かもしれませんが、上記のエラーを見て何か分かりましたら教えていただけると幸いです。

ちなみに、最終行の
```
[24728:0413/022820.935:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```
は正常に動作している時にも出力されていることがあるので、今回の問題には関係無いかもしれません。

**Comment by w-okada** [comment]
https://github.com/liujing04/Retrieval-based-Voice-Conversion-WebUI/commits/main/train/process_ckpt.py

これを見る限り、mismatchのバグがあって、修正が発生しているようです。
最新版でマージしてみていただけないでしょうか？

**Comment by w-okada** [comment]
Discordで解決事例あり。
![image](https://user-images.githubusercontent.com/48346627/231632961-b99049a0-d0ac-44f2-a1e2-4f56637344fc.png)

**Comment by 0x25a6** [comment]
ありがとうございます。
最新版の process_ckpt.py を使ったところエラーが発生しなくなりました。
ご対応ありがとうございました。
