### ISSUE TITLE
AttributeError: 'HParams' object has no attribute 'n_speakers'

### ISSUE THREAD

**Issue by 2p31-1** [w-okada/voice-changer#164]
```
PORT:16961, LOG_FILE:LOG_FILE_16961, model_param: -m /content/drive/MyDrive/VoiceChanger/mika/G_24000.pth
```

```
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
Traceback (most recent call last):
  File "/content/voice-changer/server/MMVCServerSIO.py", line 104, in <module>
    voiceChangerManager.loadModel(CONFIG, MODEL, ONNX_MODEL)
  File "/content/voice-changer/server/voice_changer/VoiceChangerManager.py", line 14, in loadModel
    info = self.voiceChanger.loadModel(config, model, onnx_model)
  File "/content/voice-changer/server/voice_changer/VoiceChanger.py", line 72, in loadModel
    n_speakers=self.hps.data.n_speakers,
AttributeError: 'HParams' object has no attribute 'n_speakers'
```

**Comment by w-okada** [comment]
The latest version, you cannot pass the parameter for model. delete "-m xxx.pth", and upload via GUI.

**Comment by w-okada** [comment]
no reply. Close.

**Comment by 2blackbar** [comment]
HEy dev, this error makes the gui stuck in a bootloop and its pretty serious, your answer is pretty vague, where i should go and remove files from, cant you add some check to ignore those errors and just load gui without model if there such error that can cause bootloop?  It makes the whole gui stop working

**Comment by w-okada** [comment]
use feature request template
