### ISSUE TITLE
CUDA error attempting to convert to Onnx 

### ISSUE THREAD

**Issue by kalomaze** [w-okada/voice-changer#211]
`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "engineio\async_drivers\asgi.py", line 67, in __call__
  File "fastapi\applications.py", line 270, in __call__
  File "starlette\applications.py", line 124, in __call__
  File "starlette\middleware\errors.py", line 184, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\middleware\exceptions.py", line 79, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 21, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 706, in __call__
  File "starlette\routing.py", line 276, in handle
  File "starlette\routing.py", line 66, in app
  File "fastapi\routing.py", line 235, in app
  File "fastapi\routing.py", line 163, in run_endpoint_function
  File "starlette\concurrency.py", line 41, in run_in_threadpool
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "restapi\MMVC_Rest_Fileuploader.py", line 124, in get_onnx
  File "voice_changer\VoiceChangerManager.py", line 58, in export2onnx
  File "voice_changer\VoiceChanger.py", line 350, in export2onnx
  File "voice_changer\RVC\RVC.py", line 582, in export2onnx
  File "voice_changer\RVC\export2onnx.py", line 73, in export2onnx
  File "torch\onnx\utils.py", line 504, in export
  File "torch\onnx\utils.py", line 1529, in _export
  File "torch\onnx\utils.py", line 1111, in _model_to_graph
  File "torch\onnx\utils.py", line 987, in _create_jit_graph
  File "torch\onnx\utils.py", line 891, in _trace_and_get_graph_from_model
  File "torch\jit\_trace.py", line 1184, in _get_trace_graph
  File "torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\jit\_trace.py", line 127, in forward
  File "torch\jit\_trace.py", line 118, in wrapper
  File "torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "voice_changer\RVC\onnx\SynthesizerTrnMs256NSFsid_ONNX.py", line 94, in forward
  File "torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\Kalo\Downloads\MMVCServerSIO\RVC\infer_pack\models.py", line 435, in forward
    xs += self.resblocks[i * self.num_kernels + j](x)
  File "torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torch\nn\modules\module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\Kalo\Downloads\MMVCServerSIO\RVC\infer_pack\modules.py", line 309, in forward
    x = xt + x
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 6.00 GiB total capacity; 5.07 GiB already allocated; 0 bytes free; 5.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I tried using the RVC onnx exporter but that also didnt work as it complained about missing onnx module, installing it manually complained about having no attribute 'load_from_string', any further help would be appreciated

**Comment by w-okada** [comment]
VC Client will have a functionality to export onnx with cpu at next version.
please wait

**Comment by w-okada** [comment]
v.1.5.2.8 is released. you can export onnx with cpu. try it.

**Comment by foxydevloper** [comment]
> v.1.5.2.8 is released. you can export onnx with cpu. try it.

How do you set it to export using CPU?

**Comment by w-okada** [comment]
Set gpu -1, then export .

![image](https://user-images.githubusercontent.com/48346627/236572535-830d6476-d3f7-4315-8365-682fdadaacaf.png)

**Comment by kalomaze** [comment]
[Voice Changer] Model Load Error! Check your model is valid. local variable 'embedder' referenced before assignment
[Voice Changer] update configuration: gpu -1
CHAGE TO NEW PIPELINE False
[Voice Changer] export2onnx, No pyTorch filepath.

The pth is uploaded, however, every time I upload a model on the new version, I get this:

  File "torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 131, in loadModel
  File "voice_changer\RVC\RVC.py", line 86, in loadModel
  File "voice_changer\RVC\RVC.py", line 154, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 53, in createPipeline
UnboundLocalError: local variable 'embedder' referenced before assignment

[Voice Changer] Model Load Error! Check your model is valid. local variable 'embedder' referenced before assignment

**Comment by kalomaze** [comment]
I think it failed downloading hubert_base.pt (or some other pretrained weight??) on the first run of the new version. 

Now I have this error:

```
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Prepare done.
[Voice Changer] Switching model..
[Voice Changer] Switching model..done
[Voice Changer] exporting onnx... gpu_id:-1 gpu_mem:0
[Voice Changer] Warning!!! onnx export with float32. maybe size is doubled.
gin_channels: 256 self.spk_embed_dim: 109
torch\onnx\utils.py:2040: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input feats
torch\onnx\utils.py:2040: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input pitch
torch\onnx\utils.py:2040: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input pitchf
C:\Users\Andrew\Downloads\MMVCServerSIO\RVC\infer_pack\attentions.py:236: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  t_s == t_t
C:\Users\Andrew\Downloads\MMVCServerSIO\RVC\infer_pack\attentions.py:298: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  pad_length = max(length - (self.window_size + 1), 0)
C:\Users\Andrew\Downloads\MMVCServerSIO\RVC\infer_pack\attentions.py:299: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  slice_start_position = max((self.window_size + 1) - length, 0)
C:\Users\Andrew\Downloads\MMVCServerSIO\RVC\infer_pack\attentions.py:301: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_length > 0:
torch\onnx\_internal\jit_utils.py:258: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
torch\onnx\_internal\jit_utils.py:258: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ..\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
torch\onnx\utils.py:687: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ..\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
torch\onnx\utils.py:687: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
torch\onnx\utils.py:1178: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at ..\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
torch\onnx\utils.py:1178: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
[17300:0505/195115.377:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```
