### ISSUE TITLE
Exception during loading hubert/contentvec model stat

### ISSUE THREAD

**Issue by buildcore** [w-okada/voice-changer#222]
Tried: loaded two models so-vits-svc and rvc independently (.json, .pt, .pth), loaded correctly
Device: MacOS M1

Something looks wrong in SoVitsSvc40.py, in `loadModel()`: 

 ```
content_vec_path = self.params.content_vec_500
        content_vec_onnx_path = self.params.content_vec_500_onnx
        content_vec_onnx_on = self.params.content_vec_500_onnx_on
        hubert_base_path = self.params.hubert_base
```

Moreover, got an exception on "voice_changer/VoiceChanger.py":

```
VC PROCESSING!!!! EXCEPTION!!! ufunc 'resample_f_s' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule "'safe'
Traceback (most recent call last):
File "voice_changer/VoiceChanger py", line 231, in on_request_sola
File "resampy/core.py", line 168, in resample File "numba/np/ufunc/gufunc.py", line 192, in _call.
lypetrror: ufunc 'resample_f_s' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule lisafpli
```

**Comment by w-okada** [comment]
I cannot reproduce it. please tell me how to reproduce.

**Comment by w-okada** [comment]
no res. close
