### ISSUE TITLE
RVCでトレーニングしたモデルがアップロード出来ない

### ISSUE THREAD

**Issue by maaakigai** [w-okada/voice-changer#232]
AnacondaでVCClientを起動し、RVCでトレーニングしたモデルをアップロードしようと試みたところ、何度ファイルを指定してアップロードを行っても反映がされませんでした。ブラウザはChromeを使用しました。
（２）の項目にある事前ビルド済みの Binary では正常にアップロードができ、モデルは問題なく使用できました。
解決策を教えていただけると嬉しいです。

下記はアップロードが出来なかった時のログです。

INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64584 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64583 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64590 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64587 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64588 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "POST /concat_uploaded_file HTTP/1.1" 200 OK
paramDict {'trans': 0, 'files': {'mmvcv13Config': '', 'mmvcv13Model': '', 'mmvcv15Config': '', 'mmvcv15Model': '', 'soVitsSvc40Config': '', 'soVitsSvc40Model': '', 'soVitsSvc40Cluster': '', 'soVitsSvc40v2Config': '', 'soVitsSvc40v2Model': '', 'soVitsSvc40v2Cluster': '', 'rvcModel': 'george.pth', 'rvcIndex': '', 'rvcFeature': '', 'ddspSvcModel': '', 'ddspSvcModelConfig': '', 'ddspSvcDiffusion': '', 'ddspSvcDiffusionConfig': ''}}
Traceback (most recent call last):
  File "/mnt/c/Users/miura/voice-changer/server/voice_changer/VoiceChanger.py", line 299, in loadModel
    return self.voiceChanger.loadModel(props)
AttributeError: 'NoneType' object has no attribute 'loadModel'

[Voice Changer] Model Load Error! Check your model is valid. 'NoneType' object has no attribute 'loadModel'
INFO:     172.19.176.1:64593 - "POST /load_model HTTP/1.1" 200 OK
INFO:     172.19.176.1:64593 - "GET /info HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/engineio/async_drivers/asgi.py", line 67, in __call__
    await self.other_asgi_app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/c/Users/miura/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 57, in get_info
    info = self.voiceChangerManager.get_info()
  File "/mnt/c/Users/miura/voice-changer/server/voice_changer/VoiceChangerManager.py", line 30, in get_info
    info = self.voiceChanger.get_info()
  File "/mnt/c/Users/miura/voice-changer/server/voice_changer/VoiceChanger.py", line 308, in get_info
    data.update(self.voiceChanger.get_info())
AttributeError: 'NoneType' object has no attribute 'get_info'

備考）
サーバー開発者向けのページにあった
python3 MMVCServerSIO.py -p 18888 --https true \
  --content_vec_500 weights/checkpoint_best_legacy_500.pt \
  --hubert_base weights/hubert_base.pt \
  --hubert_soft weights/hubert-soft-0d54a1f4.pt \
  --nsf_hifigan weights/nsf_hifigan/model
  を入力してもVCClientが起動出来なかったため、

python3 MMVCServerSIO.py -p 18888 --https true \
  --content_vec_500 weights/checkpoint_best_legacy_500.pt \
  --hubert_base weights/hubert_base.pt \
  --hubert_base_jp weights/model.pt \
  --hubert_soft weights/hubert-soft-0d54a1f4.pt \
  --nsf_hifigan weights/nsf_hifigan/model
と書き加えて起動しました。

$ pip install -r requirements.txt
を最初に実行した際に、
error: command 'gcc' failed: No such file or directory
と
error: Failed building wheel for fairseq
と
could not build wheels for pyworld, fairseq, which is required to install paproject.tomol-based project
というエラーが発生したため、
sudo apt install -y build-essential
を実行してgccとg++を入れたところ、エラーが発生せずに
$ pip install -r requirements.txt
が実行できました。
（gccとg++を入れる際にもエラーが起きたため、sudo apt-get updateを実行した後に再びsudo apt install -y build-essentialを実行したところ、エラー無く入れられました）

gccとg++を入れて
$ pip install -r requirements.txt
を実行した際（これはエラーが起きたときの初回実行を１回目と数えた時、２回目に実行したものです）、モジュールの一部が正常にインストールできなかったのか、VCClientを起動する際にエラーが発生したため、求められたものを手動で入れました。（これは起動するときに入力するコマンドに--hubert_base_jp weights/model.pt \を書き加える前に行いました）入れたものは下の２つです。
・sudo apt-get install portaudio19-dev
を実行してportaudioを入れた。
・pip install sounddevice
を実行してsounddeviceを入れた。

**Comment by w-okada** [comment]
初回アクセス時に読み込まれる内部モジュールが読み込めてないように見えます。
ブラウザを一度閉じてから、URLにアクセスしてアップロードしてみるとどうでしょうか？

**Comment by maaakigai** [comment]
ブラウザを閉じてから、再びURLにアクセスして開いてみましたが、改善されませんでした。
何度か試してみましたが、開いた後にモデルをアップロードした際、「ちょっと問題が起きたみたいです」が出ることが多かったです。
下記は手順実行時のログです。

INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52824 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52827 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52831 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52825 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52830 - "POST /upload_file HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "POST /concat_uploaded_file HTTP/1.1" 200 OK
paramDict {'trans': 0, 'files': {'mmvcv13Config': '', 'mmvcv13Model': '', 'mmvcv15Config': '', 'mmvcv15Model': '', 'soVitsSvc40Config': '', 'soVitsSvc40Model': '', 'soVitsSvc40Cluster': '', 'soVitsSvc40v2Config': '', 'soVitsSvc40v2Model': '', 'soVitsSvc40v2Cluster': '', 'rvcModel': 'george.pth', 'rvcIndex': '', 'rvcFeature': '', 'ddspSvcModel': '', 'ddspSvcModelConfig': '', 'ddspSvcDiffusion': '', 'ddspSvcDiffusionConfig': ''}}
Traceback (most recent call last):
  File "/mnt/c/Users/miura/voice-changer/server/voice_changer/VoiceChanger.py", line 299, in loadModel
    return self.voiceChanger.loadModel(props)
AttributeError: 'NoneType' object has no attribute 'loadModel'

[Voice Changer] Model Load Error! Check your model is valid. 'NoneType' object has no attribute 'loadModel'
INFO:     172.19.176.1:52829 - "POST /load_model HTTP/1.1" 200 OK
INFO:     172.19.176.1:52829 - "GET /info HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/engineio/async_drivers/asgi.py", line 67, in __call__
    await self.other_asgi_app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/kakapo/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/c/Users/miura/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 57, in get_info
    info = self.voiceChangerManager.get_info()
  File "/mnt/c/Users/miura/voice-changer/server/voice_changer/VoiceChangerManager.py", line 30, in get_info
    info = self.voiceChanger.get_info()
  File "/mnt/c/Users/miura/voice-changer/server/voice_changer/VoiceChanger.py", line 308, in get_info
    data.update(self.voiceChanger.get_info())
AttributeError: 'NoneType' object has no attribute 'get_info'

**Comment by w-okada** [comment]
だいぶバージョンが上がっていますので、もうしわけありませんが最新版で再度試していただけないでしょうか？

**Comment by w-okada** [comment]
no res close
