### ISSUE TITLE
RVC V2 Models Are not compatible with MMVCServerSIO

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#233]
[Voice Changer] exception! loading inferencer Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 24, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 20, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 31, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 19, in loadModel
  File "torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 301, in loadModel
  File "voice_changer\RVC\RVC.py", line 84, in loadModel
  File "voice_changer\RVC\RVC.py", line 153, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 54, in createPipeline
UnboundLocalError: local variable 'inferencer' referenced before assignment

[Voice Changer] Model Load Error! Check your model is valid. local variable 'inferencer' referenced before assignment

i just need to know if v2 models work with the current version of the application

**Comment by w-okada** [comment]
No, not supported yet. I have plan to support by end of May. Please wait.

**Comment by w-okada** [comment]
I released new version which supports rvc v2. try it. 
And close.

**Comment by Furcornlover** [comment]
Una mierda

**Comment by ElhamAhmedian** [comment]
does not work for me. 
```
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 20, in loadModel
  File "torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).
```
