### ISSUE TITLE
Can it support real-time computing using cloud GPUs?

### ISSUE THREAD

**Issue by pz9k** [w-okada/voice-changer#235]
Can it support real-time computing using cloud GPUs and remote invocation (similar to calling another PC for real-time inference within a local area network)?

For example, I rented a cloud GPU server and placed the model to run on it. When using, I transmit the data stream of the local microphone to the server for inference through WebSocket and other forms. After the server completes the inference, it quickly sends the results back to the local area and outputs them to the speaker.

Is there a possibility of implementing this method?

**Comment by pz9k** [comment]
I tried to run this project on Ubuntu 20.4, but it was unsuccessful. It seems that a lot of models need to be downloaded, and the automatic download has failed. After I manually downloaded these models, the project still failed to start. It seems that this project cannot run on Ubuntu 20.4? May I ask if there is a complete compression package available for Linux, similar to the win/mac compression package on huggingface?

**Comment by pz9k** [comment]
Yes, I read the document and followed its steps. 
After I downloaded the model, I started it using the command with Conda, and it displayed: 

(vcclient-dev) root@aaa19c330:~/voice-changer/server# python3 MMVCServerSIO.py -p 18888 --https false  \
>   --content_vec_500 weights/checkpoint_best_legacy_500.pt \
>   --hubert_base weights/hubert_base.pt \
>   --hubert_soft weights/hubert-soft-0d54a1f4.pt \
>   --nsf_hifigan weights/nsf_hifigan/model  
    Booting PHASE :__main__
    Voice Changerを起動しています。
Traceback (most recent call last):
  File "/root/voice-changer/server/MMVCServerSIO.py", line 227, in <module>
    downloadWeight()
  File "/root/voice-changer/server/MMVCServerSIO.py", line 125, in downloadWeight
    if os.path.exists(hubert_base_jp) is False:
  File "/root/miniconda3/envs/vcclient-dev/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType.


Then I specified the missing model path, it displays:

(vcclient-dev) root@aaa19c330:~/voice-changer/server# python3 MMVCServerSIO.py -p 18888 --https false  \
>   --content_vec_500 weights/checkpoint_best_legacy_500.pt \
>   --hubert_base weights/hubert_base.pt \
>   --hubert_base_jp weights/hubert_base_jp.pt \
>   --hubert_soft weights/hubert-soft-0d54a1f4.pt \
>   --nsf_hifigan weights/nsf_hifigan/model
    Booting PHASE :__main__
    Voice Changerを起動しています。
Traceback (most recent call last):
  File "/root/voice-changer/server/MMVCServerSIO.py", line 229, in <module>
    os.makedirs(args.model_dir, exist_ok=True)
  File "/root/miniconda3/envs/vcclient-dev/lib/python3.10/os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "/root/miniconda3/envs/vcclient-dev/lib/python3.10/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by pz9k** [comment]
I don't know what this param is: "args.model_dir".
I try to modify the code to skip the steps associate with "downloadWeight()" and "args.model_dir", the project lunched, but got fatal errors in the html page.

**Comment by w-okada** [comment]
Oh,,, documentation is little bit old about parameter, I will update it.

**Comment by pz9k** [comment]
Thanks, the project lunched, but there seems to be some errors here:
"
Booting PHASE :__main__
Voice Changerを起動しています。
[Voice Changer] loading sample failed expected str, bytes or os.PathLike object, not NoneType
[Voice Changer] loading sample info error: expected str, bytes or os.PathLike object, not NoneType
    Internal_Port:6006
    protocol: HTTP
    -- ---- -- 
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/
    Booting PHASE :__mp_main__
    サーバプロセスを起動しています。
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
"

Is the "loading sample failed" matter?
I open the page via broswer, ssh shows:
"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  ......
  File "/root/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 70, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
  File "/root/voice-changer/server/voice_changer/VoiceChangerManager.py", line 45, in update_settings
    info = self.voiceChanger.update_settings(key, val)
  File "/root/voice-changer/server/voice_changer/VoiceChanger.py", line 339, in update_settings
    ret = self.voiceChanger.update_settings(key, val)
AttributeError: 'NoneType' object has no attribute 'update_settings'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  .......
  File "/root/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 70, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
  File "/root/voice-changer/server/voice_changer/VoiceChangerManager.py", line 45, in update_settings
    info = self.voiceChanger.update_settings(key, val)
  File "/root/voice-changer/server/voice_changer/VoiceChanger.py", line 344, in update_settings
    return self.get_info()
  File "/root/voice-changer/server/voice_changer/VoiceChanger.py", line 308, in get_info
    data.update(self.voiceChanger.get_info())
AttributeError: 'NoneType' object has no attribute 'get_info'
......
"


And then I uploaded model from local PC and clicked start button, the remote ssh shows:
"
VC PROCESSING!!!! EXCEPTION!!! 'NoneType' object has no attribute 'get_processing_sampling_rate'
Traceback (most recent call last):
  File "/root/voice-changer/server/voice_changer/VoiceChanger.py", line 401, in on_request_sola
    processing_sampling_rate = self.voiceChanger.get_processing_sampling_rate()
AttributeError: 'NoneType' object has no attribute 'get_processing_sampling_rate'
VC PROCESSING!!!! EXCEPTION!!! 'NoneType' object has no attribute 'get_processing_sampling_rate'
Traceback (most recent call last):
  File "/root/voice-changer/server/voice_changer/VoiceChanger.py", line 401, in on_request_sola
    processing_sampling_rate = self.voiceChanger.get_processing_sampling_rate()
AttributeError: 'NoneType' object has no attribute 'get_processing_sampling_rate'
.......
"

Broswer has nothing output but a alert:
"エラーが頻発しています。対象としているフレームワークのモデルがロードされているか確認してください。"

**Comment by pz9k** [comment]
I clone the new version of files, the error of  "loading sample failed"  has been fixed.
But the error of (AttributeError: 'NoneType' object has no attribute 'get_info') is still exists.
It seems the object of (MMVC_Rest->MMVC_Rest_FileUploader->voiceChangerManager->voiceChanger) is None,  I try to do something to fix it but finally failed.
