### ISSUE TITLE
AudioDeviceList.py error

### ISSUE THREAD

**Issue by willis** [w-okada/voice-changer#240]
no start. 
error info:

G:\soft\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir models     --samples samples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
++    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
Process p:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "MMVCServerSIO.py", line 182, in localServer
  File "uvicorn\main.py", line 569, in run
  File "uvicorn\server.py", line 60, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "uvicorn\server.py", line 67, in serve
  File "uvicorn\config.py", line 477, in load
  File "uvicorn\importer.py", line 21, in import_from_string
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "MMVCServerSIO.py", line 211, in <module>
  File "voice_changer\VoiceChangerManager.py", line 17, in get_instance
  File "voice_changer\VoiceChanger.py", line 237, in __init__
  File "voice_changer\Local\AudioDeviceList.py", line 17, in list_audio_device
  File "sounddevice.py", line 564, in query_devices
  File "sounddevice.py", line 564, in <genexpr>
  File "sounddevice.py", line 578, in query_devices
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
Preparing your application. Please wait...

search file AudioDeviceList.py not found.

**Comment by w-okada** [comment]
maybe this is related?

https://github.com/spatialaudio/python-sounddevice/issues/72

**Comment by willis** [comment]
I'm running with the client MMVCServerSIO .exe, not anaconda environment, so I can't find sounddevice.py files

**Comment by w-okada** [comment]
The version has been updated a lot already, so I cannot apologize enough, but could you please try it again with the newest version?

**Comment by w-okada** [comment]
no res close
