### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by john012343210** [w-okada/voice-changer#245]
C:\Users\Username\Downloads\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.2\MMVCServerSIO>MMVCServerSIO.exe
    Booting PHASE :__main__
    Voice Changerを起動しています。
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 225, in <module>
  File "MMVCServerSIO.py", line 116, in downloadWeight
  File "genericpath.py", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[45404] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

**Comment by szriru** [comment]
i got the same error message in wsl ubuntu
```bash
(vcclient-dev) me:~/voice-changer/server$ python3 MMVCServerSIO.py -p 18888 --https true
    Booting PHASE :__main__
    Voice Changerを起動しています。
Traceback (most recent call last):
  File "/home/me/voice-changer/server/MMVCServerSIO.py", line 225, in <module>
    downloadWeight()
  File "/home/me/voice-changer/server/MMVCServerSIO.py", line 116, in downloadWeight
    if os.path.exists(hubert_base) is False:
  File "/home/me/miniconda3/envs/vcclient-dev/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by szriru** [comment]
it turned out to be that my launch line didn't have specific arguments.
i was too lazy to add args in command line.
In windows shift+right click can paste multiple line to terminal.
```bash
python3 MMVCServerSIO.py -p 18888 --https true \
 --content_vec_500 pretrain/checkpoint_best_legacy_500.pt  \
 --hubert_base pretrain/hubert_base.pt \
 --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt \
 --nsf_hifigan pretrain/nsf_hifigan/model \
 --hubert_base_jp pretrain/rinna_hubert_base_jp.pt \
 --model_dir models
```
