### ISSUE TITLE
'HParams' object has no attribute 'c_dim'

### ISSUE THREAD

**Issue by 7est** [w-okada/voice-changer#248]
When I try to upload my sovits4.0v2 model, it shows the error like below:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 78, in __call__
  File "engineio\async_drivers\asgi.py", line 67, in __call__
  File "fastapi\applications.py", line 270, in __call__
  File "starlette\applications.py", line 124, in __call__
  File "starlette\middleware\errors.py", line 184, in __call__
  File "starlette\middleware\errors.py", line 162, in __call__
  File "starlette\middleware\cors.py", line 92, in __call__
  File "starlette\middleware\cors.py", line 147, in simple_response
  File "starlette\middleware\exceptions.py", line 79, in __call__
  File "starlette\middleware\exceptions.py", line 68, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 21, in __call__
  File "fastapi\middleware\asyncexitstack.py", line 18, in __call__
  File "starlette\routing.py", line 706, in __call__
  File "starlette\routing.py", line 276, in handle
  File "starlette\routing.py", line 66, in app
  File "fastapi\routing.py", line 235, in app
  File "fastapi\routing.py", line 163, in run_endpoint_function
  File "starlette\concurrency.py", line 41, in run_in_threadpool
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "restapi\MMVC_Rest_Fileuploader.py", line 69, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 14, in loadModel
  File "voice_changer\VoiceChanger.py", line 84, in loadModel
  File "voice_changer\SoVitsSvc40v2\SoVitsSvc40v2.py", line 109, in loadModel
  File "F:\MMVCServerSIO\MMVCServerSIOBak\so-vits-svc-40v2\models.py", line 857, in __init__
    hps.data.c_dim,
AttributeError: 'HParams' object has no attribute 'c_dim'

**Comment by w-okada** [comment]
The most likely cause is using the wrong file. Please chekc.

**Comment by w-okada** [comment]
OK? close.

**Comment by Piripara** [comment]
i meet the same problem,do you know how to import models correctly?

**Comment by 7est** [comment]
Use the so-vits-svc-40v2 that [voice-changer](https://github.com/w-okada/voice-changer) provides to train the model again.
