### ISSUE TITLE
RVC model load error

### ISSUE THREAD

**Issue by Misakaou** [w-okada/voice-changer#255]
## RVC model load error

Hi, I have added a RVC model trained by myself but got this error, what happened please?
It told me that the model is not valid but in RVC-WebUI it worked.

## logs

```text
[Voice Changer] update configuration: dstId 1
[Voice Changer] update configuration: crossFadeEndRate 1
[Voice Changer] update configuration: crossFadeOverlapSize 1024
[Voice Changer] update configuration: f0Factor 1
[Voice Changer] update configuration: serverInputAudioSampleRate 48000
[Voice Changer] update configuration: serverInputAudioBufferSize 24576
[Voice Changer] update configuration: serverOutputAudioBufferSize 24576
[Voice Changer] update configuration: serverInputDeviceId -1
[Voice Changer] update configuration: serverOutputDeviceId -1
[Voice Changer] update configuration: modelSamplingRate 48000
[Voice Changer] update configuration: extraConvertSize 32768
[Voice Changer] update configuration: useDiff 1
[Voice Changer] update configuration: diffSpkId 1
[Voice Changer] update configuration: diffAcc 20
[Voice Changer] update configuration: kStep 120
[Voice Changer] update configuration: onnxExecutionProvider CPUExecutionProvider
[Voice Changer] update configuration: f0Detector harvest
[Voice Changer] update configuration: serverReadChunkSize 256
[Voice Changer] update configuration: diffMethod dpm-solver
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: silenceFront 1
[Voice Changer] update configuration: framework PyTorch
[Voice Changer] update configuration: inputSampleRate 48000
[Voice Changer] update configuration: serverOutputAudioSampleRate 48000
[Voice Changer] update configuration: threshold -45
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 299, in loadModel
AttributeError: 'NoneType' object has no attribute 'loadModel'

[Voice Changer] Model Load Error! Check your model is valid. 'NoneType' object has no attribute 'loadModel'
[23788:0525/140032.855:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 299, in loadModel
AttributeError: 'NoneType' object has no attribute 'loadModel'
```

If you need the model, I will upload it.

**Comment by w-okada** [comment]
Please full log.

**Comment by Misakaou** [comment]
I tried to re-download voice-changer and it works fine. 
Thanks!
