### ISSUE TITLE
VC PROCESSING!!!! EXCEPTION!!! Model requires 6 inputs. Input Feed contains 5

### ISSUE THREAD

**Issue by pengbin897** [w-okada/voice-changer#268]
VC PROCESSING!!!! EXCEPTION!!! Model requires 6 inputs. Input Feed contains 5
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 473, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 342, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 178, in exec
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 57, in infer
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 196, in run
ValueError: Model requires 6 inputs. Input Feed contains 5
![微信截图_20230530154116](https://github.com/w-okada/voice-changer/assets/12709670/1c126b4c-adf8-4467-b90d-a4cbd72aabd3)
Start is OK, but it doesn't work and has this exception on terminal. attachment is snapshot of client interface

**Comment by pengbin897** [comment]
Well... so be it

**Comment by Keith-Hon** [comment]
> If the ONNX model is generated from the RVC official web-UI, this app cannot support it due to licensing issues. Please use the original PyTorch model instead.

What is the licensing issue about?
