### ISSUE TITLE
Apple Sillicon macOS にてPythonの環境構築した上で実行すると、クライアントから設定する際にエラーが出る

### ISSUE THREAD

**Issue by oniatsu** [w-okada/voice-changer#272]
Apple Sillicon の macOS にてPythonの環境構築した上で、RVCでの変換をコマンドラインにて実行しようとしています。

環境構築手順に従って実行すると、macOS では実行ファイル（.app）での実行前提になっているためと理解しているのですが、
sys.path で Contents/MacOS が含まれていない点と、sys._MEIPASS がない点のエラーが出ます。
そのため以下の2点を変更しました。誤った理解をしていれば指摘ください。

```diff
--- a/server/voice_changer/RVC/RVC.py
+++ b/server/voice_changer/RVC/RVC.py
@@ -13,14 +13,16 @@ from voice_changer.RVC.SampleDownloader import downloadModelFiles
 sys.argv = ["MMVCServerSIO.py"]

 if sys.platform.startswith("darwin"):
-    baseDir = [x for x in sys.path if x.endswith("Contents/MacOS")]
-    if len(baseDir) != 1:
-        print("baseDir should be only one ", baseDir)
-        sys.exit()
-    modulePath = os.path.join(baseDir[0], "RVC")
-    sys.path.append(modulePath)
+    sys.path.append("RVC")
 else:
     sys.path.append("RVC")
```

```diff
--- a/server/restapi/MMVC_Rest.py
+++ b/server/restapi/MMVC_Rest.py
@@ -72,14 +72,17 @@ class MMVC_Rest:
             )

             if sys.platform.startswith("darwin"):
-                p1 = os.path.dirname(sys._MEIPASS)
-                p2 = os.path.dirname(p1)
-                p3 = os.path.dirname(p2)
-                model_dir = os.path.join(p3, "models")
-                print("mac model_dir:", model_dir)
                 app_fastapi.mount(
-                    "/models", StaticFiles(directory=model_dir), name="static"
+                    "/models", StaticFiles(directory="models"), name="static"
                 )
             else:
                 app_fastapi.mount(
                     "/models", StaticFiles(directory="models"), name="static"
```

そして、この変更の上でコマンドラインから起動することはできるのですが、ブラウザからVCをRVCに指定すると、クライアントではエラーとなり、サーバでは以下のようなエラーが出ます。
かなり多くのエラーが出るため、一部抜粋しています。

その中でも以下が主なエラー分だと考えています。
voiceChanger が None になったままになってしまっているためと思うのですが、対処法が分かりませんでした。
```
  File "/Users/person/dev/vc/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 73, in post_update_settings
    info = self./oiceChangerManager.update_settings(key, val)
  File "/Users/person/dev/vc/voice-changer/server/voice_changer/VoiceChangerManager.py", line 48, in update_settings
    info["status"] = "OK"
TypeError: 'NoneType' object does not support item assignment
```

対処法があれば指摘ください。よろしくお願いします。

エラー文
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/engineio/async_drivers/asgi.py", line 67, in __call__
    await self.other_asgi_app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/person/dev/vc/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 73, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
  File "/Users/person/dev/vc/voice-changer/server/voice_changer/VoiceChangerManager.py", line 46, in update_settings
    info["status"] = "OK"
TypeError: 'NoneType' object does not support item assignment
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/engineio/async_drivers/asgi.py", line 67, in __call__
    await self.other_asgi_app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/person/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/person/dev/vc/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 73, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
  File "/Users/person/dev/vc/voice-changer/server/voice_changer/VoiceChangerManager.py", line 46, in update_settings
    info["status"] = "OK"
TypeError: 'NoneType' object does not support item assignment
```

**Comment by w-okada** [comment]
any update?

**Comment by oniatsu** [comment]
No update yet.

**Comment by w-okada** [comment]
Have you seen https://github.com/w-okada/voice-changer/issues/339 ?

**Comment by oniatsu** [comment]
It worked!

I need these changes to deploy and use.

- Install arm64 version pyworld manually before running `pip install -y requirements.txt`.
    - `ARCHFLAGS="-arch arm64" pip install pyworld==0.3.3 --compile --no-cache-dir --force-reinstall`
- Add check whether using [_MEIPASS](https://github.com/w-okada/voice-changer/blob/master/server/restapi/MMVC_Rest.py#L79).
```diff
+             if sys.platform.startswith("darwin") and hasattr(sys, "_MEIPASS"):
-             if sys.platform.startswith("darwin"):
```
- Use `PYTORCH_ENABLE_MPS_FALLBACK=1` to start the server.
```sh
PYTORCH_ENABLE_MPS_FALLBACK=1 python3 MMVCServerSIO.py -p 18888 --https false \
    --content_vec_500 pretrain/checkpoint_best_legacy_500.pt  \
    --content_vec_500_onnx pretrain/content_vec_500.onnx \
    --content_vec_500_onnx_on true \
    --hubert_base pretrain/hubert_base.pt \
    --hubert_base_jp pretrain/rinna_hubert_base_jp.pt \
    --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt \
    --nsf_hifigan pretrain/nsf_hifigan/model \
    --crepe_onnx_full pretrain/crepe_onnx_full.onnx \
    --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx \
    --model_dir model_dir \
    --samples samples.json
```

I will write the my steps to run the server for the other people to corabollate this project.

**Comment by oniatsu** [comment]
I wrote my detailed steps on the similar issue. https://github.com/w-okada/voice-changer/issues/339#issuecomment-1636970207
