### ISSUE TITLE
RVC is not available in v.1.5.3.4

### ISSUE THREAD

**Issue by pz9k** [w-okada/voice-changer#281]
Hi, I got some problems in v.1.5.3.4.
After I select RVC, the "Switch Model" comboBox did not show numbers. Error code:
```
ModelSlot.__init__() got an unexpected keyword argument 'rvcIndexDownload'
Traceback (most recent call last):
  File "/root/voice-changer/server/voice_changer/VoiceChanger.py", line 310, in switchModelType
    self.voiceChanger = RVC(self.params)
  File "/root/voice-changer/server/voice_changer/RVC/RVC.py", line 69, in __init__
    self.loadSlots()
  File "/root/voice-changer/server/voice_changer/RVC/RVC.py", line 186, in loadSlots
    slotInfo = ModelSlot(**jsonDict)
TypeError: ModelSlot.__init__() got an unexpected keyword argument 'rvcIndexDownload'

Exception ignored in: <function RVC.__del__ at 0x7f10bc86c550>
Traceback (most recent call last):
  File "/root/voice-changer/server/voice_changer/RVC/RVC.py", line 375, in __del__
    del self.pipeline
AttributeError: pipeline
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
```
![BANF1UT5%C0FOFS4P87740Q](https://github.com/w-okada/voice-changer/assets/128797321/f054e081-b7c9-4a6e-af34-84c7f438f9c9)

Then I try to upload model, got error code:
```
[Voice Changer] Voice Changer is not selected.
Traceback (most recent call last):
  File "/root/voice-changer/server/voice_changer/VoiceChanger.py", line 329, in loadModel
    raise RuntimeError("Voice Changer is not selected.")
RuntimeError: Voice Changer is not selected.

[Voice Changer] Model Load Error! Check your model is valid. Voice Changer is not selected.
```
![VYWC) 26~8PH(@H0H6 7KJR](https://github.com/w-okada/voice-changer/assets/128797321/39196c3a-5501-4502-8dbe-51776c395b13)
![Q8PQ6EO~EXX61R@0Z$HA{W5](https://github.com/w-okada/voice-changer/assets/128797321/fe4c5339-b915-4a72-907e-5feee6f8e178)

**Comment by w-okada** [comment]
try clear settting

**Comment by pz9k** [comment]
it works now, thanks
