### ISSUE TITLE
Error when trying to run "start_http.bat"

### ISSUE THREAD

**Issue by Dasher-The-Viral** [w-okada/voice-changer#283]
I followed the readme but every time I try to launch the program all I get is this.

MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir model_dir     --samples samples.json
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "voice_changer\RVC\SampleDownloader.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "voice_changer\RVC\ModelSlotGenerator.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "REDACTED:\Redacted\MMVCServerSIO\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.
[2480] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

**Comment by KarinMiku** [comment]
i think it is your antivirus.. mine stopped that service too due to suspicious actions or something like that.. seems like the latest version changed something

**Comment by Dasher-The-Viral** [comment]
Added a folder exclusion in my antivirus and sadly it still doesn't work.

**Comment by w-okada** [comment]
The error message seems to be indicating an issue with the cuda. I'm not sure about this but have you made sure that the driver is installed properly?

**Comment by Dasher-The-Viral** [comment]
I tried re-installing the driver but sadly nothing has changed... :/

**Comment by VisualK** [comment]
I ran into this issue and tried many solutions. None of them worked. But I figured out how to fix it. 
The problem was I unpacked the new version of MMVCServerSIO on top of the old folder. It tried to use the old libraries that it had downloaded to that folder. When I unpacked to a fresh new folder, it redownloaded the libraries and the error went away.

Maybe relevant: nvcc --version listed my CUDA version as 11.3. Turns out I had 11.3 AND 11.8 installed, so I uninstalled 11.3. I also reinstalled torch for the entire PC, but I don't think that's relevant because MMVCServerSIO has Torch in its own folder.

**Comment by w-okada** [comment]
no update close

**Comment by maria2321a** [comment]
I can't even open the file I click and it show up for less than 1 sec and closed i spam clicking it try to make it open it won't open and when i try to use chat cgt nothing was working and I'm using window 10 like wth.... security know realtime voice changer and maybe tryna taken down..

**Comment by maria2321a** [comment]
![image](https://github.com/w-okada/voice-changer/assets/154034451/4bb8ea16-c4df-4dcb-9e64-b07336161df0)

**Comment by maria2321a** [comment]
This is the longest time it stay and it closed again and then when i try to open again it close than less than 1 sec

**Comment by burner-208** [comment]
> no update close

hello, is there a way to ensure i have fully removed and uninstalled everything from this program from my mac?

**Comment by KuukoShan** [comment]
Check the place where you downloaded and decompressed the folder. Is the folder still there? If still, delete the folder. If there is no folder then there isn't any traces remaining. This software have no installation, it simply decompress into a folder and, once you run it for the first time, it downloads some necessary resources inside of the subfolders within the same main folder. Deleting the main folder deletes everything.
