### ISSUE TITLE
Issue found In Voice Changer 

### ISSUE THREAD

**Issue by tomas122727** [w-okada/voice-changer#290]
[Voice Changer] VC PROCESSING EXCEPTION!!! expected scalar type Double but found Float
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 472, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 367, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 230, in exec
  File "voice_changer\RVC\pipeline\Pipeline.py", line 216, in exec
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 39, in infer
  File "D:\TTS-so-VITS\MMVCServerSIO\RVC\infer_pack\models.py", line 636, in infer
    m_p, logs_p, x_mask = self.enc_p(phone, pitch, phone_lengths)
  File "torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(args, **kwargs)
  File "D:\TTS-so-VITS\MMVCServerSIO\RVC\infer_pack\models.py", line 50, in forward
    x = self.emb_phone(phone) + self.emb_pitch(pitch)
  File "torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(args, **kwargs)
  File "torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Double but found Float 

How To Fix This error

**Comment by w-okada** [comment]
tell me version of client.
and if not use the latest version, use the latest one.

**Comment by tomas122727** [comment]
<html>
<body>


win | ONNX(cpu,cuda), PyTorch(cpu,cuda) | normal *1 | MMVC v.1.5.x, MMVC v.1.3.x, so-vits-svc 4.0, RVC, DDSP-SVC | 3243MB
-- | -- | -- | -- | --



</body>
</html>win	ONNX(cpu,cuda), PyTorch(cpu,cuda)	[normal](https://drive.google.com/uc?id=1s_bWt9EZlVhNSgamz38SOL8yI0nTz2PM&export=download) *1	MMVC v.1.5.x, MMVC v.1.3.x, so-vits-svc 4.0, RVC, DDSP-SVC	3243MB this one

**Comment by tomas122727** [comment]
V 1.5.3.4 b

**Comment by tomas122727** [comment]
onnx GPU cuda

**Comment by w-okada** [comment]
I apologize for the inconvenience,  but please try v 1.5.3.4c.

**Comment by tomas122727** [comment]
where i download that ?

**Comment by w-okada** [comment]
here.

![image](https://github.com/w-okada/voice-changer/assets/48346627/f0448878-c309-43d1-b899-321c87a98aa0)

 If you cannnot download from google drive, please use hugging face.

**Comment by tomas122727** [comment]
im not on mac

**Comment by w-okada** [comment]
??
Win is second line.

**Comment by tomas122727** [comment]
dont worry i got it i will wait till i can tell if its working for my friend

**Comment by tomas122727** [comment]
its worked thank you

**Comment by w-okada** [comment]
close
