### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Syobe** [w-okada/voice-changer#291]
[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 472, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 367, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 207, in exec
TypeError: 'NoneType' object is not subscriptable

v.1.5.3.4b onnx-directmlです
none pitchモデルの場合にのみ該当エラーが発生します

**Comment by w-okada** [comment]
ありがとうございます。
問題再現しました。（directmlだけではなくcudaも同じ現象でます。）
修正版を今日明日中に出します。

また、DirectML試用と動作報告大変助かります。
本件とは直接関係しませんが、GPUの型番を教えていただけるとありがたいです。

**Comment by w-okada** [comment]
v.1.5.3.4cをリリースしました。

**Comment by Syobe** [comment]
確認しました！
pthファイルでは正常に動作しますが
onnxファイルではまた別のエラーが発生します

[Voice Changer] VC PROCESSING EXCEPTION!!! [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float16)) , expected: (tensor(float))
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 472, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 367, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 220, in exec
  File "voice_changer\RVC\inferencer\OnnxRVCInferencerNono.py", line 23, in infer
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float16)) , expected: (tensor(float))

使用中のGPUはRX6700XTです

**Comment by w-okada** [comment]
おぉー、ありがとうございます。AMDのhalf precision関連でバグっているのか。。。
むぅ、、、ちょっと見てみますが、これはAMDだけの問題かもしれないので実機触りながら出ないとわからないかもなぁ、、

**Comment by w-okada** [comment]
ところで、onnx nof0の時だけでしょうか？onnx f0の場合は動きますでしょうか？

**Comment by Syobe** [comment]
はい、今確認してみたんですが
onnx f0の場合はGPU使用量も上がり、正常に動作することを確認しました！

**Comment by w-okada** [comment]
どうもAMDの問題ではなく、調査の結果、他の環境でも発生するバグだったようです。
対策版をアップロードしたので、お手数ですがご確認いただけないでしょうか。
v.1.5.3.4dです。

**Comment by Syobe** [comment]
確認しました！
問題なく機能し、以前よりcpu使用量が減り、gpu使用量も正常に上がります。
ありがとうございました！

**Comment by w-okada** [comment]
ご確認ありがとうございます！！念願のAMD対応できました！
あとは、ほかの人にも使ってもらって実績を積んでいきたいところですね。

いったんこのissueはクローズします。
