### ISSUE TITLE
app does not work well under a radion GPU

### ISSUE THREAD

**Issue by marrie** [w-okada/voice-changer#303]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.4d.zip

### OS

Windows 11 22H2 (AMD64) build 22621.1702

### GPU

AMD Radeon RX 6800 XT

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Voice Changer type

rvc

### Model type

unknown

### Situation

I tried to fill out what I could. Basically, I have a radion GPU the app won't work on. The app works for about 30 seconds under the one second buffer in CPU mode but after a while it cuts out and the delay increases to about 10 seconds which distracts me. Is there a way to make this thing run on a radion GPU? I have a Rison processer running at I think 3.8 ghz. and my radion has twenty-four gigs of VRam. I wanted to try and use that however I didn't know how to have it try and use said internal card. If you need me to try and troubleshoot I can, know I cannot code. Thanks. Is there any form of a log I can upload? Thanks.

**Comment by w-okada** [comment]
Try directML version.
This is an experimental implementation, but we have received several positive reports that it works well.

![image](https://github.com/w-okada/voice-changer/assets/48346627/7dd9de4d-8445-4396-b642-3bbe1921f7d2)

**Comment by marrie** [comment]
I will try and do that.  I assume there are debugging logs I can attach if necessary? Also does your software come with a trainer? I want to test that as well. Thanks and will continue to test

**Comment by w-okada** [comment]
Close.

**Comment by marrie** [comment]
Hello. It is still cutting out even at the default settings. I cleared and started from scratch. I am getting this as translated into English.

 

I am getting frequent errors. Check if the model for the framework you are targeting is loaded.

 

I’m also getting errors when I start the client after loading the voice and clicking “upload.”  Here are the last 10. 

Is there a log somewhere I can attach to this report? The app works for about 2 seccinds then I get  this flood of errors. I would upload my dx diag information however that contains private info such as serial numbers, I think. I can if needed attach the voice I’m using. It works on the intel systems fine. I’ve heard it. When I record though it does not cut out. I hope this block of errors is not too big to send through email. Thanks.

 

 

 

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[Voice Changer] VC PROCESSING EXCEPTION!!! 'NoneType' object has no attribute 'write'

Traceback (most recent call last):

  File "voice_changer\VoiceChanger.py", line 553, in on_request_sola

  File "voice_changer\IORecorder.py", line 28, in writeInput

  File "wave.py", line 437, in writeframes

  File "wave.py", line 432, in writeframesraw

AttributeError: 'NoneType' object has no attribute 'write'

 

[2023-06-10 09:33:07] connet sid : FeEGmbxNR-2v3-JhAAAP

[2023-06-10 09:33:07] connet sid : EooqVx2xe6qQ9Sg0AAAR

[2023-06-10 09:33:53] connet sid : TooyFsyMTGg0KeXoAAAT
