### ISSUE TITLE
AttributeError: 'SoVitsSvc40' object has no attribute 'hubert_model'

### ISSUE THREAD

**Issue by kodokawa** [w-okada/voice-changer#306]
### Issue Type

Bug Report

### vc client version number

sovits svc 40

### OS

windows 10

### GPU

none

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

sovits svc 40

### Model type

40

### Situation

error
[Voice Changer] VC PROCESSING EXCEPTION!!! 'SoVitsSvc40' object has no attribute 'hubert_model'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 464, in on_request_sola
  File "voice_changer\SoVitsSvc40\SoVitsSvc40.py", line 363, in generate_input
  File "voice_changer\SoVitsSvc40\SoVitsSvc40.py", line 289, in get_unit_f0
AttributeError: 'SoVitsSvc40' object has no attribute 'hubert_model'

**Comment by w-okada** [comment]
please more info
