### ISSUE TITLE
How to restart the installation process? "Voice Changer is not selected"

### ISSUE THREAD

**Issue by Hitazaki** [w-okada/voice-changer#346]
### Issue Type

Bug Report

### vc client version number

1.5.3.5

### OS

Windows 10

### GPU

NVidia GeForce GTX 1050Ti (4Gb)

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

ONNXgpu-cuda

### Situation

Hey, I was wondering if there was a way to restart the whole installation process?

Because apparently it seemed like mine crashed due to my stupidly slow internet and I have access to no models that came with the software, nor can I add mine, when I press the Edit button I get just the "Model Slot Configuration" banner and nothing else at all.

As well as some parameters that I cannot change like Protect or anything in the Crossfade section because apparently I don't have a "Voice Changer selected".

**So pretty much I'm looking for a way to make a clean installation, do I just need to delete everything and redownload the whole package or there's a different way?**

Also I get an error in the cmd prompt that is detailed lower.

Thank you in advance.

```
(node:15968) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
[2023-06-26 00:23:39] connet sid : _qvlSb-Q2TnV9TUVAAAC
[2023-06-26 00:23:39] connet sid : s-GL75xeQAfpbn19AAAD
2023-06-26 00:23:41 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-06-26 00:23:41 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-06-26 00:23:41 | INFO | faiss.loader | Loading faiss.
2023-06-26 00:23:42 | INFO | faiss.loader | Successfully loaded faiss.
[Voice Changer] RVC initialization:  VoiceChangerParams(model_dir='model_dir', content_vec_500='pretrain/checkpoint_best_legacy_500.pt', content_vec_500_onnx='pretrain/checkpoint_best_legacy_500.onnx', content_vec_500_onnx_on=0, hubert_base='pretrain/hubert_base.pt', hubert_base_jp='pretrain/rinna_hubert_base_jp.pt', hubert_soft='pretrain/hubert/hubert-soft-0d54a1f4.pt', nsf_hifigan='pretrain/nsf_hifigan/model', rvc_sample_mode='production')
[Voice Changer] Prepare Model of slot: 0
[Voice Changer] exception! loading inferencer [Errno 2] No such file or directory: 'model_dir\\rvc\\0\\tokina_shigure_v2_40k_e100_simple.onnx'
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 19, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 23, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 18, in loadModel
  File "torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model_dir\\rvc\\0\\tokina_shigure_v2_40k_e100_simple.onnx'
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\rvc\0\added_IVF2736_Flat_nprobe_1_v2.index.bin
[Voice Changer] load index failed. Use no index.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 71, in _loadIndex
  File "faiss\swigfaiss.py", line 9795, in read_index
RuntimeError: Error in struct faiss::InvertedLists *__cdecl faiss::read_InvertedLists(struct faiss::IOReader *,int) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\index_read.cpp:211: Error: 'ret == (n * ails->code_size)' failed: read error in model_dir\rvc\0\added_IVF2736_Flat_nprobe_1_v2.index.bin: 6709 != 141312 (No error)
local variable 'inferencer' referenced before assignment
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 312, in switchModelType
  File "voice_changer\RVC\RVC.py", line 92, in __init__
  File "voice_changer\RVC\RVC.py", line 249, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 46, in createPipeline
UnboundLocalError: local variable 'inferencer' referenced before assignment

[Voice Changer] update configuration: dstId 1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: crossFadeEndRate 1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: crossFadeOverlapSize 1024
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: framework PyTorch
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: onnxExecutionProvider CPUExecutionProvider
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: f0Factor 1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: f0Detector harvest
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverInputAudioSampleRate 48000
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverOutputAudioSampleRate 48000
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverInputAudioBufferSize 24576
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverOutputAudioBufferSize 24576
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverInputDeviceId -1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverOutputDeviceId -1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverReadChunkSize 256
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: serverInputAudioGain 1
[Voice Changer] Voice Changer is not selected.
Exception ignored in: <function RVC.__del__ at 0x000001AD50E963B0>
Traceback (most recent call last):
  File "voice_changer\RVC\RVC.py", line 406, in __del__
[Voice Changer] update configuration: serverOutputAudioGain 1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: tran 10
[Voice Changer] Voice Changer is not selected.
AttributeError: pipeline
[Voice Changer] update configuration: extraConvertSize 4096
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: protect 0.5
[Voice Changer] update configuration: modelSamplingRate 48000
[Voice Changer] Voice Changer is not selected.
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: silenceFront 1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: useDiff 1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: diffMethod dpm-solver
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: diffAcc 20
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: diffSpkId 1
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: kStep 120
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: threshold -45
[Voice Changer] Voice Changer is not selected.
[Voice Changer] update configuration: inputSampleRate 48000
[Voice Changer] Voice Changer is not selected.

```

**Comment by w-okada** [comment]
not recommended but, you can delete `model_dir` to re-download sample models.

**Comment by w-okada** [comment]
no res close

**Comment by kenblock12** [comment]
how to uninstall a voice changer? , because this program not detect in windows apps

**Comment by w-okada** [comment]
just delete folder
