### ISSUE TITLE
how do I fix this? i'm not good with this stuff

### ISSUE THREAD

**Issue by Billy2000k** [w-okada/voice-changer#352]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.6

### OS

Windows 10

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Preparing your application. Please wait...
(node:6504) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
Preparing your application. Please wait...
(node:6504) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
Process p:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "MMVCServerSIO.py", line 97, in localServer
  File "uvicorn\main.py", line 578, in run
  File "uvicorn\server.py", line 61, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "uvicorn\server.py", line 68, in serve
  File "uvicorn\config.py", line 473, in load
  File "uvicorn\importer.py", line 21, in import_from_string
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "MMVCServerSIO.py", line 110, in <module>
  File "restapi\MMVC_Rest.py", line 93, in get_instance
  File "starlette\staticfiles.py", line 57, in __init__
RuntimeError: Directory 'model_dir' does not exist
Preparing your application. Please wait...
(node:6504) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...

**Comment by gitihobo** [comment]
same is happening

**Comment by bip0larbear** [comment]
same here ^

**Comment by w-okada** [comment]
show more log.

**Comment by Billy2000k** [comment]
Booting PHASE :__main__
    Voice Changerを起動しています。
    RVC用のモデルファイルのダウンロードに失敗しました。
    failed to download weight for rvc
[Errno 2] No such file or directory: 'samples_0003_t2.json'
[Errno 2] No such file or directory: 'samples_0003_o2.json'
[Voice Changer] loading sample failed [Errno 2] No such file or directory: 'samples_0003_t2.json'
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] Web Server Launch Exception Directory 'model_dir' does not exist
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

**Comment by Billy2000k** [comment]
that's the entire thing

**Comment by w-okada** [comment]
> RVC用のモデルファイルのダウンロードに失敗しました。
you failed to download the required data.

same this.
https://github.com/w-okada/voice-changer/issues/379
