### ISSUE TITLE
RVC导出的onnx模型在VC（voice-changer）中无法使用，但pth可以

### ISSUE THREAD

**Issue by hpx502766238** [w-okada/voice-changer#381]
### Issue Type

Bug Report, Question

### vc client version number

1.5.3.7

### OS

Windows11

### GPU

NVDIA RTX 3060 、AMD 5800H Radeon Graphics

### Clear setting

yes

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

pyTorch,ONNX

### Situation

RVC导出的onnx模型在voice-changer)中无法使用，报错，但VC直接使用pth又能够推理，但如果使用pth，又不能通过DirectML利用核显的算力了（游戏党需要。测试用VC自带的onnx示例模型是可以使用核显推理的）。下面是VC报错内容：
[Voice Changer] VC PROCESSING EXCEPTION!!! Required inputs (['phone', 'phone_lengths', 'ds', 'rnd']) are missing from input feed (['feats', 'p_len', 'pitch', 'pitchf', 'sid']).
Traceback (most recent call last):
File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
File "voice_changer\RVC\RVC.py", line 157, in inference
File "voice_changer\RVC\pipeline\Pipeline.py", line 209, in exec
File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 57, in infer
File "onnxruntime\capi\onnxruntime_inference_collection.py", line 213, in run
File "onnxruntime\capi\onnxruntime_inference_collection.py", line 195, in _validate_input
ValueError: Required inputs (['phone', 'phone_lengths', 'ds', 'rnd']) are missing from input feed (['feats', 'p_len', 'pitch', 'pitchf', 'sid']).

**Comment by w-okada** [comment]
RVC本家のONNXはライセンス上使用が難しいです。本クライアントを使用してONNXを出力してください。

**Comment by w-okada** [comment]
no res close
