### ISSUE TITLE
more...Advanced setting > RVC Quality , if set high, cmd show "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by minimoonleaf** [w-okada/voice-changer#433]
### Issue Type

Question

### vc client version number

v.1.5.3.8a

### OS

Windows 10

### GPU

RTX3090

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

f0

### Situation

more...Advanced setting > RVC Quality , if set high, cmd show "IndexError: tuple index out of range"
CMD:
...
[Voice Changer] update configuration: rvcQuality 1
[Voice Changer][RVC]: update_settings rvcQuality 1
[Voice Changer] VC PROCESSING EXCEPTION!!! tuple index out of range
Traceback (most recent call last):
File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
File "voice_changer\RVC\RVC.py", line 175, in inference
File "voice_changer\RVC\pipeline\Pipeline.py", line 106, in exec
IndexError: tuple index out of range[Voice Changer] update configuration: rvcQuality 1
[Voice Changer][RVC]: update_settings rvcQuality 1
[Voice Changer] VC PROCESSING EXCEPTION!!! tuple index out of range
Traceback (most recent call last):
File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
File "voice_changer\RVC\RVC.py", line 175, in inference
File "voice_changer\RVC\pipeline\Pipeline.py", line 106, in exec
IndexError: tuple index out of range
...

**Comment by w-okada** [comment]
use the latest version

**Comment by w-okada** [comment]
no res close
