### ISSUE TITLE
frequent error occur please check if the model of the framework being targeted is loaded

### ISSUE THREAD

**Issue by lMINIMALl** [w-okada/voice-changer#447]
### Issue Type

Others

### vc client version number

1.5.3.8.a

### OS

Windows 10

### GPU

gt 720 2 gb

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

onnx

### Situation

 ![aiiCF34sNBE](https://github.com/w-okada/voice-changer/assets/112943327/a2563f24-195a-4a22-8f15-983ea139df56)
 logs:
 
 --samples samples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

Preparing your application. Please wait...
(node:17464) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
torch\cuda\__init__.py:152: UserWarning:
    Found GPU0 GeForce GT 720 which is of cuda capability 3.5.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is 3.7.

  warnings.warn(old_gpu_warn % (d, name, major, minor, min_arch // 10, min_arch % 10))
[Voice Changer] model slot is changed -1 -> 0
................RVC
2023-07-10 07:00:35 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-07-10 07:00:35 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-07-10 07:00:35 | INFO | faiss.loader | Loading faiss.
2023-07-10 07:00:35 | INFO | faiss.loader | Successfully loaded faiss.
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
inferencerTypeinferencerTypeinferencerTypeinferencerType onnxRVC
2023-07-10 07:00:36.1587941 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-07-10 07:00:36.1635654 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
Preparing your application. Please wait...
(node:17464) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x00000199076D1450>
GENERATE EMBEDDER <voice_changer.RVC.embedder.FairseqHubert.FairseqHubert object at 0x0000019921C40BB0>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000019934D61B70>
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
[Voice Changer][RVC]: update_settings modelSlotIndex 1688961516000
[2023-07-10 07:00:42] connet sid : fCHvrBfXoNzD-tTxAAAC
[2023-07-10 07:00:42] connet sid : fPX7sfOIYVJwuuBlAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 163, in inference
  File "torchaudio\functional\functional.py", line 1604, in resample
  File "torchaudio\functional\functional.py", line 1502, in _get_sinc_resample_kernel
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[Voice Changer] VC PROCESSING EXCEPTION!!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 163, in inference
  File "torchaudio\functional\functional.py", line 1604, in resample
  File "torchaudio\functional\functional.py", line 1502, in _get_sinc_resample_kernel
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[Voice Changer] VC PROCESSING EXCEPTION!!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 163, in inference
  File "torchaudio\functional\functional.py", line 1604, in resample
  File "torchaudio\functional\functional.py", line 1502, in _get_sinc_resample_kernel
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[Voice Changer] VC PROCESSING EXCEPTION!!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 228, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 163, in inference
  File "torchaudio\functional\functional.py", line 1604, in resample
  File "torchaudio\functional\functional.py", line 1502, in _get_sinc_resample_kernel
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by w-okada** [comment]
Error code said
````
Found GPU0 GeForce GT 720 which is of cuda capability 3.5.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability supported by this library is 3.7.
````

**Comment by lMINIMALl** [comment]
> Error code said
> 
> ```
> Found GPU0 GeForce GT 720 which is of cuda capability 3.5.
> PyTorch no longer supports this GPU because it is too old.
> The minimum cuda capability supported by this library is 3.7.
> ```

can I do something about it without changing the gpu?

**Comment by tooty-1135** [comment]
> Error code said
> 
> ```
> Found GPU0 GeForce GT 720 which is of cuda capability 3.5.
> PyTorch no longer supports this GPU because it is too old.
> The minimum cuda capability supported by this library is 3.7.
> ```

Can I change the version of PyTorch?
