### ISSUE TITLE
Model Load Failed

### ISSUE THREAD

**Issue by Hubetlo** [w-okada/voice-changer#494]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9

### OS

Windows 11 Home

### GPU

RTX 3060(6GB)

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

TypeError
Cannot read properties of null (reading 'enableServerAudio')
at DeviceArea (webpack://demo/./src/components/demo/components2/102-3_DeviceArea.tsx?:29:101)
at div
at ConfigArea (webpack://demo/./src/components/demo/components2/102_ConfigArea.tsx?:19:66)
at div
at div
at div
at ModelSlotControl (webpack://demo/./src/components/demo/b00_ModelSlotControl.tsx?:13:98)
at div
at GuiStateProvider (webpack://demo/./src/components/demo/001_GuiStateProvider.tsx?:63:23)
at Demo
at App (webpack://demo/./src/000_index.tsx?:43:98)
at AppStateProvider (webpack://demo/./src/001_provider/001_AppStateProvider.tsx?:29:23)
at ErrorBoundary (webpack://demo/./src/001_provider/900_ErrorBoundary.tsx?:27:86)
at AppStateWrapper (webpack://demo/./src/000_index.tsx?:55:99)
at AppRootProvider (webpack://demo/./src/001_provider/001_AppRootProvider.tsx?:27:23)

**Comment by 04041b** [comment]
Same issue here, hope my log can help.
```
[Voice Changer] update configuration: modelSlotIndex 1689925184004
[Voice Changer] model slot is changed 0 -> 4
................RVC
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
[Voice Changer] exception! loading inferencer Ran out of input
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 19, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencerNono.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
[Voice Changer] generate new embedder. (anyway)
2023-07-21 00:39:44.2912298 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-07-21 00:39:44.2961556 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
[Voice Changer] post_update_settings ex: local variable 'inferencer' referenced before assignment
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 73, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 248, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 204, in generateVoiceChanger
  File "voice_changer\RVC\RVC.py", line 54, in __init__
  File "voice_changer\RVC\RVC.py", line 60, in initialize
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 44, in createPipeline
UnboundLocalError: local variable 'inferencer' referenced before assignment
```

**Comment by w-okada** [comment]
try sample model

**Comment by 04041b** [comment]
> try sample model

Sample model is fine, it only occurs when you use custom model.
This problem is solved now, I have reinstall and it works well with custom model now. 
I upload the model remotely(with the https start script), and clicked the upload button multiple times before upload finishes. The issue occurs when I try to switch to my model I just uploaded.

**Comment by w-okada** [comment]
Okey, close
