### ISSUE TITLE
My voice changer is Not opening

### ISSUE THREAD

**Issue by HardMkaAvtion** [w-okada/voice-changer#508]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.8a.zip

### OS

mac M1

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

ONNX

### Situation

Its not opening but i don't know why Um.. code is like when I see the like code there is : exit ; idk Here is what code typed: on ttys000
/var/folders/r_/085rqfms78b3qmvdnsz43f0m0000gn/T/AppTranslocation/5D8492A4-FA41-43E7-92F4-F084548ED717/d/MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO ; exit;
ezra@ezras-MacBook-Air ~ % /var/folders/r_/085rqfms78b3qmvdnsz43f0m0000gn/T/AppTranslocation/5D8492A4-FA41-43E7-92F4-F084548ED717/d/MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO ; exit;
    Booting PHASE :__main__
    Voice Changerを起動しています。
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 126, in <module>
  File "downloader/WeightDownloader.py", line 17, in downloadWeight
  File "genericpath.py", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[6696] Failed to execute script 'MMVCServerSIO' due to unhandled exception: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[6696] Traceback:
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 126, in <module>
  File "downloader/WeightDownloader.py", line 17, in downloadWeight
  File "genericpath.py", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process Complete]

and nothing opening or appearing.

**Comment by w-okada** [comment]
did you open with .command file?
