### ISSUE TITLE
rmvpe question and Advanced Setting question 

### ISSUE THREAD

**Issue by l68728** [w-okada/voice-changer#520]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.10

### OS

macOS  Ventura13.4.1 and Windows 10 

### GPU

M2/4070ti

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pytorch f0

### I have two questions.

1.1(Bug)When I use rmvpe in Mac it has no sound and terminal shows

```
[Voice Changer][RVC]: update_settings f0Detector rmvpe
Generated Strengths: for prev:(4096,), for cur:(4096,)
torch/functional.py:641: UserWarning: The operator 'aten::_fft_r2c' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
[Voice Changer] VC PROCESSING EXCEPTION!!! Placeholder storage has not been allocated on MPS device!
Traceback (most recent call last):
  File "voice_changer/VoiceChanger.py", line 218, in on_request_sola
  File "voice_changer/RVC/RVC.py", line 176, in inference
  File "voice_changer/RVC/pipeline/Pipeline.py", line 112, in exec
  File "voice_changer/RVC/pitchExtractor/RMVPEPitchExtractor.py", line 35, in extract
  File "voice_changer/DiffusionSVC/pitchExtractor/rmvpe/rmvpe.py", line 387, in infer_from_audio_t
  File "torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "voice_changer/DiffusionSVC/pitchExtractor/rmvpe/rmvpe.py", line 321, in forward
RuntimeError: Placeholder storage has not been allocated on MPS device!
```
Does this mean that Mac cannot use rmvpe or that **device** is not specified as `mps` in the rmvpe file?
I want to try to change but the packaged program breaks the file structure, I can only speculate that.

1.2(Bug) When I use rmvpe on win10, I think the effect is very good, and the occupancy rate and delay are very satisfactory.But when switching, the following code will appear, the page will crash, and it needs to be initialized before it can be used.
```
[Voice Changer][RVC]: update_settings f0Detector rmvpe
[Voice Changer] post_update_settings ex: PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 273, in update_settings
  File "voice_changer\VoiceChanger.py", line 132, in update_settings
  File "voice_changer\RVC\RVC.py", line 80, in update_settings
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 24, in getPitchExtractor
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 42, in loadPitchExtractor
  File "voice_changer\RVC\pitchExtractor\RMVPEPitchExtractor.py", line 25, in __init__
  File "voice_changer\DiffusionSVC\pitchExtractor\rmvpe\rmvpe.py", line 332, in __init__
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```
2.Advanced Setting:what is the difference between sio and rest？
 and what is the difference between RVC quality low(rvcQuality 0) and high(rvcQuality 1)？
When use high quality, In some cases, the system usage is not high but the sound is intermittent on win10. And Mac only can use low quality because high quality has very high delay.

I didn't see any relevant instructions in the tutorial about Advanced Setting .Can you add it if possible?

**Comment by w-okada** [comment]
About (1-1)rmvpe in Mac.
I could reproduce, I am studing how to fix.

About (1-2) Win
I could not reproduced. The message seems apear when download weight is not succeded. Please re-install.

**Comment by w-okada** [comment]
About (2) Advanced Setting.
I was able to replicate this issue. However, since this function is not being maintained, it is classified as a low priority for correction. Dont use it.

**Comment by w-okada** [comment]
But Thank you for many useful reports.

**Comment by w-okada** [comment]
fiexed issue of rmvpe. try v.1.5.3.10a

**Comment by w-okada** [comment]
no res close
