### ISSUE TITLE
RVC does not change voice model

### ISSUE THREAD

**Issue by redbluexe1** [w-okada/voice-changer#539]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

Windows 11

### GPU

Nvidia GeForce GT 1030

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

any model

### Situation

rvc opens up fine, but when changing model, it says:

Looks like there's a bit of a problem.
unknwon message

If you clear the information being managed by this app, it may be recoverable
`Initialize`
`Reload without initialize`

`TypeError
Cannot read properties of null (reading 'enableServerAudio')
at vw (https://localhost:18888/index.js:2:2486149)
at div
at Sw (https://localhost:18888/index.js:2:2505407)
at div
at div
at div
at xw (https://localhost:18888/index.js:2:2510157)
at div
at cH (https://localhost:18888/index.js:2:2412449)
at Nw
at Tw (https://localhost:18888/index.js:2:2512441)
at Xy (https://localhost:18888/index.js:2:2410363)
at o (https://localhost:18888/index.js:2:2405537)
at _w (https://localhost:18888/index.js:2:2512717)
at Wy (https://localhost:18888/index.js:2:2406719)`

![image](https://github.com/w-okada/voice-changer/assets/86514546/594cffb7-e9f0-4611-8e56-73250162eee8)

**Comment by redbluexe1** [comment]
in command prompt (starthttps.bat): 
`[Voice Changer] update configuration: modelSlotIndex 1690107953000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 19, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 35, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] generate new embedder. (anyway)
[ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] Loading index...
[Voice Changer] post_update_settings ex: local variable 'inferencer' referenced before assignment
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 73, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 248, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 204, in generateVoiceChanger
  File "voice_changer\RVC\RVC.py", line 54, in __init__
  File "voice_changer\RVC\RVC.py", line 60, in initialize
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 44, in createPipeline
UnboundLocalError: local variable 'inferencer' referenced before assignment
2023-07-23 18:26:00 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2023-07-23 18:26:00 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
`

**Comment by w-okada** [comment]
You failed to download model or some weight.

this is answer from chat gpt.
![image](https://github.com/w-okada/voice-changer/assets/48346627/bb1f4798-700a-461d-98a1-526fb9a9e809)

**Comment by redbluexe1** [comment]
> You failed to download model or some weight.
> 
> this is answer from chat gpt. ![image](https://user-images.githubusercontent.com/48346627/255388827-bb1f4798-700a-461d-98a1-526fb9a9e809.png)

oh okay. im gonna redownload it

**Comment by redbluexe1** [comment]
redownloaded and running. still same issue, but its diffrent this time. 
Terminal (command prompt):
`D:\vcchng\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
[Voice Changer] matplotlib is dummied
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
+++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

Preparing your application. Please wait...
(node:6808) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
[Voice Changer] matplotlib is dummied
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[MODEL SLOT INFO] [RVCModelSlot(voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみち
ゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='model_dir\\0\\tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='model_dir\\0\\tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o'), RVCModelSlot(voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='model_dir\\1\\amitaro.png', speakers={'0': 'target'}, modelFile='model_dir\\1\\amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o'), RVCModelSlot(voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='model_dir\\2\\kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='model_dir\\2\\kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o'), RVCModelSlot(voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='model_dir\\3\\tokina_shigure.png', speakers={'0': 'target'}, modelFile='model_dir\\3\\tokina_shigure_v2_40k_e100_simple.onnx', indexFile='model_dir\\3\\added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o'), DiffusionSVCModelSlot(voiceChangerType='Diffusion-SVC', name='初期メン(3,20)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='model_dir\\4\\diffusion-svc.png', speakers={'1': 'user1', '2': 'user2', '3': 'user3', '4': 'user4', '5': 'user5'}, modelFile='model_dir\\4\\combo_spk5_nl3_dl20_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl20_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=20, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768), DiffusionSVCModelSlot(voiceChangerType='Diffusion-SVC', name='初 期メン(3,1)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='model_dir\\5\\diffusion-svc.png', speakers={'1': 'user1', '2': 'user2', '3': 'user3', '4': 'user4', '5': 'user5'}, modelFile='model_dir\\5\\combo_spk5_nl3_dl1_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl1_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=1, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={})]
[2023-07-24 09:33:10] connet sid : wzMBN-HV3wufhhuIAAAB
[2023-07-24 09:33:10] connet sid : KoUkZXaW9OreHkRqAAAD
[Voice Changer] update configuration: modelSlotIndex 1690162396000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVC] Creating instance
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 26, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
[Voice Changer] post_update_settings ex: local variable 'embedder' referenced before assignment
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 271, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 277, in update_settings
  File "voice_changer\VoiceChanger.py", line 132, in update_settings
  File "voice_changer\RVC\RVC.py", line 74, in update_settings
  File "voice_changer\RVC\RVC.py", line 60, in initialize
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 43, in createPipeline
UnboundLocalError: local variable 'embedder' referenced before assignment
[5672:0724/093505.104:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is`

**Comment by redbluexe1** [comment]
apparently also found out changing any settings also cause the issue

**Comment by w-okada** [comment]
I think your download file is broken, see and check your download file.

https://github.com/w-okada/voice-changer/issues/488

**Comment by redbluexe1** [comment]
i am redownloading it. and also try use directml if its the same

**Comment by w-okada** [comment]
check your downloaded files. 

Are they correct? or not?  all files is there? file size is same?

**Comment by w-okada** [comment]
no res close
