### ISSUE TITLE
start_http.bat failing

### ISSUE THREAD

**Issue by MysteriousSwordsman** [w-okada/voice-changer#567]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

Windows 11

### GPU

4070ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

![2023-07-26 12_28_50-Greenshot](https://github.com/w-okada/voice-changer/assets/122497266/093e7765-759b-42c7-9039-ebd8874dced1)
![2023-07-26 10_36_30-C__WINDOWS_system32_cmd exe](https://github.com/w-okada/voice-changer/assets/122497266/b7cf0c61-514c-498d-beda-0def1ce8cafc)

I have downloaded and unpacked different versions of the program. .10 .10a and .9a with all of them resulting in the same console window where it fails to launch. It initially opened and then closed really fast, but I managed to grab the console window to display the error and it was the same error. Those pictures are 2 hours apart from one another on different versions of the program. But neither .bat file will allow me to launch.

Can you please help me?

**Comment by w-okada** [comment]
This is a phenomenon I've never seen before. Let's see if others have experienced the same thing.

**Comment by MysteriousSwordsman** [comment]
So I am not the most adept at coding but continuing to look around allowed me to find this:

https://www.data-mining.co.nz/docker-for-data-scientists/troubleshooting/

which then led me to this:

https://stackoverflow.com/questions/59290386/runtimeerror-at-cannot-cache-function-shear-dense-no-locator-available-fo/63367171#63367171

What file or files do I need to modify in order to fix the numba caching issue? Apparently, if I direct it somewhere it should fix my issue.

**Comment by w-okada** [comment]
https://github.com/librosa/librosa/issues/1156

check your diskspace.

**Comment by MysteriousSwordsman** [comment]
![image_2023-07-26_185657885](https://github.com/w-okada/voice-changer/assets/122497266/4a0b736c-645e-4933-b357-17599d29e1c5)

I moved it to another drive with over 1 TB available, got the same error. Is there anything else I can try?

**Comment by w-okada** [comment]
Sorry, I have no idea

**Comment by MysteriousSwordsman** [comment]
I put it in an virtual environment and still failed...

(myenv) D:\VC\MMVCServerSIO>"D:\VC\MMVCServerSIO\start_http.bat"

(myenv) D:\VC\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "downloader\SampleDownloader.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\DiffusionSVC\DiffusionSVCModelSlotGenerator.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\DiffusionSVC\inferencer\diffusion_svc_model\diffusion\unit2mel.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\DiffusionSVC\inferencer\diffusion_svc_model\diffusion\vocoder.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\DiffusionSVC\inferencer\diffusion_svc_model\nsf_hifigan\nvSTFT.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "librosa\__init__.py", line 209, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "librosa\core\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "librosa\core\convert.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "librosa\core\notation.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "librosa\util\__init__.py", line 77, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "librosa\util\utils.py", line 1879, in <module>
  File "numba\core\decorators.py", line 234, in wrapper
  File "numba\core\dispatcher.py", line 863, in enable_caching
  File "numba\core\caching.py", line 601, in __init__
  File "numba\core\caching.py", line 337, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'librosa\\util\\utils.py'
[24140] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

**Comment by 0xicl33n** [comment]
Same problem. win10

**Comment by w-okada** [comment]
@MysteriousSwordsman 

try @0xicl33n's way

**Comment by MysteriousSwordsman** [comment]
I reinstalled Windows 11 and it now works. I had tried the admin thing before and it did not work.

**Comment by w-okada** [comment]
OKay, close this issue
