### ISSUE TITLE
MMVCv13 model could not be uploaded

### ISSUE THREAD

**Issue by AlphaCyan** [w-okada/voice-changer#579]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a

### OS

Windows 10

### GPU

GeForce GTX 1650

### Clear setting

no

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC, MMVVCv13

### Model type

ONNX

### Situation

How to fix these errors?
---Too much memory allocation
[Voice Changer] [MMVCv13] Creating instance
[Voice Changer] [MMVCv13] Initializing...
[Voice Changer] post_update_settings ex: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\2\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 1376256

Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 267, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 222, in generateVoiceChanger
  File "voice_changer\MMVCv13\MMVCv13.py", line 62, in __init__
  File "voice_changer\MMVCv13\MMVCv13.py", line 70, in initialize
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\2\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 1376256

---Unknown
[Voice Changer] VC PROCESSING EXCEPTION!!! 'HParams' object has no attribute 'data'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 191, in on_request_sola
  File "voice_changer\MMVCv13\MMVCv13.py", line 139, in get_processing_sampling_rate
AttributeError: 'HParams' object has no attribute 'data'

[Voice Changer] VC PROCESSING EXCEPTION!!! 'HParams' object has no attribute 'data'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 191, in on_request_sola
  File "voice_changer\MMVCv13\MMVCv13.py", line 139, in get_processing_sampling_rate
AttributeError: 'HParams' object has no attribute 'data'

[Voice Changer] VC PROCESSING EXCEPTION!!! 'HParams' object has no attribute 'data'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 191, in on_request_sola
  File "voice_changer\MMVCv13\MMVCv13.py", line 139, in get_processing_sampling_rate
AttributeError: 'HParams' object has no attribute 'data'

![Screenshot 2023-07-28 210215](https://github.com/w-okada/voice-changer/assets/140358291/0066108d-56c6-4789-8147-2e62abaa637e)
![Screenshot 2023-07-28 210244](https://github.com/w-okada/voice-changer/assets/140358291/976fa6ed-fec5-4ee5-bf1d-3b8435722527)

**Comment by w-okada** [comment]
I couldn't reproduce. 
Are you training using this repository?
https://github.com/isletennos/MMVC_Trainer

**Comment by AlphaCyan** [comment]
I have fixed the issue, sorry for bothering.
Have a nice day!
