### ISSUE TITLE
Dockerにて動作しない

### ISSUE THREAD

**Issue by swut047** [w-okada/voice-changer#584]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.10b

### OS

Ubuntu 20.04

### GPU

RTX 3080

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

PyTorch

### Situation

start2.shを実行し、Server Setting, Device Settingを行った上でstartを押すと以下エラーが発生します。

``` 
$ USE_GPU=on source start2.sh MMVC
MMVCを起動します(with gpu)
exec with [UID : 1000, GID: 1000]
------
MMVC
TYPE: MMVC
PARAMS: 
------
MMVCを起動します
/voice-changer/server/MMVCServerSIO.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
    Voice Changerを起動しています。
    -- 設定 -- 
    CONFIG:None, MODEL:None ONNX_MODEL:None
    External_Port:18888 Internal_Port:18888
    External_IP:192.168.10.106 172.17.0.1 
    protocol: HTTP
    -- ---- -- 
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
    サーバプロセスを起動しています。
post_update_setteings framework ONNX
post_update_setteings dstId 100
post_update_setteings minConvertSize 0
post_update_setteings onnxExecutionProvider CPUExecutionProvider
post_update_setteings srcId 107
onnxExecutionProvider is not mutalbe variable!
post_update_setteings gpu 0
post_update_setteings convertChunkNum 32
post_update_setteings crossFadeOffsetRate 0.1
post_update_setteings crossFadeOverlapRate 0.5
post_update_setteings crossFadeEndRate 0.9
post_update_setteings framework PyTorch
Generated Strengths
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-75' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py:522> exception=AttributeError("'VoiceChanger' object has no attribute 'hps'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py", line 569, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/usr/local/lib/python3.10/dist-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/voice-changer/server/sio/MMVC_Namespace.py", line 31, in on_request_message
    audio1 = self.voiceChangerManager.changeVoice(unpackedData)
  File "/voice-changer/server/voice_changer/VoiceChangerManager.py", line 36, in changeVoice
    return self.voiceChanger.on_request(unpackedData)
  File "/voice-changer/server/voice_changer/VoiceChanger.py", line 300, in on_request
    data = self._generate_input(unpackedData, convertSize)
  File "/voice-changer/server/voice_changer/VoiceChanger.py", line 171, in _generate_input
    audio_norm = audio / self.hps.data.max_wav_value  # normalize
AttributeError: 'VoiceChanger' object has no attribute 'hps'
```

**Comment by w-okada** [comment]
read readme and tutorial
