### ISSUE TITLE
[Voice Changer] Pipeline is not initialized.111

### ISSUE THREAD

**Issue by joemeer** [w-okada/voice-changer#611]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

windows 10

### GPU

NVIDIA GeForce GTX 1650 super

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

idk

### Situation

![first message](https://github.com/w-okada/voice-changer/assets/141104763/b69986a8-5c1b-4e6d-a2d1-7b408f3cd468)
![image](https://github.com/w-okada/voice-changer/assets/141104763/33225fd9-319c-42fe-af86-fda6d6c1a671)

I just downloaded it idk what I'm doing.
when I opened it and tried to use one of the models that comes with it, it didn't work. it kept saying [Voice Changer] Pipeline is not initialized.111
so I downloaded a model from a discord server to try and see if it would work it, and it didn't, it kept giving me the same message, I sent a screenshot. 
I don't if I did something wrong or what but I cant find the solution any where on google. all i found was something similar someone sent yesterday.
sorry if I'm bothering you and its a simple thing, I just downloaded it a hour ago trying to fix it.

**Comment by w-okada** [comment]
show me full log on the terminal

**Comment by joemeer** [comment]
> 

D:\Voice changer\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
[Voice Changer] custom matplotlib loaded successfully
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

[VCClient] Access http://localhost:18888/
(node:15580) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:15580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[Voice Changer] custom matplotlib loaded successfully
Preparing your application. Please wait...
(node:15580) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 6
................RVC
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] [RVC] Creating instance
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVC] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
Preparing your application. Please wait...
(node:15580) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings f0Detector:crepe
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer][RVC]: update_settings modelSlotIndex:1690860102006
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[2023-08-02 11:14:42] connet sid : GQcy0E4EKe2K0kCDAAAB
[2023-08-02 11:14:42] connet sid : 1fijrISv0nLcP8pfAAAD
[Voice Changer] update configuration: modelSlotIndex 1690964087002
[Voice Changer] model slot is changed 6 -> 2
................RVC
[Voice Changer] [RVC] Creating instance
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVC] Initializing...
2023-08-02 11:14:52.2565103 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-02 11:14:52.2782966 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] update configuration: modelSlotIndex 1690964096002
[Voice Changer] model slot is changed 6 -> 2
................RVC
[Voice Changer] [RVC] Creating instance
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVC] Initializing...
2023-08-02 11:15:00.5842279 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-02 11:15:00.5938871 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
[Voice Changer][RVC]: update_settings silentThreshold:0.001
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
[Voice Changer][RVC]: update_settings f0Detector:crepe
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings modelSlotIndex:1690964096002
[Voice Changer][RVC]: update_settings f0Detector:crepe
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer][RVC]: update_settings modelSlotIndex:1690964087002
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
[Voice Changer] Pipeline is not initialized.111
any thing else ?

**Comment by w-okada** [comment]
same 
https://github.com/w-okada/voice-changer/issues/462

**Comment by PogChoke** [comment]
> same #462

You aren't helping anybody. You're supposed to help them, and tell them what to do. Not just leave one word.

**Comment by AimRite2YT** [comment]
i have this problem too

**Comment by miyusuri** [comment]
help
