### ISSUE TITLE
Frequent errors occur

### ISSUE THREAD

**Issue by bjork99fan** [w-okada/voice-changer#641]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 11

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

Whenever I click the start button no audio is coming out and I keep getting prompted with the message "frequent errors occur. please check if the model of the framework being targeted is loaded"

### logs on terminal

C:\Users\small\Documents\bl\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

[VCClient] Access http://localhost:18888/
(node:9728) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:9728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Preparing your application. Please wait...
(node:9728) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cpu
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Preparing your application. Please wait...
(node:9728) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[2023-08-05 18:55:30] connet sid : JU9kHdgidcCjyh57AAAC
[2023-08-05 18:55:30] connet sid : hN5Vk1uyFw9WNkthAAAD
[Voice Changer] update configuration: modelSlotIndex 1691279731000
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cpu
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] update configuration: modelSlotIndex 1691279750001
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cpu
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] update configuration: modelSlotIndex 1691279750001
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cpu
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)

During handling of the above exception, another exception occurred:

  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
Traceback (most recent call last):
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by w-okada** [comment]
same 
https://github.com/w-okada/voice-changer/issues/462

**Comment by morl1x** [comment]
same
