### ISSUE TITLE
Frequent errors occur. Please check if the model of the framework is being targeted is loaded.

### ISSUE THREAD

**Issue by Hatsuu667** [w-okada/voice-changer#645]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 11

### GPU

4070 TI Nvidia 

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

Basic Model 

### Situation

Just install the app by following a tuto on youtube but got this error coming back again and again : Frequent errors occur. Please check if the model of the framework is being targeted is loaded. Don't know what to do

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/141562154/20ecf14b-b5e7-4b8f-8828-a6d2d0bdd60d)

### logs on terminal

Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[2023-08-06 14:36:26] connet sid : LSw9Zpo0GrFWcNLyAAAc
[2023-08-06 14:36:26] connet sid : ncl72qRbc8zZlt6cAAAd
<class 'str'>
51-/test,["request_message",[1691325386673,{"_placeholder":true,"num":0}]]
[2023-08-06 14:42:17] connet sid : cJEeObVIjyyV54bjAAAg
[2023-08-06 14:42:17] connet sid : FWrN3IyO92VfTHQWAAAh
<class 'str'>
51-/test,["request_message",[1691325737909,{"_placeholder":true,"num":0}]]

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/462
