### ISSUE TITLE
VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'

### ISSUE THREAD

**Issue by imtrash84** [w-okada/voice-changer#652]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12.zip

### OS

Windows 10

### GPU

GTX 1650 Super

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

every default model

### Situation

hi. i just downloaded the app and i got this issue and i don't know what to do. please help me, thanks a lot

### logs on terminal

D:\Voice Changer\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVCr2] Initializing...
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 35, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 35, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer][RVC]: update_settings modelSlotIndex:1691401199000
[VCClient] wait web server... done 200
[2023-08-07 13:18:41] connet sid : JWZvNYqXd2QX2R7bAAAB
[2023-08-07 13:18:41] connet sid : bYNHa49gQz8oX50XAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] update configuration: serverReadChunkSize 32
[Voice Changer][RVC]: update_settings serverReadChunkSize:32
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/481
