### ISSUE TITLE
Frequent errors occur.Please check if the model of the framework being targeted is loaded.

### ISSUE THREAD

**Issue by FallingEpiphany** [w-okada/voice-changer#692]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12

### OS

Windows 11

### GPU

NVIDIA GeForce RTX 3070 Laptop

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC and Diff-SVC

### Model type

pyTorch ONNX

### Situation

![image](https://github.com/w-okada/voice-changer/assets/123282147/bd6a1c77-4892-4531-9419-2fe8fb4641d8)
It warns is. After I tried every thing i can find, my voice input still can't change.
` exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory` I don't know what to do next. And the embedder seems missing.

### logs on terminal

    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] custom matplotlib loaded successfully
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
[Voice Changer] load onnx nsf-hifigan
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\DiffusionSVC\pipeline\PipelineGenerator.py", line 34, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
[Voice Changer] load onnx nsf-hifigan
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\DiffusionSVC\pipeline\PipelineGenerator.py", line 34, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[VCClient] wait web server... done 200
[2023-08-11 23:31:55] connet sid : h6XeEeDB2G40-BjMAAAC
[2023-08-11 23:31:55] connet sid : zbvQSBd-jML8uXEMAAAD
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[2023-08-11 23:33:08] connet sid : GhVvd8-EJxZ2lz15AAAG
[2023-08-11 23:33:08] connet sid : 019nGNz8TNdACeK4AAAH
<class 'str'>
51-/test,["request_message",[1691767988079,{"_placeholder":true,"num":0}]]

**Comment by FallingEpiphany** [comment]
I deleted the model_dir folder, and reboot the changer.
New Info:     Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[74088:0811/235902.444:ERROR:cache_util_win.cc(20)] Unable to move the cache: 拒绝访问。 (0x5)
[74088:0811/235902.444:ERROR:disk_cache.cc(205)] Unable to create cache
[VCClient] wait web server... done 200
[53408:0811/235902.471:ERROR:cache_util_win.cc(20)] Unable to move the cache: 拒绝访问。 (0x5)
[53408:0811/235902.471:ERROR:cache_util_win.cc(20)] Unable to move the cache: 拒绝访问。 (0x5)
[53408:0811/235902.478:ERROR:disk_cache.cc(205)] Unable to create cache
[53408:0811/235902.478:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[53408:0811/235902.478:ERROR:disk_cache.cc(205)] Unable to create cache
[53408:0811/235902.478:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[53408:0811/235904.120:ERROR:quota_database.cc(939)] Could not open the quota database, resetting.
[Voice Changer] custom matplotlib loaded successfully
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
[Voice Changer] load onnx nsf-hifigan
[Voice Changer] generate new embedder. (no embedder)
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
[53408:0811/235908.009:ERROR:quota_database.cc(939)] Could not open the quota database, resetting.
[Voice Changer] load onnx nsf-hifigan
[Voice Changer] generate new embedder. (anyway)
[53408:0811/235910.888:ERROR:quota_database.cc(941)] Failed to reset the quota database.
[53408:0811/235910.888:ERROR:quota_database.cc(941)] Failed to reset the quota database.

**Comment by FallingEpiphany** [comment]
??????
I rebooted it again, and it works. It's really strange. (⊙_⊙)？

**Comment by w-okada** [comment]
Ok, close
