### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CRHiHiHa** [w-okada/voice-changer#694]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a.zip

### OS

Windows 10

### GPU

GT740 2GB GDDR5

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC v1.3

### Model type

pyTorch

### logs on terminal

[Voice Changer] VC PROCESSING EXCEPTION!!! CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 228, in on_request
  File "voice_changer\RVC\RVCr2.py", line 197, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 107, in exec
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by bmaxdk** [comment]
if you debug with `CUDA_LAUNCH_BLOCKING=1`, what do you see?

```
export CUDA_LAUNCH_BLOCKING=1
python path of voice_changer/VoiceChangerV2.py
```
Could be your GT740 2GB GDDR5 not meet the requirement?

**Comment by CRHiHiHa** [comment]
> if you debug with `CUDA_LAUNCH_BLOCKING=1`, what do you see?
> 
> ```
> export CUDA_LAUNCH_BLOCKING=1
> python path of voice_changer/VoiceChangerV2.py
> ```
> 
> Could be your GT740 2GB GDDR5 not meet the requirement?

no idea

**Comment by w-okada** [comment]
I have no idea.

**Comment by bmaxdk** [comment]
I guess your GPU cannot handle? if you are planning on using PyTorch for very large models or datasets, you may want to consider a more powerful GPU. Since the error message you're encountering, `CUDA error: no kernel image is available for execution on the device,` usually indicates that there's a discrepancy between the GPU's compute capability and the compiled code, causing compatibility issues.
Currently all I can say is your GPU is not compatible to run current model.

**Comment by wokadasolver** [comment]
correct, his gpu is too old and the gpu tech cant handle that
