### ISSUE TITLE
Running voice-changer through docker on linux gives error: No module named 'beatrice_internal_api'

### ISSUE THREAD

**Issue by foodornt** [w-okada/voice-changer#697]
I cloned the repo at commit 46ff05b04f1c034b50486fe116e8216135945e76 (latest master as of the moment)
I'm using arch linux, running a 3050 rtx, these are the logs upon executing ./start_docker.sh:

```
VC Client start...(with gpu)
exec with [UID : 1000, GID: 998]
/voice-changer/server/MMVCServerSIO.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
Traceback (most recent call last):
  File "/voice-changer/server/MMVCServerSIO.py", line 18, in <module>
    from voice_changer.VoiceChangerManager import VoiceChangerManager
  File "/voice-changer/server/voice_changer/VoiceChangerManager.py", line 14, in <module>
    from voice_changer.VoiceChangerV2 import VoiceChangerV2
  File "/voice-changer/server/voice_changer/VoiceChangerV2.py", line 21, in <module>
    from voice_changer.Beatrice.Beatrice import Beatrice
  File "/voice-changer/server/voice_changer/Beatrice/Beatrice.py", line 10, in <module>
    from beatrice_internal_api import BeatriceInternalAPI
ModuleNotFoundError: No module named 'beatrice_internal_api'
```

I suggest you guys change the original template as it contains a lot of stuff that I didn't find necessary to submit, as I haven't got to launch the program in the first place

**Comment by foodornt** [comment]
Using an older commit made it work just fine 👍
Although indeed last commit is bugful
