### ISSUE TITLE
Failing when clicking on model 

### ISSUE THREAD

**Issue by wewwlad** [w-okada/voice-changer#742]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

Windows 10

### GPU

Nvdia/intel

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

I made sure to download both pytorch and onnx

### Situation

When I press the model I get the error that it is missing. I tried making a new model but that one also gets a similar error. 

### logs on terminal

[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] post_update_settings ex: Can't get source for <function script_skip_tensor_list at 0x0000015ECDE1E560>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
Traceback (most recent call last):
  File "torch\_sources.py", line 23, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "inspect.py", line 1121, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 302, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 234, in generateVoiceChanger
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\RVC\RVCr2.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\RVC\embedder\FairseqContentvec.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "fairseq\__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "fairseq\criterions\__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "fairseq\criterions\ctc.py", line 19, in <module>
    from fairseq.tasks import FairseqTask
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "fairseq\tasks\__init__.py", line 136, in <module>
  File "fairseq\tasks\__init__.py", line 117, in import_tasks
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "fairseq\tasks\multilingual_translation.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "fairseq\models\__init__.py", line 235, in <module>
  File "fairseq\models\__init__.py", line 217, in import_models
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "fairseq\models\model_utils.py", line 13, in <module>
  File "torch\jit\_script.py", line 1338, in script
  File "torch\jit\frontend.py", line 262, in get_jit_def
  File "torch\_sources.py", line 120, in parse_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(
  File "torch\_sources.py", line 32, in get_source_lines_and_file
    raise OSError(msg) from e
OSError: Can't get source for <function script_skip_tensor_list at 0x0000015ECDE1E560>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

**Comment by w-okada** [comment]
Doesn't it work even with the sample model?

**Comment by w-okada** [comment]
no res close
