### ISSUE TITLE
DDSP-SVC4.0モデル使用時、rmvpe使用不可？（rmvpe cannot be used when using the DDSP-SVC4.0 model?）

### ISSUE THREAD

**Issue by lenore-puwawa** [w-okada/voice-changer#762]
### Issue Type

Feature Request, Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10、MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

windows11

### GPU

RTX4090

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

DDSP-SVC4.0

### Model type

f0

### Situation

DDSP-SVC4.0モデル使用時に、VC Client v.1.5.3.10のF0 Detに「rmvpe」を設定して音声変換開始するとエラーログが出力されます。
また、VC Client v.1.5.3.12a使用時同様にF0 Detに「rmvpe」を設定して音声変換開始するとエラーログは出力されませんが、音声が変換されません。
上記より、DDSP-SVCモデルでのrmvpe使用が現状不可だと推測しますが、可能であれば対応していただけると嬉しいです。

When using the DDSP-SVC4.0 model, setting "rmvpe" to F0 Det of VC Client v.1.5.3.10 and starting voice conversion will output an error log.
Also, when using VC Client v.1.5.3.12a, if you set F0 Det to "rmvpe" and start voice conversion, an error log will not be output, but the voice will not be converted.
Based on the above, I assume that it is currently impossible to use rmvpe with the DDSP-SVC model, but I would appreciate it if you could support it.

### logs on terminal

v.1.5.3.10使用時のエラーログ
F0 Detを「rmvpe」にして変換開始した際に出力される
[Voice Changer] VC PROCESSING EXCEPTION!!! name 'f0_extractor' is not defined
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 218, in on_request_sola
  File "voice_changer\DDSP_SVC\DDSP_SVC.py", line 163, in inference
  File "voice_changer\DDSP_SVC\DDSP_SVC.py", line 133, in _pyTorch_inference
  File "voice_changer\DDSP_SVC\SvcDDSP.py", line 123, in infer
  File "voice_changer\DDSP_SVC\models\ddsp\vocoder.py", line 75, in extract
NameError: name 'f0_extractor' is not defined

v.1.5.3.12a使用時のログ（エラーログは出力されないが、音声変換されない）
F0 Detを「harvest」に変更した後、「rmvpe」に変更した際のログ
[Voice Changer] update configuration: f0Detector harvest
| Load HifiGAN:  pretrain/nsf_hifigan/model
Removing weight norm...
[Voice Changer] update configuration: f0Detector rmvpe

**Comment by w-okada** [comment]
so-vits-svc 4.0?

**Comment by lenore-puwawa** [comment]
[DDSP-SVC](https://github.com/yxlllc/DDSP-SVC)です。

**Comment by w-okada** [comment]
DDSP-SVCに4.0があったんですね。
いずれにせよ、いまのところはrmvpeは対応できていません。
feature requestということで、タグをつけておきます。
