### ISSUE TITLE
"Pipeline is not initialized"

### ISSUE THREAD

**Issue by SheldonTheOneAndOnly** [w-okada/voice-changer#781]
I have installed the Windows CUDA version of the program and strangely I can't get it to run because of "Pipeline is not initialized"

```
C:\Artificial Intelligence\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={0: 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={0: 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={0: 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={0: 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
[Voice Changer] Downloading model files...
                                                                                                                       [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={'0': 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=2, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひ ろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=3, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={'0': 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-01 21:02:38] connet sid : fxOtBlP899pXVA1VAAAB
[2023-09-01 21:02:38] connet sid : 1qknxyIzwCWXU4lmAAAD
[Voice Changer] update configuration: modelSlotIndex 1693594964000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2023-09-01 21:02:46.1685551 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-01 21:02:46.1757671 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings modelSlotIndex:1693594964000
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
```

**Comment by w-okada** [comment]
use issue template
