### ISSUE TITLE
[ISSUE]: no output sound

### ISSUE THREAD

**Issue by alanmlcrt** [w-okada/voice-changer#852]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11

### Operational System

Windows 11

### GPU

RTX 3070

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

no sound comes out of the software. My microphone is used by the application but there is no sound. The passthru works, I can hear myself but without the modified voice.

### Logs on console

C:\Users\alanc\Documents\voice AI\RVC\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 35, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[VCClient] wait web server... done 200
[2023-09-15 23:34:15] connet sid : o9dhrOvMu7hJH89JAAAB
[2023-09-15 23:34:15] connet sid : f3ve8rHpuLNJ9hc7AAAD
[Voice Changer] update configuration: rvcQuality 1
[2023-09-15 23:45:03] connet sid : mZTK4mWifmaz4roMAAAG
[2023-09-15 23:45:03] connet sid : WKcLKwrajMBJxJItAAAH
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: silenceFront 0
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: modelSlotIndex 1694814475002
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 35, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: crossFadeOverlapSize 1024
[Voice Changer] update configuration: passThrough true
[2023-09-15 23:48:21] connet sid : hblKKvsmHEw5bdr7AAAK
[2023-09-15 23:48:21] connet sid : 4Aa0_jQfSbhOg6LWAAAL
[2023-09-15 23:48:25] connet sid : 0zwueLBVVxqtJE4SAAAO
[2023-09-15 23:48:25] connet sid : 7Cl0Dg8xnts90WGKAAAP
[Voice Changer] update configuration: silenceFront 0
[Voice Changer] update configuration: modelSlotIndex 1694814514003
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 35, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] update configuration: passThrough false

**Comment by w-okada** [comment]
If the sample model is working fine, your model might be broken. recheck it

**Comment by w-okada** [comment]
no res close
