### ISSUE TITLE
[ISSUE]:  Okada RVC Kaggle Environment is Not Running

### ISSUE THREAD

**Issue by bennett-krubakar** [w-okada/voice-changer#865]
### Voice Changer Version

Not sure

### Operational System

Kaggle

### GPU

P100

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

**Description:**
The Okada RVC environment on Kaggle has been non-functional for the past few days. It seems to be encountering issues with starting the server. The error messages have changed recently, indicating that there might be ongoing maintenance or changes to the environment.

**Current Behavior:**
The Okada RVC Kaggle environment is not running, and it fails to start the server.

**Additional Information:**
It's worth noting that the error messages recently changed, which suggests ongoing updates or maintenance. Any information on these changes or a timeline for when the environment will be functional again would be greatly appreciated.

**Labels:** bug, kaggle, environment, server

**Requesting help from:** @Rafacasari 

### Application Screenshot

**Screenshots/Logs:**

Recent error message(s) while trying to start the server.
![image](https://github.com/w-okada/voice-changer/assets/81170429/05896ba7-3c60-4d26-9c7b-35101743e197)
![image](https://github.com/w-okada/voice-changer/assets/81170429/60e6dd36-65db-4581-bceb-d27d37807de8)
![image](https://github.com/w-okada/voice-changer/assets/81170429/7b7e21b7-102a-420c-bac5-6df6ba7ddc8e)

Error messages encountered during the installation of dependencies for reference.
![image](https://github.com/w-okada/voice-changer/assets/81170429/a7ff71a7-4ab5-4938-94c2-33aa84376cf9)

### Logs on console

```
/kaggle/working/voice-changer/server
<frozen importlib._bootstrap>:241: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
^C
Traceback (most recent call last):
  File "/kaggle/working/voice-changer/server/MMVCServerSIO.py", line 19, in <module>
    from sio.MMVC_SocketIOApp import MMVC_SocketIOApp
  File "/kaggle/working/voice-changer/server/sio/MMVC_SocketIOApp.py", line 1, in <module>
    import socketio
  File "/opt/conda/lib/python3.10/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/opt/conda/lib/python3.10/site-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/opt/conda/lib/python3.10/site-packages/engineio/__init__.py", line 8, in <module>
    from .asyncio_client import AsyncClient
  File "/opt/conda/lib/python3.10/site-packages/engineio/asyncio_client.py", line 7, in <module>
    import aiohttp
  File "/opt/conda/lib/python3.10/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/opt/conda/lib/python3.10/site-packages/aiohttp/client.py", line 32, in <module>
    import attr
  File "/opt/conda/lib/python3.10/site-packages/attr/__init__.py", line 26, in <module>
    from ._version_info import VersionInfo
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
KeyboardInterrupt
```

**Comment by Rafacasari** [comment]
I think Colab and Kaggle banned WebUIs/tunnels like Gradio, Ngrok, but not sure

**Comment by Rafacasari** [comment]
I think Amazon is paid, no? The best paid option is paperspace, I think.

But idk about it too, I've never used amazon studio

**Comment by bennett-krubakar** [comment]
Sagemake is free. We get 4 hrs of GPU time in a day, and 8 hrs of CPU time in a day with a runtime of max 4 hrs per session. With Paperspace I think you get 8 hrs per day. But overall, I've heard Sagemaker GPU is stronger than Paperspace. But if we can get Okada RVC running in either of them, that would be great.

**Comment by bennett-krubakar** [comment]
@Rafacasari  I have checked out both Sagemaker and Paperspace. From what I have found, Paperspace is technically free but practically, it is not. Paperspace only has one free GPU option and is unavailable primarily due to its high demand. While Paperspace may provide more GPU runtime hours per day than Sagemaker, paperspace is not free(Practically). Sagemaker has an odd interface compared to other notebooks but it's not complicated. I think Sagemaker is the best option we have at hand. 

I would like to request your help to create a notebook for Sagemaker to run okada-RVC.

**Comment by Rafacasari** [comment]
I have tried for some minutes to run the notebooks that we already have, but seems that Amazon will have some specific issues that I'll have to fix. I will try again later.

**Comment by bennett-krubakar** [comment]
@Rafacasari Thank you for looking into this. If you have any updates on Sagemaker, I would love to know about it.

**Comment by bennett-krubakar** [comment]
I don't think what I've done is right but give it a gander and see what I should be changing for this to work.

![image](https://github.com/w-okada/voice-changer/assets/81170429/38b159eb-ee0f-407f-bb96-1629f2ba462d)
![image](https://github.com/w-okada/voice-changer/assets/81170429/3e87b24f-dcdc-4b9b-8bb5-22548dfe8d39)
![image](https://github.com/w-okada/voice-changer/assets/81170429/1769f37b-d5f7-4f5a-a022-b68e0a956604)
![image](https://github.com/w-okada/voice-changer/assets/81170429/a6828243-ab17-4779-8e43-4501d07f801c)
![image](https://github.com/w-okada/voice-changer/assets/81170429/4d1cf35a-f2bd-409b-95f5-b1a28a536e0b)
![image](https://github.com/w-okada/voice-changer/assets/81170429/e997b5cb-e095-4417-a8c3-b45f1d304af3)
![image](https://github.com/w-okada/voice-changer/assets/81170429/7a099293-f6f3-41e2-9a19-fb6bf9ca2fca)

**Comment by DaUnknow1** [comment]
It looks like you got your directory wrong. I think your directory is /home/studio-lab-user/sagemaker-studiolab-notebooks/voice-changer/server if it doesn't work try and find where
 the server folder is and right-click and copy the path then use %cd /home/studio-lab-user/[Copied path]. Also you need the !python3 MMVCServerSIO.py and the ngrok.disconnect(ngrokConnection.public_url) needs to be in the same cell as the above. **If you a easier way just download the zip and unzip the file click upload file and put your token and just all every cell it should run properly ** [Amazon_SageMaker_Studio(Lab)_RealtimeVoiceChanger.zip](https://github.com/w-okada/voice-changer/files/12732758/Amazon_SageMaker_Studio.Lab._RealtimeVoiceChanger.zip)

**Comment by DaUnknow1** [comment]
Send a screenshot of your problem

**Comment by bggir** [comment]
I got the following error. Could anyone let me know how to solve it? I unzipped the file and used the codes.

File "/home/studio-lab-user/voice-changer/server/const.py", line 5, in <module>
    from typing import Literal, TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/home/studio-lab-user/.conda/envs/default/lib/python3.9/typing.py)

**Comment by razzytest61** [comment]
https://www.kaggle.com/code/razzytest/public-w-okada-voice-changer

100 working voice changers
