### ISSUE TITLE
[ISSUE]: numba import error

### ISSUE THREAD

**Issue by coolst3r** [w-okada/voice-changer#875]
### Voice Changer Version

latest

### Operational System

arch linux

### GPU

3060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

rvc

### Issue Description

wafter launch

### Logs on console

Traceback (most recent call last):
  File "/home/cunny/voice-changer/server/MMVCServerSIO.py", line 18, in <module>
    from voice_changer.VoiceChangerManager import VoiceChangerManager
  File "/home/cunny/voice-changer/server/voice_changer/VoiceChangerManager.py", line 9, in <module>
    from voice_changer.Local.ServerDevice import ServerDevice, ServerDeviceCallbacks
  File "/home/cunny/voice-changer/server/voice_changer/Local/ServerDevice.py", line 13, in <module>
    import librosa
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages/numba/__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")

**Comment by coolst3r** [comment]
Requirement already satisfied: NumPy==1.24 in /home/cunny/miniconda3/envs/vcclient-dev/lib/python3.10/site-packages (1.24.0)
