### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by nazar641** [w-okada/voice-changer#900]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14

### Operational System

Windows 11

### GPU

Rtx 3060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Everything works fine, that's just when I click on "start" the voice transformation does not work, I tried to use microphones, but nothing helps. vol is always 0, but after pressing the "passthru" button, the sound is heard without change

### Logs on console

File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 37, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[VCClient] wait web server... done 200
[2023-09-28 23:42:16] connet sid : zJPdKvpzxv-Kc4roAAAC
[2023-09-28 23:42:16] connet sid : ms59oVJ01ZKzCnh5AAAD
[Voice Changer] update configuration: modelSlotIndex 1695934018006
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] update configuration: modelSlotIndex 1695934020006
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by w-okada** [comment]
same 

https://github.com/w-okada/voice-changer/issues/851
