### ISSUE TITLE
[ISSUE]: Vol. 0 always

### ISSUE THREAD

**Issue by RichterPyre** [w-okada/voice-changer#905]
### Voice Changer Version

Newest

### Operational System

windows 11

### GPU

rtx 3050

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

When I press start, the ping changes, but the sound always remains at 0, if you turn on passthru mode, then everything is fine (but the changer itself does not work in this mode)

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/145543532/43cb6820-d07f-497e-877f-bbab09cd3dde)

### Logs on console

C:\Users\cryni\OneDrive\Рабочий стол\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
2023-09-29 13:54:06.1591546 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] exception! loading inferencer [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model_dir\2\kikoto_mahiro_v2_40k_simple.onnx failed:Protobuf parsing failed.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model_dir\2\kikoto_mahiro_v2_40k_simple.onnx failed:Protobuf parsing failed.
[VCClient] wait web server... done 200
[2023-09-29 13:56:56] connet sid : Rs6IocnAYVPjj9xHAAAC
[2023-09-29 13:56:57] connet sid : iD4-_zXlCYqBMg-CAAAD
[Voice Changer] update configuration: modelSlotIndex 1695974222003
[Voice Changer] exception! loading inferencer [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model_dir\3\tokina_shigure_v2_40k_e100_simple.onnx failed:Protobuf parsing failed.
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model_dir\3\tokina_shigure_v2_40k_e100_simple.onnx failed:Protobuf parsing failed.
[Voice Changer] update configuration: f0Detector dio

**Comment by exciar** [comment]
lower your chunk to 64 and set extra to 8192

**Comment by RichterPyre** [comment]
> lower your chunk to 64 and set extra to 8192

Still the same

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/462
