### ISSUE TITLE
[ISSUE]: wait web server problem

### ISSUE THREAD

**Issue by Gustavo133562** [w-okada/voice-changer#935]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.14.zip

### Operational System

Windows 10

### GPU

RX6800XT Powercolor Red Devil 

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

I've tried different versions up to 1.5.3.11, but the same problem persists - "wait web server". I've reinstalled the program, disabled the antivirus, turned off the firewall, added everything to exceptions in the antivirus, granted permissions in the firewall, and even tried opening HTTP in the browser (no connection). Nothing helps, I don't know what to do. Could it be related to the graphics card?

### Application Screenshot

![1696801318513](https://github.com/w-okada/voice-changer/assets/147350866/1eeb6c9c-3c53-4e7b-b3d1-053ce6cfc199)

### Logs on console

Please open the following URL in your browser.
http://:/
In many cases, it will launch when you access any of the following URLs.
http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
Booting PHASE :main
Booting PHASE :MMVCServerSIO
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/

**Comment by w-okada** [comment]
maybe same

https://github.com/w-okada/voice-changer/issues/928

**Comment by Gustavo133562** [comment]
> maybe same
> 
> https://github.com/w-okada/voice-changer/issues/928

I think it's not the same thing. The program installs, starts, and a window with the client appears, but it's just white, and it says "wait web server...0...10...20" endlessly. I've tried everything with the antivirus, maybe installing Windows 11 would help, but I don't want to switch from Windows 10 to it.

**Comment by Nishikinov** [comment]
Same problem on RX5700XT, tried all versions from 1.5.3.11 to 1.5.3.15. Another interesting detail is that I recently tried a GTX 1060 card on the same system and the GUI started up.

**Comment by w-okada** [comment]
So, I have no idea.

**Comment by LagBerry** [comment]
for me i fixed this issue by deleting the stored_settings.json file and disabling firewall

**Comment by Gustavo133562** [comment]
> for me i fixed this issue by deleting the stored_settings.json file and disabling firewall

 I don't have that file and i tried to disable firewall, no result

**Comment by ShatterinSpider** [comment]
I tried The DirectML ver, and multiple Cuda versions, non works. All dependencies are downloaded, tried with fire enabled, disabled and even allowed both programs through my firewall to see. I got it to work on google collab, and open the ui but I couldn't get my voice to change there. I just don't think it works on an all AMD PC honestly.

**Comment by ShatterinSpider** [comment]
Anyone who got a version of the program to work can you send your batch log to compare. I wanna try and examine the difference between them so see if there's any differences in how the program runs.

`
D:\Users\Offic\Downloads\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.16a\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    **http://127.0.0.1:18888/**

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server...10 http://127.0.0.1:18888/
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 258, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt
Terminate batch job (Y/N)?`

The URL I bolded is something different I saw compared to tutorials online which had localhost:18888 instead.

**Comment by Nekilsior** [comment]
I have the same problem, can anyone solve it?

**Comment by weewoo-teehee** [comment]
I have an AMD PC as well but it worked perfectly well for like 2 months and now it's just like not tryna work now lol there's only

 Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server...10 http://127.0.0.1:18888/

**Comment by Gustavo133562** [comment]
> I have an AMD PC as well but it worked perfectly well for like 2 months and now it's just like not tryna work now lol there's only
> 
>  Booting PHASE :__main__
>     PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
>     Activating the Voice Changer.
> [Voice Changer] download sample catalog. samples_0003_t2.json
> [Voice Changer] download sample catalog. samples_0003_o2.json
> [Voice Changer] download sample catalog. samples_0003_d2.json
> [Voice Changer] model_dir is already exists. skip download samples.
>     Internal_Port:18888
>     protocol: HTTP
>     -- ---- --
>     Please open the following URL in your browser.
>     http://<IP>:<PORT>/
>     In many cases, it will launch when you access any of the following URLs.
>     http://127.0.0.1:18888/
> 
> [VCClient] Access http://127.0.0.1:18888/
> [VCClient] wait web server...0 http://127.0.0.1:18888/
> [VCClient] wait web server...10 http://127.0.0.1:18888/

Strange things, maybe it's because AMD?

**Comment by Gustavo133562** [comment]
According to statistics, this problem is most common in AMD gpu

**Comment by rizalkhaerul96** [comment]
![win A.PNG](https://github.com/user-attachments/assets/24857387-59a2-48b2-acd7-df6c1474f492)

![Preview win A.PNG](https://github.com/user-attachments/assets/0ebbf19c-4186-4653-a36d-63e3da4affec)

![music.PNG](https://github.com/user-attachments/assets/b7cbc372-9a73-408d-9769-2adcaa739657)

![Screanshot A Song AKR96III,amg.PNG](https://github.com/user-attachments/assets/648c814b-2e53-474f-9fee-459d990ca7ab)

MicroORGANISM OS microsoft Windows (A) Version build high tech version standard from A.KR96III,Amg. 2036 
.
.
./sample apk support and ios in 6G era of high tech at #goddyfarious A.KR96III,Amg. (Instagram info @ae.rizalkhaerul9630.amg/@illahiyahwe)
.
./Hee <peace> good luck ;)
