### ISSUE TITLE
[REQUEST]: bug

### ISSUE THREAD

**Issue by OverLookk** [w-okada/voice-changer#946]
### In a few words, describe your idea

[14528] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

### More information

Traceback (most recent call last):
  File "MMVCServerSIO.py", line 33, in <module>
  File "mods\log_control.py", line 63, in initialize
  File "logging\__init__.py", line 1169, in __init__
  File "logging\__init__.py", line 1201, in _open
PermissionError: [Errno 13] Permission denied: 'O:\\ai voice\\MMVCServerSIO\\vcclient.log'
[14528] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

i open the start_http.bat file and get that and then it closes

**Comment by w-okada** [comment]
use this one. thanks

![image](https://github.com/w-okada/voice-changer/assets/48346627/e3e2859f-f3b1-4fcf-87d8-339fd4ca10ed)
