### ISSUE TITLE
[ISSUE]: start_http doesnt work when i load it it just closes instantly i searched for an hour now and nothing seems to work

### ISSUE THREAD

**Issue by danidany** [w-okada/voice-changer#950]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v1.5.3.15.zip

### Operational System

Windows 10

### GPU

RTX 3060

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

Idk what this means

### Issue Description

whenever i open the start_http it just always closes so fast and i looked for ages to find a fix but nothing seems to work 

### Application Screenshot

i got no settings since it wont open

### Logs on console

idk what that is

**Comment by tsonict** [comment]
Uninstall python from your computer, that worked for me.

**Comment by JustinSomers** [comment]
I'm getting the following error when running the bat file in the powershell:

```
C:\Users\justi\OneDrive\Documents\voiceai\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pythoncom.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "pywintypes.py", line 126, in <module>
  File "pywintypes.py", line 47, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\Users\\justi\\OneDrive\\Documents\\voiceai\\MMVCServerSIO\\base_library.zip', 'C:\\Users\\justi\\OneDrive\\Documents\\voiceai\\MMVCServerSIO\\lib-dynload', 'C:\\Users\\justi\\OneDrive\\Documents\\voiceai\\MMVCServerSIO', 'C:\\Users\\justi\\OneDrive\\Documents\\voiceai\\MMVCServerSIO\\pythonwin']
[16908] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!
```

**Comment by Yuuki2802** [comment]
having the same issue here

**Comment by Origami345Studio** [comment]
same here

**Comment by PorkDevMode** [comment]
Caused by renaming folder, or abruptly pausing unzipping. I fixed by downloading again and unzipping without changing folder name
