### ISSUE TITLE
[ISSUE]: [ONNXRuntimeError] Protobuf parsing failed

### ISSUE THREAD

**Issue by khrystalr1** [w-okada/voice-changer#963]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15.zip

### Operational System

Windows 10

### GPU

GeForce GTX 1650

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

After I was succesfully launch the client, I'm clicking the RVC model and then the client just going white blank, trying to re-launch and now the cmd having this issue (the client just went white blank after re-launch)

### Logs on console

MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-10-24 04:40:12] connet sid : I7mAn-ygfWgs7R0OAAAC
[2023-10-24 04:40:12] connet sid : pxpzhMO71m7gX6pGAAAD
[Voice Changer] update configuration: modelSlotIndex 1698097224000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2023-10-24 04:40:25.9621980 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-10-24 04:40:25.9674722 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
2023-10-24 04:40:27.0871336 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-10-24 04:40:27.0923293 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] post_update_settings ex: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/rmvpe.onnx failed:Protobuf parsing failed.
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 315, in update_settings
  File "voice_changer\VoiceChangerManager.py", line 321, in update_settings
  File "voice_changer\VoiceChangerV2.py", line 155, in update_settings
  File "voice_changer\RVC\RVCr2.py", line 73, in update_settings
  File "voice_changer\RVC\RVCr2.py", line 51, in initialize
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 42, in createPipeline
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 25, in getPitchExtractor
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 45, in loadPitchExtractor
  File "voice_changer\RVC\pitchExtractor\RMVPEOnnxPitchExtractor.py", line 28, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/rmvpe.onnx failed:Protobuf parsing failed.

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/488

**Comment by Moimeme919** [comment]
Same.
V. 16a

**Comment by mammad0066** [comment]
same
