### ISSUE TITLE
[ISSUE]: Help me please! I broke something and I need to fix it, but I have no idea how

### ISSUE THREAD

**Issue by wazene** [w-okada/voice-changer#977]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11

### Operational System

Windows 10

### GPU

Geforce GTX1650

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Hello there! I was using Okada voice changer for about a month now without any errors at all

But today I broke something cause of my stupidity. I missclicked and loaded some other audiodriver while voice changer was active, and this audio driver for some reason affected the virtual audio driver of voice changer itself (as I guess), so now it broke completely

Earlier everything was fine, buf 0 and res about a 1300, but now whenever I try to interact with voice changer, buf moves around 120-130 and res rising non stop. Help advice would be really appreciated

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/137265536/b21590f3-1cb9-43b8-bd5e-375c39ff347a)

![image](https://github.com/w-okada/voice-changer/assets/137265536/b32d7353-a967-4eb8-b367-183bdbb01d2a)

### Logs on console

[VCClient] Access http://localhost:18888/
(node:6352) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:6352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2023-11-02 15:33:43.1468964 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Preparing your application. Please wait...
(node:6352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 30
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVCr2] Initializing...
Preparing your application. Please wait...
(node:6352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] Loading index...
Try loading... model_dir\30\trained_IVF908_Flat_nprobe_1_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000002E10D640610>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002E1488A6680>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002E1488A66B0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
2023-11-02 15:33:49.9142533 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1018 onnxruntime::ProviderSharedLibrary::Ensure [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Smush\OneDrive\¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ \VOICE CHANGER\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11\MMVCServerSIO\onnxruntime\capi\onnxruntime_providers_shared.dll"

2023-11-02 15:33:49.9274092 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
[Voice Changer] Loading index...
Try loading... model_dir\30\trained_IVF908_Flat_nprobe_1_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000002E1488A6EF0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002E18441D510>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002E18441D570>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:crepe_tiny
2023-11-02 15:33:50.4062194 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1018 onnxruntime::ProviderSharedLibrary::Ensure [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Smush\OneDrive\¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ \VOICE CHANGER\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11\MMVCServerSIO\onnxruntime\capi\onnxruntime_providers_shared.dll"

2023-11-02 15:33:50.4174823 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
[Voice Changer][RVC]: update_settings silentThreshold:0
[Voice Changer][RVC]: update_settings serverReadChunkSize:48
Preparing your application. Please wait...
(node:6352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings modelSlotIndex:1698913886030
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[2023-11-02 15:33:53] connet sid : KJxW6gvDCUSqMTm6AAAB
[2023-11-02 15:33:53] connet sid : WuijvURqMiI15_buAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[2023-11-02 15:34:35] connet sid : -M50dtS2UKYTXM8OAAAF
[2023-11-02 15:35:46] connet sid : 3sTW6YYGUAsH_AuMAAAH
[Voice Changer] update configuration: modelSlotIndex 1698914459000
[Voice Changer] model slot is changed 30 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVCr2] Initializing...
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000002E1888FE350>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002E1888FD810>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002E1888FD6C0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2023-11-02 15:41:02.7709215 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1018 onnxruntime::ProviderSharedLibrary::Ensure [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Smush\OneDrive\¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ \VOICE CHANGER\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11\MMVCServerSIO\onnxruntime\capi\onnxruntime_providers_shared.dll"

2023-11-02 15:41:02.7840157 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
[Voice Changer] generate new embedder. (anyway)
2023-11-02 15:41:05.8381863 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1018 onnxruntime::ProviderSharedLibrary::Ensure [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Smush\OneDrive\¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ \VOICE CHANGER\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11\MMVCServerSIO\onnxruntime\capi\onnxruntime_providers_shared.dll"

2023-11-02 15:41:05.8505920 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
[Voice Changer] Loading index...
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000002E14885A290>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002E148859630>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002E1488594B0>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer][RVC]: update_settings f0Detector:crepe_tiny
2023-11-02 15:41:06.5869479 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1018 onnxruntime::ProviderSharedLibrary::Ensure [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Smush\OneDrive\¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ \VOICE CHANGER\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11\MMVCServerSIO\onnxruntime\capi\onnxruntime_providers_shared.dll"

2023-11-02 15:41:06.5989733 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
[Voice Changer][RVC]: update_settings silentThreshold:0
[Voice Changer][RVC]: update_settings serverReadChunkSize:48
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings modelSlotIndex:1698914459000
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[2023-11-02 15:54:58] connet sid : 5nUdWghK4mXYQT3zAAAJ
post request handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 288, in handle_request
  File "engineio\asyncio_socket.py", line 109, in handle_post_request
  File "engineio\payload.py", line 13, in __init__
  File "engineio\payload.py", line 44, in decode
ValueError: Too many packets in payload
message async handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 455, in _trigger_event
  File "socketio\asyncio_server.py", line 592, in _handle_eio_message
  File "socketio\packet.py", line 43, in __init__
  File "socketio\packet.py", line 77, in decode
ValueError: invalid literal for int() with base 10: b'\x00'
<class 'str'>
51-/test,["request_message",[1698915298711,{"_placeholder":true,"num":0}]]

Please, tell me, if this can be fixed, or I can fix it by reinstalling the voice changer, because I need it very much

**Comment by wazene** [comment]
please help

**Comment by wazene** [comment]
please help

**Comment by wazene** [comment]
*bump*

**Comment by sasaki0487** [comment]
[ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Smush\OneDrive\¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤ ¤ \VOICE CHANGER\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11\MMVCServerSIO\onnxruntime\capi\onnxruntime_providers_shared.dll"

AI backend tried to load the dll but it **might** be missing. 
I think you can just remove the app and reinstall to fix.

**Comment by w-okada** [comment]
extract files from zip to the folder whose path contains only ASCII Charcter
