### ISSUE TITLE
[ISSUE]: exception! loading inferencer invalid load key, '\x08'.

### ISSUE THREAD

**Issue by Chocobonis** [w-okada/voice-changer#979]
### Voice Changer Version

MMVCserver

### Operational System

linux

### GPU

RADEON

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

exception! loading inferencer invalid load key, '\x08'.

[Voice Changer] update configuration: modelSlotIndex 1699028347000
[Voice Changer] model slot is changed 3 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/pipeline/PipelineGenerator.py", line 22, in createPipeline
    inferencer = InferencerManager.getInferencer(modelSlot.modelType, modelPath, gpu, modelSlot.version)
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/inferencer/InferencerManager.py", line 25, in getInferencer
    cls.currentInferencer = cls.loadInferencer(inferencerType, file, gpu, inferencerTypeVersion)
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/inferencer/InferencerManager.py", line 37, in loadInferencer
    return RVCInferencer().loadModel(file, gpu)
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/inferencer/RVCInferencer.py", line 16, in loadModel
    cpt = torch.load(file, map_location="cpu")
  File "/home/pentabonyx/.conda/envs/vcclient-dev/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/pentabonyx/.conda/envs/vcclient-dev/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputDeviceId:2
[Voice Changer][RVC]: update_settings serverOutputDeviceId:-1
[Voice Changer][RVC]: update_settings modelSlotIndex:1699028347000
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.

### Logs on console

[Voice Changer] update configuration: modelSlotIndex 1699028347000
[Voice Changer] model slot is changed 3 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] exception! loading inferencer invalid load key, '\x08'.
Traceback (most recent call last):
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/pipeline/PipelineGenerator.py", line 22, in createPipeline
    inferencer = InferencerManager.getInferencer(modelSlot.modelType, modelPath, gpu, modelSlot.version)
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/inferencer/InferencerManager.py", line 25, in getInferencer
    cls.currentInferencer = cls.loadInferencer(inferencerType, file, gpu, inferencerTypeVersion)
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/inferencer/InferencerManager.py", line 37, in loadInferencer
    return RVCInferencer().loadModel(file, gpu)
  File "/home/pentabonyx/voice-changer/server/voice_changer/RVC/inferencer/RVCInferencer.py", line 16, in loadModel
    cpt = torch.load(file, map_location="cpu")
  File "/home/pentabonyx/.conda/envs/vcclient-dev/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/pentabonyx/.conda/envs/vcclient-dev/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputDeviceId:2
[Voice Changer][RVC]: update_settings serverOutputDeviceId:-1
[Voice Changer][RVC]: update_settings modelSlotIndex:1699028347000
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.

**Comment by Chocobonis** [comment]
the solution was that the use of japanese characters broke made the program not being able to read the voice files, I installed new voices and it started to work normally
